/* Generated by Yosys 0.65+57 (git sha1 9d0cdb855, clang++ 18.1.8 -fPIC -O3) */

/* hdlname = "mult_32" */
/* top =  1  */
/* src = "mult_32.v:1.1-20.14" */
module mult_32(clk, B, A, rst, init, PP, done);
  /* src = "mult_32.v:2.11-2.14" */
  input clk;
  wire clk;
  /* src = "mult_32.v:3.20-3.21" */
  input [15:0] B;
  wire [15:0] B;
  /* src = "mult_32.v:3.18-3.19" */
  input [15:0] A;
  wire [15:0] A;
  /* src = "mult_32.v:2.15-2.18" */
  input rst;
  wire rst;
  /* src = "mult_32.v:2.19-2.23" */
  input init;
  wire init;
  /* src = "mult_32.v:4.19-4.21" */
  output [31:0] PP;
  wire [31:0] PP;
  /* src = "mult_32.v:5.12-5.16" */
  output done;
  wire done;
  wire [14:0] B_LUT4_B_Z;
  /* hdlname = "acc0 A" */
  /* src = "acc.v:3.18-3.19" */
  wire [31:0] \acc0.A ;
  /* hdlname = "acc0 PP" */
  /* src = "acc.v:4.23-4.25" */
  wire [31:0] \acc0.PP ;
  /* hdlname = "acc0 clk" */
  /* src = "acc.v:2.11-2.14" */
  wire \acc0.clk ;
  /* hdlname = "acc0 rst" */
  /* src = "acc.v:2.16-2.19" */
  wire \acc0.rst ;
  /* hdlname = "comp0 B" */
  /* src = "comp.v:2.18-2.19" */
  wire [15:0] \comp0.B ;
  /* hdlname = "control0 clk" */
  /* src = "control_mult.v:3.8-3.11" */
  wire \control0.clk ;
  /* hdlname = "control0 cont" */
  /* src = "control_mult.v:31.12-31.16" */
  wire [4:0] \control0.cont ;
  /* abc9_carry = 32'd1 */
  /* src = "control_mult.v:68.22-68.30|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  /* unused_bits = "0" */
  wire \control0.cont_CCU2C_B0_COUT ;
  /* unused_bits = "0" */
  wire \control0.cont_CCU2C_B0_S1 ;
  /* abc9_carry = 32'd1 */
  /* src = "control_mult.v:68.22-68.30|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \control0.cont_CCU2C_B1_1_COUT ;
  /* unused_bits = "0" */
  wire \control0.cont_CCU2C_B1_1_S0 ;
  /* abc9_carry = 32'd1 */
  /* src = "control_mult.v:68.22-68.30|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \control0.cont_CCU2C_B1_COUT ;
  /* force_downto = 32'd1 */
  /* src = "control_mult.v:68.22-68.30|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:34.26-34.27" */
  wire [4:0] \control0.cont_TRELLIS_FF_Q_DI ;
  /* hdlname = "control0 done" */
  /* src = "control_mult.v:9.13-9.17" */
  wire \control0.done ;
  /* hdlname = "control0 init" */
  /* src = "control_mult.v:6.8-6.12" */
  wire \control0.init ;
  /* hdlname = "control0 lsb_B" */
  /* src = "control_mult.v:5.8-5.13" */
  wire \control0.lsb_B ;
  /* hdlname = "control0 rst" */
  /* src = "control_mult.v:4.8-4.11" */
  wire \control0.rst ;
  /* hdlname = "control0 state" */
  /* src = "control_mult.v:21.12-21.17" */
  wire [2:0] \control0.state ;
  wire \control0.state_TRELLIS_FF_Q_1_DI ;
  wire \control0.state_TRELLIS_FF_Q_2_DI ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [6:0] \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.66-157.68" */
  wire \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0 ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.50-157.52" */
  wire \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D0 ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.22-157.24" */
  wire \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_ALUT ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.18-157.20" */
  wire \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_BLUT ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.54-157.56" */
  wire \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D1 ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.30-157.32" */
  wire \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_ALUT ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.26-157.28" */
  wire \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_BLUT ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.70-157.72" */
  wire \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1 ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.58-157.60" */
  wire \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D0 ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.38-157.40" */
  wire \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_ALUT ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.34-157.36" */
  wire \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_BLUT ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.62-157.64" */
  wire \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D1 ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.46-157.48" */
  wire \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_ALUT ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.42-157.44" */
  wire \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_BLUT ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [6:0] \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_SD ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_PFUMX_Z_ALUT ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_PFUMX_Z_BLUT ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [4:0] \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_PFUMX_Z_C0 ;
  wire \control0.state_TRELLIS_FF_Q_DI ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.66-157.68" */
  wire \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0 ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.50-157.52" */
  wire \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0 ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.22-157.24" */
  wire \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_ALUT ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.18-157.20" */
  wire \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_BLUT ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.54-157.56" */
  wire \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1 ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.30-157.32" */
  wire \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_ALUT ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.26-157.28" */
  wire \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_BLUT ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.70-157.72" */
  wire \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1 ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.58-157.60" */
  wire \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0 ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.38-157.40" */
  wire \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_ALUT ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.34-157.36" */
  wire \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_BLUT ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.62-157.64" */
  wire \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1 ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.46-157.48" */
  wire \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_ALUT ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.42-157.44" */
  wire \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_BLUT ;
  wire done_LUT4_D_Z;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [1:0] done_PFUMX_C0_Z;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [4:0] init_LUT4_A_Z;
  /* hdlname = "lsr0 clk" */
  /* src = "lsr.v:2.11-2.14" */
  wire \lsr0.clk ;
  /* hdlname = "lsr0 in_A" */
  /* src = "lsr.v:3.18-3.22" */
  /* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15" */
  wire [15:0] \lsr0.in_A ;
  /* hdlname = "lsr0 s_A" */
  /* src = "lsr.v:4.23-4.26" */
  wire [30:0] \lsr0.s_A ;
  /* hdlname = "rsr0 clk" */
  /* src = "rsr.v:2.11-2.14" */
  wire \rsr0.clk ;
  /* hdlname = "rsr0 in_B" */
  /* src = "rsr.v:3.18-3.22" */
  wire [15:0] \rsr0.in_B ;
  /* hdlname = "rsr0 s_B" */
  /* src = "rsr.v:4.23-4.26" */
  wire [15:0] \rsr0.s_B ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [3:0] \rsr0.s_B_TRELLIS_FF_Q_9_LSR ;
  wire \rsr0.s_B_TRELLIS_FF_Q_9_LSR_LUT4_D_Z ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire rst_LUT4_A_1_Z;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire rst_LUT4_A_2_Z;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [4:0] rst_LUT4_A_C;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] rst_LUT4_A_C_LUT4_B_Z;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire rst_LUT4_A_Z;
  wire rst_LUT4_A_Z_PFUMX_BLUT_Z;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire rst_LUT4_C_Z;
  /* src = "mult_32.v:11.17-11.20" */
  wire [31:0] w_A;
  /* src = "mult_32.v:12.17-12.20" */
  wire [31:0] w_B;
  /* src = "mult_32.v:17.30-17.35" */
  wire w_rst;
  /* src = "mult_32.v:10.17-10.20" */
  /* unused_bits = "0" */
  wire [15:0] w_z;
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B (
    .A(1'h0),
    .B(B[0]),
    .C(\rsr0.s_B [1]),
    .D(rst_LUT4_A_C_LUT4_B_Z[2]),
    .Z(B_LUT4_B_Z[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_1 (
    .A(1'h0),
    .B(B[1]),
    .C(\rsr0.s_B [2]),
    .D(rst_LUT4_A_C_LUT4_B_Z[2]),
    .Z(B_LUT4_B_Z[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_10 (
    .A(1'h0),
    .B(B[10]),
    .C(\rsr0.s_B [11]),
    .D(rst_LUT4_A_C_LUT4_B_Z[2]),
    .Z(B_LUT4_B_Z[10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_11 (
    .A(1'h0),
    .B(B[11]),
    .C(\rsr0.s_B [12]),
    .D(rst_LUT4_A_C_LUT4_B_Z[2]),
    .Z(B_LUT4_B_Z[11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_12 (
    .A(1'h0),
    .B(B[12]),
    .C(\rsr0.s_B [13]),
    .D(rst_LUT4_A_C_LUT4_B_Z[2]),
    .Z(B_LUT4_B_Z[12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_13 (
    .A(1'h0),
    .B(B[13]),
    .C(\rsr0.s_B [14]),
    .D(rst_LUT4_A_C_LUT4_B_Z[2]),
    .Z(B_LUT4_B_Z[13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_14 (
    .A(1'h0),
    .B(B[14]),
    .C(\rsr0.s_B [15]),
    .D(rst_LUT4_A_C_LUT4_B_Z[2]),
    .Z(B_LUT4_B_Z[14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_2 (
    .A(1'h0),
    .B(B[2]),
    .C(\rsr0.s_B [3]),
    .D(rst_LUT4_A_C_LUT4_B_Z[2]),
    .Z(B_LUT4_B_Z[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_3 (
    .A(1'h0),
    .B(B[3]),
    .C(\rsr0.s_B [4]),
    .D(rst_LUT4_A_C_LUT4_B_Z[2]),
    .Z(B_LUT4_B_Z[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_4 (
    .A(1'h0),
    .B(B[4]),
    .C(\rsr0.s_B [5]),
    .D(rst_LUT4_A_C_LUT4_B_Z[2]),
    .Z(B_LUT4_B_Z[4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_5 (
    .A(1'h0),
    .B(B[5]),
    .C(\rsr0.s_B [6]),
    .D(rst_LUT4_A_C_LUT4_B_Z[2]),
    .Z(B_LUT4_B_Z[5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_6 (
    .A(1'h0),
    .B(B[6]),
    .C(\rsr0.s_B [7]),
    .D(rst_LUT4_A_C_LUT4_B_Z[2]),
    .Z(B_LUT4_B_Z[6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_7 (
    .A(1'h0),
    .B(B[7]),
    .C(\rsr0.s_B [8]),
    .D(rst_LUT4_A_C_LUT4_B_Z[2]),
    .Z(B_LUT4_B_Z[7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_8 (
    .A(1'h0),
    .B(B[8]),
    .C(\rsr0.s_B [9]),
    .D(rst_LUT4_A_C_LUT4_B_Z[2]),
    .Z(B_LUT4_B_Z[8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) B_LUT4_B_9 (
    .A(1'h0),
    .B(B[9]),
    .C(\rsr0.s_B [10]),
    .D(rst_LUT4_A_C_LUT4_B_Z[2]),
    .Z(B_LUT4_B_Z[9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:68.22-68.30|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \control0.cont_CCU2C_B0  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\control0.cont [4]),
    .B1(1'h0),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\control0.cont_CCU2C_B1_COUT ),
    .COUT(\control0.cont_CCU2C_B0_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\control0.cont_TRELLIS_FF_Q_DI [4]),
    .S1(\control0.cont_CCU2C_B0_S1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:68.22-68.30|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \control0.cont_CCU2C_B1  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\control0.cont [2]),
    .B1(\control0.cont [3]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\control0.cont_CCU2C_B1_1_COUT ),
    .COUT(\control0.cont_CCU2C_B1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\control0.cont_TRELLIS_FF_Q_DI [2]),
    .S1(\control0.cont_TRELLIS_FF_Q_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:68.22-68.30|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \control0.cont_CCU2C_B1_1  (
    .A0(1'h1),
    .A1(1'h0),
    .B0(\control0.cont [0]),
    .B1(\control0.cont [1]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(1'h0),
    .COUT(\control0.cont_CCU2C_B1_1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\control0.cont_CCU2C_B1_1_S0 ),
    .S1(\control0.cont_TRELLIS_FF_Q_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:114.33-115.56" */
  LUT4 #(
    .INIT(16'h00ff)
  ) \control0.cont_LUT4_D  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\control0.cont [0]),
    .Z(\control0.cont_TRELLIS_FF_Q_DI [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:33.1-76.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q  (
    .CE(done_PFUMX_C0_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [1]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:33.1-76.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q_1  (
    .CE(done_PFUMX_C0_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [2]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:33.1-76.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q_2  (
    .CE(done_PFUMX_C0_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [0]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:33.1-76.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q_3  (
    .CE(done_PFUMX_C0_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [3]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:33.1-76.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q_4  (
    .CE(done_PFUMX_C0_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [4]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:33.1-76.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.state_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\control0.state_TRELLIS_FF_Q_DI ),
    .LSR(rst_LUT4_A_Z_PFUMX_BLUT_Z),
    .Q(\control0.state [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:33.1-76.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.state_TRELLIS_FF_Q_1  (
    .CLK(clk),
    .DI(\control0.state_TRELLIS_FF_Q_1_DI ),
    .LSR(rst_LUT4_A_Z_PFUMX_BLUT_Z),
    .Q(\control0.state [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hdccc)
  ) \control0.state_TRELLIS_FF_Q_1_DI_LUT4_Z  (
    .A(\control0.state [2]),
    .B(rst_LUT4_A_C[2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.state_TRELLIS_FF_Q_1_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_mult.v:33.1-76.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.state_TRELLIS_FF_Q_2  (
    .CLK(clk),
    .DI(\control0.state_TRELLIS_FF_Q_2_DI ),
    .LSR(rst_LUT4_A_Z_PFUMX_BLUT_Z),
    .Q(\control0.state [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'haeee)
  ) \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z  (
    .A(init_LUT4_A_Z[2]),
    .B(\rsr0.s_B_TRELLIS_FF_Q_9_LSR [1]),
    .C(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D [5]),
    .D(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D [6]),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:184.21-184.63" */
  L6MUX21 \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z  (
    .D0(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0 ),
    .D1(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1 ),
    .SD(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_SD [6]),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:182.21-182.64" */
  L6MUX21 \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z  (
    .D0(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D0 ),
    .D1(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D1 ),
    .SD(\rsr0.s_B [8]),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:178.19-178.65" */
  PFUMX \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z  (
    .ALUT(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_ALUT ),
    .BLUT(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_BLUT ),
    .C0(\rsr0.s_B [9]),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D0 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:160.39-161.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:158.39-159.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:179.19-179.65" */
  PFUMX \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z  (
    .ALUT(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_ALUT ),
    .BLUT(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_BLUT ),
    .C0(\rsr0.s_B [9]),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:165.39-166.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:163.39-164.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:183.21-183.64" */
  L6MUX21 \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z  (
    .D0(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D0 ),
    .D1(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D1 ),
    .SD(\rsr0.s_B [8]),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:180.19-180.65" */
  PFUMX \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z  (
    .ALUT(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_ALUT ),
    .BLUT(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_BLUT ),
    .C0(\rsr0.s_B [9]),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D0 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:170.39-171.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:168.39-169.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_BLUT_LUT4_Z  (
    .A(\rsr0.s_B [13]),
    .B(\rsr0.s_B [12]),
    .C(\rsr0.s_B [11]),
    .D(\rsr0.s_B [10]),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:181.19-181.65" */
  PFUMX \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z  (
    .ALUT(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_ALUT ),
    .BLUT(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_BLUT ),
    .C0(\rsr0.s_B [9]),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:175.41-176.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:173.41-174.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h000f)
  ) \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_SD_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(\rsr0.s_B [15]),
    .D(\rsr0.s_B [14]),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_SD [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_PFUMX_Z  (
    .ALUT(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_PFUMX_Z_ALUT ),
    .BLUT(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_PFUMX_Z_BLUT ),
    .C0(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_PFUMX_Z_C0 [4]),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_PFUMX_Z_ALUT_LUT4_Z  (
    .A(\rsr0.s_B [7]),
    .B(\rsr0.s_B [6]),
    .C(\rsr0.s_B [5]),
    .D(\rsr0.s_B [4]),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_PFUMX_Z_C0_LUT4_Z  (
    .A(\rsr0.s_B [3]),
    .B(\rsr0.s_B [2]),
    .C(\rsr0.s_B [1]),
    .D(\rsr0.s_B [0]),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_PFUMX_Z_C0 [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:184.21-184.63" */
  L6MUX21 \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z  (
    .D0(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0 ),
    .D1(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1 ),
    .SD(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D [6]),
    .Z(\control0.state_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:182.21-182.64" */
  L6MUX21 \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z  (
    .D0(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0 ),
    .D1(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1 ),
    .SD(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D [5]),
    .Z(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:178.19-178.65" */
  PFUMX \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z  (
    .ALUT(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_ALUT ),
    .BLUT(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_BLUT ),
    .C0(init_LUT4_A_Z[3]),
    .Z(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:160.39-161.56" */
  LUT4 #(
    .INIT(16'h0004)
  ) \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_ALUT_LUT4_Z  (
    .A(\control0.cont [3]),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:158.39-159.56" */
  LUT4 #(
    .INIT(16'h000c)
  ) \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:179.19-179.65" */
  PFUMX \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z  (
    .ALUT(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_ALUT ),
    .BLUT(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_BLUT ),
    .C0(init_LUT4_A_Z[3]),
    .Z(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:165.39-166.56" */
  LUT4 #(
    .INIT(16'h0004)
  ) \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_ALUT_LUT4_Z  (
    .A(\control0.cont [3]),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:163.39-164.56" */
  LUT4 #(
    .INIT(16'h000c)
  ) \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:183.21-183.64" */
  L6MUX21 \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z  (
    .D0(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0 ),
    .D1(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1 ),
    .SD(\control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D [5]),
    .Z(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:180.19-180.65" */
  PFUMX \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z  (
    .ALUT(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_ALUT ),
    .BLUT(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_BLUT ),
    .C0(init_LUT4_A_Z[3]),
    .Z(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:170.39-171.56" */
  LUT4 #(
    .INIT(16'h0004)
  ) \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_ALUT_LUT4_Z  (
    .A(\control0.cont [3]),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:168.39-169.56" */
  LUT4 #(
    .INIT(16'h000c)
  ) \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:181.19-181.65" */
  PFUMX \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z  (
    .ALUT(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_ALUT ),
    .BLUT(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_BLUT ),
    .C0(init_LUT4_A_Z[3]),
    .Z(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:175.41-176.56" */
  LUT4 #(
    .INIT(16'h0034)
  ) \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_ALUT_LUT4_Z  (
    .A(\control0.cont [3]),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:173.41-174.56" */
  LUT4 #(
    .INIT(16'h003c)
  ) \control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.state_TRELLIS_FF_Q_DI_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h00f0)
  ) done_LUT4_D (
    .A(1'h0),
    .B(1'h0),
    .C(done_PFUMX_C0_Z[0]),
    .D(done),
    .Z(done_LUT4_D_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h000c)
  ) done_LUT4_Z (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(done)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX done_PFUMX_C0 (
    .ALUT(rst_LUT4_A_2_Z),
    .BLUT(rst_LUT4_C_Z),
    .C0(done),
    .Z(done_PFUMX_C0_Z[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0002)
  ) init_LUT4_A (
    .A(init),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(init_LUT4_A_Z[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0008)
  ) init_LUT4_A_Z_LUT4_Z (
    .A(\control0.cont [4]),
    .B(\control0.cont [2]),
    .C(\control0.cont [1]),
    .D(\control0.cont [0]),
    .Z(init_LUT4_A_Z[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:6.5-13.12|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_9_LSR_LUT4_D_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[7]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:6.5-13.12|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_1  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_9_LSR_LUT4_D_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[8]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:6.5-13.12|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_10  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_9_LSR_LUT4_D_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[1]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:6.5-13.12|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_11  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_9_LSR_LUT4_D_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[2]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:6.5-13.12|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_12  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_9_LSR_LUT4_D_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[3]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:6.5-13.12|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_13  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_9_LSR_LUT4_D_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[4]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:6.5-13.12|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_14  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_9_LSR_LUT4_D_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[5]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:6.5-13.12|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_15  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_9_LSR_LUT4_D_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[6]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:6.5-13.12|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_2  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_9_LSR_LUT4_D_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[9]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:6.5-13.12|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_3  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_9_LSR_LUT4_D_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[10]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:6.5-13.12|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_4  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_9_LSR_LUT4_D_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[11]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:6.5-13.12|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_5  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_9_LSR_LUT4_D_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[12]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:6.5-13.12|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_6  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_9_LSR_LUT4_D_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[13]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:6.5-13.12|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_7  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_9_LSR_LUT4_D_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[14]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:6.5-13.12|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:46.101-46.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.s_B_TRELLIS_FF_Q_8  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_9_LSR_LUT4_D_Z ),
    .CLK(clk),
    .DI(B_LUT4_B_Z[0]),
    .LSR(1'h0),
    .Q(\rsr0.s_B [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr.v:6.5-13.12|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:81.170-81.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("INV"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rsr0.s_B_TRELLIS_FF_Q_9  (
    .CE(\rsr0.s_B_TRELLIS_FF_Q_9_LSR_LUT4_D_Z ),
    .CLK(clk),
    .DI(B[15]),
    .LSR(\rsr0.s_B_TRELLIS_FF_Q_9_LSR [1]),
    .Q(\rsr0.s_B [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hfff0)
  ) \rsr0.s_B_TRELLIS_FF_Q_9_LSR_LUT4_D  (
    .A(1'h0),
    .B(1'h0),
    .C(rst_LUT4_A_C_LUT4_B_Z[2]),
    .D(\rsr0.s_B_TRELLIS_FF_Q_9_LSR [1]),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_LSR_LUT4_D_Z )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h0030)
  ) \rsr0.s_B_TRELLIS_FF_Q_9_LSR_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\rsr0.s_B_TRELLIS_FF_Q_9_LSR [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'haeaa)
  ) rst_LUT4_A (
    .A(rst),
    .B(\control0.state [2]),
    .C(rst_LUT4_A_C[2]),
    .D(\control0.state [1]),
    .Z(rst_LUT4_A_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'haeaf)
  ) rst_LUT4_A_1 (
    .A(rst),
    .B(\control0.state [2]),
    .C(rst_LUT4_A_C[2]),
    .D(\control0.state [1]),
    .Z(rst_LUT4_A_1_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h5155)
  ) rst_LUT4_A_2 (
    .A(rst),
    .B(\control0.cont [3]),
    .C(init_LUT4_A_Z[2]),
    .D(init_LUT4_A_Z[3]),
    .Z(rst_LUT4_A_2_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h2321)
  ) rst_LUT4_A_C_LUT4_B (
    .A(\control0.state [2]),
    .B(rst_LUT4_A_C[2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(rst_LUT4_A_C_LUT4_B_Z[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h0300)
  ) rst_LUT4_A_C_LUT4_Z (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(rst_LUT4_A_C[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX rst_LUT4_A_Z_PFUMX_BLUT (
    .ALUT(rst_LUT4_A_1_Z),
    .BLUT(rst_LUT4_A_Z),
    .C0(\control0.state [0]),
    .Z(rst_LUT4_A_Z_PFUMX_BLUT_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) rst_LUT4_C (
    .A(1'h0),
    .B(1'h0),
    .C(rst),
    .D(init_LUT4_A_Z[2]),
    .Z(rst_LUT4_C_Z)
  );
  assign { \rsr0.s_B_TRELLIS_FF_Q_9_LSR [3:2], \rsr0.s_B_TRELLIS_FF_Q_9_LSR [0] } = { \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D [6:5], init_LUT4_A_Z[2] };
  assign \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_L6MUX21_Z_SD [5:0] = { \rsr0.s_B [8], \rsr0.s_B [9], \rsr0.s_B [10], \rsr0.s_B [11], \rsr0.s_B [12], \rsr0.s_B [13] };
  assign \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D_PFUMX_Z_C0 [3:0] = { \rsr0.s_B [4], \rsr0.s_B [5], \rsr0.s_B [6], \rsr0.s_B [7] };
  assign \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z_D [4:0] = { init_LUT4_A_Z[3], \control0.state [0], \control0.state [1], \control0.state [2], \control0.cont [3] };
  assign rst_LUT4_A_C_LUT4_B_Z[1:0] = { \rsr0.s_B [2], B[1] };
  assign \acc0.A  = 32'b0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
  assign \comp0.B  = \rsr0.s_B ;
  assign \acc0.rst  = 1'hx;
  assign \lsr0.clk  = clk;
  assign \acc0.clk  = clk;
  assign \lsr0.in_A  = A;
  assign \lsr0.s_A  = 31'hxxxxxxxx;
  assign { rst_LUT4_A_C[4:3], rst_LUT4_A_C[1:0] } = { \control0.state [0], \control0.state [1], \control0.state [2], rst };
  assign { init_LUT4_A_Z[4], init_LUT4_A_Z[1:0] } = { done, \control0.cont [3], rst };
  assign done_PFUMX_C0_Z[1] = done;
  assign \rsr0.clk  = clk;
  assign \acc0.PP  = 32'd0;
  assign \rsr0.in_B  = B;
  assign \control0.done  = done;
  assign \control0.init  = init;
  assign \control0.lsb_B  = 1'hx;
  assign \control0.rst  = rst;
  assign \control0.clk  = clk;
  assign w_rst = 1'hx;
  assign w_B = { 16'h0000, \rsr0.s_B  };
  assign w_A = 32'b0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
  assign w_z[15:1] = 15'h0000;
  assign PP = 32'd0;
endmodule
