/* Generated by Yosys 0.65+57 (git sha1 9d0cdb855, clang++ 18.1.8 -fPIC -O3) */

/* hdlname = "bcd_to_bin_16" */
/* top =  1  */
/* src = "bcd_to_bin_16.v:1.1-26.10" */
module bcd_to_bin_16(clk, rst, init, A, BIN_out, done);
  /* src = "bcd_to_bin_16.v:2.11-2.14" */
  input clk;
  wire clk;
  /* src = "bcd_to_bin_16.v:2.16-2.19" */
  input rst;
  wire rst;
  /* src = "bcd_to_bin_16.v:2.21-2.25" */
  input init;
  wire init;
  /* src = "bcd_to_bin_16.v:3.18-3.19" */
  input [15:0] A;
  wire [15:0] A;
  /* src = "bcd_to_bin_16.v:4.19-4.26" */
  output [15:0] BIN_out;
  wire [15:0] BIN_out;
  /* src = "bcd_to_bin_16.v:5.12-5.16" */
  output done;
  wire done;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [3:0] A_LUT4_A_C;
  wire [31:16] A_LUT4_A_Z;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire A_LUT4_A_Z_PFUMX_Z_1_BLUT;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [4:0] A_LUT4_A_Z_PFUMX_Z_1_BLUT_LUT4_Z_D;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire A_LUT4_A_Z_PFUMX_Z_2_BLUT;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [4:0] A_LUT4_A_Z_PFUMX_Z_2_BLUT_LUT4_Z_D;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire A_LUT4_A_Z_PFUMX_Z_3_BLUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire A_LUT4_A_Z_PFUMX_Z_4_BLUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire A_LUT4_A_Z_PFUMX_Z_5_BLUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire A_LUT4_A_Z_PFUMX_Z_6_BLUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire A_LUT4_A_Z_PFUMX_Z_BLUT;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [4:0] A_LUT4_A_Z_PFUMX_Z_BLUT_LUT4_Z_D;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] A_LUT4_B_1_D;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire A_LUT4_B_1_D_PFUMX_Z_ALUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire A_LUT4_B_1_D_PFUMX_Z_BLUT;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] A_LUT4_B_2_C;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] A_LUT4_B_3_D;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire A_LUT4_B_3_D_PFUMX_Z_ALUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire A_LUT4_B_3_D_PFUMX_Z_BLUT;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] A_LUT4_B_4_D;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire A_LUT4_B_4_D_PFUMX_Z_ALUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire A_LUT4_B_4_D_PFUMX_Z_BLUT;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] A_LUT4_B_5_C;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] A_LUT4_B_6_C;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] A_LUT4_B_7_C;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] A_LUT4_B_D;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire A_LUT4_B_D_PFUMX_Z_ALUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire A_LUT4_B_D_PFUMX_Z_BLUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire A_LUT4_D_1_Z;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire A_LUT4_D_2_Z;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire A_LUT4_D_3_Z;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire A_LUT4_D_4_Z;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire A_LUT4_D_5_Z;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire A_LUT4_D_6_Z;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire A_LUT4_D_Z;
  /* hdlname = "acc0 in_bcd" */
  /* src = "acc_bcd_sub.v:2.18-2.24" */
  wire [15:0] \acc0.in_bcd ;
  /* hdlname = "comp_z0 val" */
  /* src = "comp_z.v:2.17-2.20" */
  wire [4:0] \comp_z0.val ;
  /* hdlname = "control0 clk" */
  /* src = "control_bcd_bin.v:2.11-2.14" */
  wire \control0.clk ;
  /* hdlname = "control0 cont" */
  /* src = "control_bcd_bin.v:12.15-12.19" */
  wire [4:0] \control0.cont ;
  /* force_downto = 32'd1 */
  /* src = "control_bcd_bin.v:39.32-39.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:34.26-34.27" */
  wire [4:0] \control0.cont_TRELLIS_FF_Q_DI ;
  /* abc9_carry = 32'd1 */
  /* src = "control_bcd_bin.v:39.32-39.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  /* unused_bits = "0" */
  wire \control0.cont_TRELLIS_FF_Q_DI_CCU2C_S0_COUT ;
  /* unused_bits = "0" */
  wire \control0.cont_TRELLIS_FF_Q_DI_CCU2C_S0_S1 ;
  /* abc9_carry = 32'd1 */
  /* src = "control_bcd_bin.v:39.32-39.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \control0.cont_TRELLIS_FF_Q_DI_CCU2C_S1_1_COUT ;
  /* unused_bits = "0" */
  wire \control0.cont_TRELLIS_FF_Q_DI_CCU2C_S1_1_S0 ;
  /* abc9_carry = 32'd1 */
  /* src = "control_bcd_bin.v:39.32-39.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \control0.cont_TRELLIS_FF_Q_DI_CCU2C_S1_COUT ;
  /* hdlname = "control0 done" */
  /* src = "control_bcd_bin.v:3.16-3.20" */
  wire \control0.done ;
  /* hdlname = "control0 init" */
  /* src = "control_bcd_bin.v:2.21-2.25" */
  wire \control0.init ;
  /* hdlname = "control0 rst" */
  /* src = "control_bcd_bin.v:2.16-2.19" */
  wire \control0.rst ;
  /* hdlname = "control0 state" */
  /* src = "control_bcd_bin.v:11.15-11.20" */
  wire [2:0] \control0.state ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [4:0] \control0.state_LUT4_D_1_Z ;
  wire \control0.state_TRELLIS_FF_Q_1_DI ;
  wire \control0.state_TRELLIS_FF_Q_2_DI ;
  wire \control0.state_TRELLIS_FF_Q_DI ;
  /* hdlname = "control0 w_sh_r" */
  /* src = "control_bcd_bin.v:3.22-3.28" */
  wire \control0.w_sh_r ;
  wire \control0.w_sh_r_LUT4_D_Z ;
  /* hdlname = "count0 clk" */
  /* src = "contador_desc.v:2.11-2.14" */
  wire \count0.clk ;
  /* hdlname = "count0 dec" */
  /* src = "contador_desc.v:2.22-2.25" */
  wire \count0.dec ;
  /* hdlname = "count0 val" */
  /* src = "contador_desc.v:3.22-3.25" */
  wire [4:0] \count0.val ;
  wire \count0.val_TRELLIS_FF_Q_1_DI ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [3:0] \count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D ;
  /* abc9_carry = 32'd1 */
  /* src = "contador_desc.v:11.27-11.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_CIN ;
  /* force_downto = 32'd1 */
  /* src = "contador_desc.v:11.27-11.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:34.26-34.27" */
  /* unused_bits = "4" */
  wire [4:0] \count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1 ;
  /* abc9_carry = 32'd1 */
  /* src = "contador_desc.v:11.27-11.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1_CCU2C_S1_COUT ;
  /* unused_bits = "0" */
  wire \count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1_CCU2C_S1_S0 ;
  /* abc9_carry = 32'd1 */
  /* src = "contador_desc.v:11.27-11.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  /* unused_bits = "0" */
  wire \count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_COUT ;
  /* unused_bits = "0" */
  wire \count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_S1 ;
  wire done_LUT4_D_Z;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] init_LUT4_A_Z;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [4:0] init_LUT4_A_Z_LUT4_D_B;
  /* hdlname = "rcr0 clk" */
  /* src = "rcr_32_combined.v:2.11-2.14" */
  wire \rcr0.clk ;
  /* hdlname = "rcr0 in_A" */
  /* src = "rcr_32_combined.v:3.18-3.22" */
  wire [31:0] \rcr0.in_A ;
  /* hdlname = "rcr0 s_out" */
  /* src = "rcr_32_combined.v:5.23-5.28" */
  wire [31:0] \rcr0.s_out ;
  wire \rcr0.s_out_TRELLIS_FF_Q_5_CE ;
  wire \rcr0.s_out_TRELLIS_FF_Q_7_CE ;
  wire \rcr0.s_out_TRELLIS_FF_Q_9_CE ;
  wire \rcr0.s_out_TRELLIS_FF_Q_CE ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] \rcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D ;
  /* hdlname = "rcr0 shift" */
  /* src = "rcr_32_combined.v:2.16-2.21" */
  wire \rcr0.shift ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [1:0] rst_LUT4_B_1_Z;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [6:0] rst_LUT4_B_C;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.66-157.68" */
  wire rst_LUT4_B_C_L6MUX21_SD_D0;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.50-157.52" */
  wire rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D0;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.22-157.24" */
  wire rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D0_PFUMX_Z_ALUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.18-157.20" */
  wire rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D0_PFUMX_Z_BLUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.54-157.56" */
  wire rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D1;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.30-157.32" */
  wire rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D1_PFUMX_Z_ALUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.26-157.28" */
  wire rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D1_PFUMX_Z_BLUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.70-157.72" */
  wire rst_LUT4_B_C_L6MUX21_SD_D1;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.58-157.60" */
  wire rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D0;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.38-157.40" */
  wire rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D0_PFUMX_Z_ALUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.34-157.36" */
  wire rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D0_PFUMX_Z_BLUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.62-157.64" */
  wire rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D1;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.46-157.48" */
  wire rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D1_PFUMX_Z_ALUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.42-157.44" */
  wire rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D1_PFUMX_Z_BLUT;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] rst_LUT4_B_C_L6MUX21_SD_Z;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire rst_LUT4_B_C_L6MUX21_SD_Z_PFUMX_Z_ALUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire rst_LUT4_B_C_L6MUX21_SD_Z_PFUMX_Z_BLUT;
  wire rst_LUT4_B_Z;
  /* src = "bcd_to_bin_16.v:9.17-9.27" */
  wire [15:0] w_BCD_part;
  /* src = "bcd_to_bin_16.v:8.17-8.27" */
  wire [31:0] w_combined;
  /* src = "bcd_to_bin_16.v:7.10-7.16" */
  wire w_sh_r;
  /* src = "bcd_to_bin_16.v:11.16-11.21" */
  wire [4:0] w_val;
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hab03)
  ) A_LUT4_A (
    .A(A[15]),
    .B(init_LUT4_A_Z_LUT4_D_B[4]),
    .C(A_LUT4_A_C[2]),
    .D(\control0.state_LUT4_D_1_Z [4]),
    .Z(A_LUT4_A_Z[31])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h5666)
  ) A_LUT4_A_C_LUT4_Z (
    .A(\rcr0.s_out [31]),
    .B(\rcr0.s_out [30]),
    .C(\rcr0.s_out [29]),
    .D(\rcr0.s_out [28]),
    .Z(A_LUT4_A_C[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX A_LUT4_A_Z_PFUMX_Z (
    .ALUT(A_LUT4_D_3_Z),
    .BLUT(A_LUT4_A_Z_PFUMX_Z_BLUT),
    .C0(\control0.state_LUT4_D_1_Z [4]),
    .Z(A_LUT4_A_Z[19])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX A_LUT4_A_Z_PFUMX_Z_1 (
    .ALUT(A_LUT4_D_4_Z),
    .BLUT(A_LUT4_A_Z_PFUMX_Z_1_BLUT),
    .C0(\control0.state_LUT4_D_1_Z [4]),
    .Z(A_LUT4_A_Z[23])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hcfc0)
  ) A_LUT4_A_Z_PFUMX_Z_1_BLUT_LUT4_Z (
    .A(1'h0),
    .B(\rcr0.s_out [24]),
    .C(init_LUT4_A_Z_LUT4_D_B[4]),
    .D(A_LUT4_A_Z_PFUMX_Z_1_BLUT_LUT4_Z_D[3]),
    .Z(A_LUT4_A_Z_PFUMX_Z_1_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'ha999)
  ) A_LUT4_A_Z_PFUMX_Z_1_BLUT_LUT4_Z_D_LUT4_Z (
    .A(\rcr0.s_out [23]),
    .B(\rcr0.s_out [22]),
    .C(\rcr0.s_out [21]),
    .D(\rcr0.s_out [20]),
    .Z(A_LUT4_A_Z_PFUMX_Z_1_BLUT_LUT4_Z_D[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX A_LUT4_A_Z_PFUMX_Z_2 (
    .ALUT(A_LUT4_D_5_Z),
    .BLUT(A_LUT4_A_Z_PFUMX_Z_2_BLUT),
    .C0(\control0.state_LUT4_D_1_Z [4]),
    .Z(A_LUT4_A_Z[27])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hcfc0)
  ) A_LUT4_A_Z_PFUMX_Z_2_BLUT_LUT4_Z (
    .A(1'h0),
    .B(\rcr0.s_out [28]),
    .C(init_LUT4_A_Z_LUT4_D_B[4]),
    .D(A_LUT4_A_Z_PFUMX_Z_2_BLUT_LUT4_Z_D[3]),
    .Z(A_LUT4_A_Z_PFUMX_Z_2_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'ha999)
  ) A_LUT4_A_Z_PFUMX_Z_2_BLUT_LUT4_Z_D_LUT4_Z (
    .A(\rcr0.s_out [27]),
    .B(\rcr0.s_out [26]),
    .C(\rcr0.s_out [25]),
    .D(\rcr0.s_out [24]),
    .Z(A_LUT4_A_Z_PFUMX_Z_2_BLUT_LUT4_Z_D[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX A_LUT4_A_Z_PFUMX_Z_3 (
    .ALUT(A_LUT4_D_Z),
    .BLUT(A_LUT4_A_Z_PFUMX_Z_3_BLUT),
    .C0(\control0.state_LUT4_D_1_Z [4]),
    .Z(A_LUT4_A_Z[24])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hcc0f)
  ) A_LUT4_A_Z_PFUMX_Z_3_BLUT_LUT4_Z (
    .A(1'h0),
    .B(\rcr0.s_out [25]),
    .C(\rcr0.s_out [24]),
    .D(init_LUT4_A_Z_LUT4_D_B[4]),
    .Z(A_LUT4_A_Z_PFUMX_Z_3_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX A_LUT4_A_Z_PFUMX_Z_4 (
    .ALUT(A_LUT4_D_6_Z),
    .BLUT(A_LUT4_A_Z_PFUMX_Z_4_BLUT),
    .C0(\control0.state_LUT4_D_1_Z [4]),
    .Z(A_LUT4_A_Z[20])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hcc0f)
  ) A_LUT4_A_Z_PFUMX_Z_4_BLUT_LUT4_Z (
    .A(1'h0),
    .B(\rcr0.s_out [21]),
    .C(\rcr0.s_out [20]),
    .D(init_LUT4_A_Z_LUT4_D_B[4]),
    .Z(A_LUT4_A_Z_PFUMX_Z_4_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX A_LUT4_A_Z_PFUMX_Z_5 (
    .ALUT(A_LUT4_D_1_Z),
    .BLUT(A_LUT4_A_Z_PFUMX_Z_5_BLUT),
    .C0(\control0.state_LUT4_D_1_Z [4]),
    .Z(A_LUT4_A_Z[16])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hcc0f)
  ) A_LUT4_A_Z_PFUMX_Z_5_BLUT_LUT4_Z (
    .A(1'h0),
    .B(\rcr0.s_out [17]),
    .C(\rcr0.s_out [16]),
    .D(init_LUT4_A_Z_LUT4_D_B[4]),
    .Z(A_LUT4_A_Z_PFUMX_Z_5_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX A_LUT4_A_Z_PFUMX_Z_6 (
    .ALUT(A_LUT4_D_2_Z),
    .BLUT(A_LUT4_A_Z_PFUMX_Z_6_BLUT),
    .C0(\control0.state_LUT4_D_1_Z [4]),
    .Z(A_LUT4_A_Z[28])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hcc0f)
  ) A_LUT4_A_Z_PFUMX_Z_6_BLUT_LUT4_Z (
    .A(1'h0),
    .B(\rcr0.s_out [29]),
    .C(\rcr0.s_out [28]),
    .D(init_LUT4_A_Z_LUT4_D_B[4]),
    .Z(A_LUT4_A_Z_PFUMX_Z_6_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hcfc0)
  ) A_LUT4_A_Z_PFUMX_Z_BLUT_LUT4_Z (
    .A(1'h0),
    .B(\rcr0.s_out [20]),
    .C(init_LUT4_A_Z_LUT4_D_B[4]),
    .D(A_LUT4_A_Z_PFUMX_Z_BLUT_LUT4_Z_D[3]),
    .Z(A_LUT4_A_Z_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'ha999)
  ) A_LUT4_A_Z_PFUMX_Z_BLUT_LUT4_Z_D_LUT4_Z (
    .A(\rcr0.s_out [19]),
    .B(\rcr0.s_out [18]),
    .C(\rcr0.s_out [17]),
    .D(\rcr0.s_out [16]),
    .Z(A_LUT4_A_Z_PFUMX_Z_BLUT_LUT4_Z_D[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hc0cf)
  ) A_LUT4_B (
    .A(1'h0),
    .B(A[14]),
    .C(\control0.state_LUT4_D_1_Z [4]),
    .D(A_LUT4_B_D[2]),
    .Z(A_LUT4_A_Z[30])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hc0cf)
  ) A_LUT4_B_1 (
    .A(1'h0),
    .B(A[6]),
    .C(\control0.state_LUT4_D_1_Z [4]),
    .D(A_LUT4_B_1_D[2]),
    .Z(A_LUT4_A_Z[22])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX A_LUT4_B_1_D_PFUMX_Z (
    .ALUT(A_LUT4_B_1_D_PFUMX_Z_ALUT),
    .BLUT(A_LUT4_B_1_D_PFUMX_Z_BLUT),
    .C0(init_LUT4_A_Z_LUT4_D_B[4]),
    .Z(A_LUT4_B_1_D[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h00ff)
  ) A_LUT4_B_1_D_PFUMX_Z_ALUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\rcr0.s_out [23]),
    .Z(A_LUT4_B_1_D_PFUMX_Z_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h3ccc)
  ) A_LUT4_B_1_D_PFUMX_Z_BLUT_LUT4_Z (
    .A(1'h0),
    .B(\rcr0.s_out [22]),
    .C(\rcr0.s_out [21]),
    .D(\rcr0.s_out [20]),
    .Z(A_LUT4_B_1_D_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_2 (
    .A(1'h0),
    .B(A[1]),
    .C(A_LUT4_B_2_C[1]),
    .D(\control0.state_LUT4_D_1_Z [4]),
    .Z(A_LUT4_A_Z[17])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'haa3c)
  ) A_LUT4_B_2_C_LUT4_Z (
    .A(\rcr0.s_out [18]),
    .B(\rcr0.s_out [17]),
    .C(\rcr0.s_out [16]),
    .D(init_LUT4_A_Z_LUT4_D_B[4]),
    .Z(A_LUT4_B_2_C[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hc0cf)
  ) A_LUT4_B_3 (
    .A(1'h0),
    .B(A[10]),
    .C(\control0.state_LUT4_D_1_Z [4]),
    .D(A_LUT4_B_3_D[2]),
    .Z(A_LUT4_A_Z[26])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX A_LUT4_B_3_D_PFUMX_Z (
    .ALUT(A_LUT4_B_3_D_PFUMX_Z_ALUT),
    .BLUT(A_LUT4_B_3_D_PFUMX_Z_BLUT),
    .C0(init_LUT4_A_Z_LUT4_D_B[4]),
    .Z(A_LUT4_B_3_D[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h00ff)
  ) A_LUT4_B_3_D_PFUMX_Z_ALUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\rcr0.s_out [27]),
    .Z(A_LUT4_B_3_D_PFUMX_Z_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h3ccc)
  ) A_LUT4_B_3_D_PFUMX_Z_BLUT_LUT4_Z (
    .A(1'h0),
    .B(\rcr0.s_out [26]),
    .C(\rcr0.s_out [25]),
    .D(\rcr0.s_out [24]),
    .Z(A_LUT4_B_3_D_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hc0cf)
  ) A_LUT4_B_4 (
    .A(1'h0),
    .B(A[2]),
    .C(\control0.state_LUT4_D_1_Z [4]),
    .D(A_LUT4_B_4_D[2]),
    .Z(A_LUT4_A_Z[18])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX A_LUT4_B_4_D_PFUMX_Z (
    .ALUT(A_LUT4_B_4_D_PFUMX_Z_ALUT),
    .BLUT(A_LUT4_B_4_D_PFUMX_Z_BLUT),
    .C0(init_LUT4_A_Z_LUT4_D_B[4]),
    .Z(A_LUT4_B_4_D[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h00ff)
  ) A_LUT4_B_4_D_PFUMX_Z_ALUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\rcr0.s_out [19]),
    .Z(A_LUT4_B_4_D_PFUMX_Z_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h3ccc)
  ) A_LUT4_B_4_D_PFUMX_Z_BLUT_LUT4_Z (
    .A(1'h0),
    .B(\rcr0.s_out [18]),
    .C(\rcr0.s_out [17]),
    .D(\rcr0.s_out [16]),
    .Z(A_LUT4_B_4_D_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_5 (
    .A(1'h0),
    .B(A[9]),
    .C(A_LUT4_B_5_C[1]),
    .D(\control0.state_LUT4_D_1_Z [4]),
    .Z(A_LUT4_A_Z[25])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'haa3c)
  ) A_LUT4_B_5_C_LUT4_Z (
    .A(\rcr0.s_out [26]),
    .B(\rcr0.s_out [25]),
    .C(\rcr0.s_out [24]),
    .D(init_LUT4_A_Z_LUT4_D_B[4]),
    .Z(A_LUT4_B_5_C[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_6 (
    .A(1'h0),
    .B(A[13]),
    .C(A_LUT4_B_6_C[1]),
    .D(\control0.state_LUT4_D_1_Z [4]),
    .Z(A_LUT4_A_Z[29])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'haa3c)
  ) A_LUT4_B_6_C_LUT4_Z (
    .A(\rcr0.s_out [30]),
    .B(\rcr0.s_out [29]),
    .C(\rcr0.s_out [28]),
    .D(init_LUT4_A_Z_LUT4_D_B[4]),
    .Z(A_LUT4_B_6_C[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_7 (
    .A(1'h0),
    .B(A[5]),
    .C(A_LUT4_B_7_C[1]),
    .D(\control0.state_LUT4_D_1_Z [4]),
    .Z(A_LUT4_A_Z[21])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'haa3c)
  ) A_LUT4_B_7_C_LUT4_Z (
    .A(\rcr0.s_out [22]),
    .B(\rcr0.s_out [21]),
    .C(\rcr0.s_out [20]),
    .D(init_LUT4_A_Z_LUT4_D_B[4]),
    .Z(A_LUT4_B_7_C[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX A_LUT4_B_D_PFUMX_Z (
    .ALUT(A_LUT4_B_D_PFUMX_Z_ALUT),
    .BLUT(A_LUT4_B_D_PFUMX_Z_BLUT),
    .C0(init_LUT4_A_Z_LUT4_D_B[4]),
    .Z(A_LUT4_B_D[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h00ff)
  ) A_LUT4_B_D_PFUMX_Z_ALUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\rcr0.s_out [31]),
    .Z(A_LUT4_B_D_PFUMX_Z_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h3ccc)
  ) A_LUT4_B_D_PFUMX_Z_BLUT_LUT4_Z (
    .A(1'h0),
    .B(\rcr0.s_out [30]),
    .C(\rcr0.s_out [29]),
    .D(\rcr0.s_out [28]),
    .Z(A_LUT4_B_D_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hff00)
  ) A_LUT4_D (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(A[8]),
    .Z(A_LUT4_D_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hff00)
  ) A_LUT4_D_1 (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(A[0]),
    .Z(A_LUT4_D_1_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hff00)
  ) A_LUT4_D_2 (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(A[12]),
    .Z(A_LUT4_D_2_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hff00)
  ) A_LUT4_D_3 (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(A[3]),
    .Z(A_LUT4_D_3_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hff00)
  ) A_LUT4_D_4 (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(A[7]),
    .Z(A_LUT4_D_4_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hff00)
  ) A_LUT4_D_5 (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(A[11]),
    .Z(A_LUT4_D_5_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hff00)
  ) A_LUT4_D_6 (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(A[4]),
    .Z(A_LUT4_D_6_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd_bin.v:19.5-46.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q  (
    .CE(rst_LUT4_B_1_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [4]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd_bin.v:19.5-46.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q_1  (
    .CE(rst_LUT4_B_1_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [3]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd_bin.v:19.5-46.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q_2  (
    .CE(rst_LUT4_B_1_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [2]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd_bin.v:19.5-46.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q_3  (
    .CE(rst_LUT4_B_1_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [1]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd_bin.v:19.5-46.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q_4  (
    .CE(rst_LUT4_B_1_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [0]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd_bin.v:39.32-39.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \control0.cont_TRELLIS_FF_Q_DI_CCU2C_S0  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\control0.cont [4]),
    .B1(1'h0),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\control0.cont_TRELLIS_FF_Q_DI_CCU2C_S1_COUT ),
    .COUT(\control0.cont_TRELLIS_FF_Q_DI_CCU2C_S0_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\control0.cont_TRELLIS_FF_Q_DI [4]),
    .S1(\control0.cont_TRELLIS_FF_Q_DI_CCU2C_S0_S1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd_bin.v:39.32-39.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \control0.cont_TRELLIS_FF_Q_DI_CCU2C_S1  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\control0.cont [2]),
    .B1(\control0.cont [3]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\control0.cont_TRELLIS_FF_Q_DI_CCU2C_S1_1_COUT ),
    .COUT(\control0.cont_TRELLIS_FF_Q_DI_CCU2C_S1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\control0.cont_TRELLIS_FF_Q_DI [2]),
    .S1(\control0.cont_TRELLIS_FF_Q_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd_bin.v:39.32-39.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \control0.cont_TRELLIS_FF_Q_DI_CCU2C_S1_1  (
    .A0(1'h1),
    .A1(1'h0),
    .B0(\control0.cont [0]),
    .B1(\control0.cont [1]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(1'h0),
    .COUT(\control0.cont_TRELLIS_FF_Q_DI_CCU2C_S1_1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\control0.cont_TRELLIS_FF_Q_DI_CCU2C_S1_1_S0 ),
    .S1(\control0.cont_TRELLIS_FF_Q_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:114.33-115.56" */
  LUT4 #(
    .INIT(16'h00ff)
  ) \control0.cont_TRELLIS_FF_Q_DI_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\control0.cont [0]),
    .Z(\control0.cont_TRELLIS_FF_Q_DI [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hffcf)
  ) \control0.state_LUT4_D  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(init_LUT4_A_Z_LUT4_D_B[4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'ha0d0)
  ) \control0.state_LUT4_D_1  (
    .A(\control0.state [2]),
    .B(\control0.state [1]),
    .C(init_LUT4_A_Z_LUT4_D_B[4]),
    .D(\control0.state [0]),
    .Z(\control0.state_LUT4_D_1_Z [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd_bin.v:19.5-46.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.state_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\control0.state_TRELLIS_FF_Q_DI ),
    .LSR(rst_LUT4_B_Z),
    .Q(\control0.state [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd_bin.v:19.5-46.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.state_TRELLIS_FF_Q_1  (
    .CLK(clk),
    .DI(\control0.state_TRELLIS_FF_Q_1_DI ),
    .LSR(rst_LUT4_B_Z),
    .Q(\control0.state [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hffc0)
  ) \control0.state_TRELLIS_FF_Q_1_DI_LUT4_Z  (
    .A(1'h0),
    .B(rst_LUT4_B_C_L6MUX21_SD_Z[0]),
    .C(rst_LUT4_B_C_L6MUX21_SD_Z[1]),
    .D(rst_LUT4_B_C_L6MUX21_SD_Z[2]),
    .Z(\control0.state_TRELLIS_FF_Q_1_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd_bin.v:19.5-46.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.state_TRELLIS_FF_Q_2  (
    .CLK(clk),
    .DI(\control0.state_TRELLIS_FF_Q_2_DI ),
    .LSR(rst_LUT4_B_Z),
    .Q(\control0.state [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h33f3)
  ) \control0.state_TRELLIS_FF_Q_DI_LUT4_Z  (
    .A(1'h0),
    .B(init_LUT4_A_Z_LUT4_D_B[4]),
    .C(rst_LUT4_B_C_L6MUX21_SD_Z[0]),
    .D(rst_LUT4_B_C_L6MUX21_SD_Z[1]),
    .Z(\control0.state_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hf000)
  ) \control0.w_sh_r_LUT4_D  (
    .A(1'h0),
    .B(1'h0),
    .C(init_LUT4_A_Z_LUT4_D_B[4]),
    .D(\control0.w_sh_r ),
    .Z(\control0.w_sh_r_LUT4_D_Z )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h3000)
  ) \control0.w_sh_r_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.w_sh_r )
  );
  /* module_not_derived = 32'd1 */
  /* src = "contador_desc.v:7.5-14.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \count0.val_TRELLIS_FF_Q  (
    .CE(\control0.w_sh_r ),
    .CLK(clk),
    .DI(\count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1 [0]),
    .LSR(\control0.state_LUT4_D_1_Z [4]),
    .Q(\count0.val [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "contador_desc.v:7.5-14.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:16.100-16.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \count0.val_TRELLIS_FF_Q_1  (
    .CLK(clk),
    .DI(\count0.val_TRELLIS_FF_Q_1_DI ),
    .LSR(1'h0),
    .Q(\count0.val [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hfece)
  ) \count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z  (
    .A(\count0.val [4]),
    .B(\control0.state_LUT4_D_1_Z [4]),
    .C(\control0.w_sh_r ),
    .D(\count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D [3]),
    .Z(\count0.val_TRELLIS_FF_Q_1_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "contador_desc.v:11.27-11.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0  (
    .A0(\count0.val [4]),
    .A1(1'h0),
    .B0(1'h0),
    .B1(1'h0),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(\count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_CIN ),
    .COUT(\count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D [3]),
    .S1(\count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_S1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "contador_desc.v:11.27-11.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT  (
    .A0(\count0.val [2]),
    .A1(\count0.val [3]),
    .B0(1'h0),
    .B1(1'h0),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(\count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1_CCU2C_S1_COUT ),
    .COUT(\count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_CIN ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1 [2]),
    .S1(\count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1 [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "contador_desc.v:11.27-11.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1_CCU2C_S1  (
    .A0(\count0.val [0]),
    .A1(\count0.val [1]),
    .B0(1'h1),
    .B1(1'h0),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(1'h1),
    .COUT(\count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1_CCU2C_S1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1_CCU2C_S1_S0 ),
    .S1(\count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1 [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:114.33-115.56" */
  LUT4 #(
    .INIT(16'h00ff)
  ) \count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\count0.val [0]),
    .Z(\count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1 [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "contador_desc.v:7.5-14.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \count0.val_TRELLIS_FF_Q_2  (
    .CE(\control0.w_sh_r ),
    .CLK(clk),
    .DI(\count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1 [3]),
    .LSR(\control0.state_LUT4_D_1_Z [4]),
    .Q(\count0.val [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "contador_desc.v:7.5-14.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \count0.val_TRELLIS_FF_Q_3  (
    .CE(\control0.w_sh_r ),
    .CLK(clk),
    .DI(\count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1 [2]),
    .LSR(\control0.state_LUT4_D_1_Z [4]),
    .Q(\count0.val [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "contador_desc.v:7.5-14.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \count0.val_TRELLIS_FF_Q_4  (
    .CE(\control0.w_sh_r ),
    .CLK(clk),
    .DI(\count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1 [1]),
    .LSR(\control0.state_LUT4_D_1_Z [4]),
    .Q(\count0.val [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h00f0)
  ) done_LUT4_D (
    .A(1'h0),
    .B(1'h0),
    .C(rst_LUT4_B_1_Z[0]),
    .D(done),
    .Z(done_LUT4_D_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hf000)
  ) done_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(\control0.state [2]),
    .D(rst_LUT4_B_C[6]),
    .Z(done)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0002)
  ) init_LUT4_A (
    .A(init),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(init_LUT4_A_Z[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hfff3)
  ) init_LUT4_A_Z_LUT4_D (
    .A(1'h0),
    .B(init_LUT4_A_Z_LUT4_D_B[4]),
    .C(\control0.w_sh_r ),
    .D(init_LUT4_A_Z[2]),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.s_out_TRELLIS_FF_Q  (
    .CE(\rcr0.s_out_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A_LUT4_A_Z[23]),
    .LSR(1'h0),
    .Q(\rcr0.s_out [23])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.s_out_TRELLIS_FF_Q_1  (
    .CE(\rcr0.s_out_TRELLIS_FF_Q_7_CE ),
    .CLK(clk),
    .DI(A_LUT4_A_Z[17]),
    .LSR(1'h0),
    .Q(\rcr0.s_out [17])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.s_out_TRELLIS_FF_Q_10  (
    .CE(\rcr0.s_out_TRELLIS_FF_Q_5_CE ),
    .CLK(clk),
    .DI(A_LUT4_A_Z[28]),
    .LSR(1'h0),
    .Q(\rcr0.s_out [28])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.s_out_TRELLIS_FF_Q_11  (
    .CE(\rcr0.s_out_TRELLIS_FF_Q_9_CE ),
    .CLK(clk),
    .DI(A_LUT4_A_Z[26]),
    .LSR(1'h0),
    .Q(\rcr0.s_out [26])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.s_out_TRELLIS_FF_Q_12  (
    .CE(\rcr0.s_out_TRELLIS_FF_Q_9_CE ),
    .CLK(clk),
    .DI(A_LUT4_A_Z[27]),
    .LSR(1'h0),
    .Q(\rcr0.s_out [27])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.s_out_TRELLIS_FF_Q_13  (
    .CE(\rcr0.s_out_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A_LUT4_A_Z[21]),
    .LSR(1'h0),
    .Q(\rcr0.s_out [21])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rcr0.s_out_TRELLIS_FF_Q_14  (
    .CE(\control0.w_sh_r_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rcr0.s_out [1]),
    .LSR(\control0.state_LUT4_D_1_Z [4]),
    .Q(\rcr0.s_out [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rcr0.s_out_TRELLIS_FF_Q_15  (
    .CE(\control0.w_sh_r_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rcr0.s_out [15]),
    .LSR(\control0.state_LUT4_D_1_Z [4]),
    .Q(\rcr0.s_out [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.s_out_TRELLIS_FF_Q_16  (
    .CE(\rcr0.s_out_TRELLIS_FF_Q_7_CE ),
    .CLK(clk),
    .DI(A_LUT4_A_Z[18]),
    .LSR(1'h0),
    .Q(\rcr0.s_out [18])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.s_out_TRELLIS_FF_Q_17  (
    .CE(\rcr0.s_out_TRELLIS_FF_Q_7_CE ),
    .CLK(clk),
    .DI(A_LUT4_A_Z[19]),
    .LSR(1'h0),
    .Q(\rcr0.s_out [19])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rcr0.s_out_TRELLIS_FF_Q_18  (
    .CE(\control0.w_sh_r_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rcr0.s_out [7]),
    .LSR(\control0.state_LUT4_D_1_Z [4]),
    .Q(\rcr0.s_out [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rcr0.s_out_TRELLIS_FF_Q_19  (
    .CE(\control0.w_sh_r_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rcr0.s_out [6]),
    .LSR(\control0.state_LUT4_D_1_Z [4]),
    .Q(\rcr0.s_out [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rcr0.s_out_TRELLIS_FF_Q_2  (
    .CE(\control0.w_sh_r_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rcr0.s_out [3]),
    .LSR(\control0.state_LUT4_D_1_Z [4]),
    .Q(\rcr0.s_out [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rcr0.s_out_TRELLIS_FF_Q_20  (
    .CE(\control0.w_sh_r_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rcr0.s_out [5]),
    .LSR(\control0.state_LUT4_D_1_Z [4]),
    .Q(\rcr0.s_out [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rcr0.s_out_TRELLIS_FF_Q_21  (
    .CE(\control0.w_sh_r_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rcr0.s_out [4]),
    .LSR(\control0.state_LUT4_D_1_Z [4]),
    .Q(\rcr0.s_out [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rcr0.s_out_TRELLIS_FF_Q_22  (
    .CE(\control0.w_sh_r_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rcr0.s_out [13]),
    .LSR(\control0.state_LUT4_D_1_Z [4]),
    .Q(\rcr0.s_out [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rcr0.s_out_TRELLIS_FF_Q_23  (
    .CE(\control0.w_sh_r_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rcr0.s_out [2]),
    .LSR(\control0.state_LUT4_D_1_Z [4]),
    .Q(\rcr0.s_out [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.s_out_TRELLIS_FF_Q_24  (
    .CE(\rcr0.s_out_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A_LUT4_A_Z[22]),
    .LSR(1'h0),
    .Q(\rcr0.s_out [22])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rcr0.s_out_TRELLIS_FF_Q_25  (
    .CE(\control0.w_sh_r_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rcr0.s_out [8]),
    .LSR(\control0.state_LUT4_D_1_Z [4]),
    .Q(\rcr0.s_out [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.s_out_TRELLIS_FF_Q_26  (
    .CE(\rcr0.s_out_TRELLIS_FF_Q_5_CE ),
    .CLK(clk),
    .DI(A_LUT4_A_Z[30]),
    .LSR(1'h0),
    .Q(\rcr0.s_out [30])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.s_out_TRELLIS_FF_Q_27  (
    .CE(\rcr0.s_out_TRELLIS_FF_Q_5_CE ),
    .CLK(clk),
    .DI(A_LUT4_A_Z[31]),
    .LSR(1'h0),
    .Q(\rcr0.s_out [31])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.s_out_TRELLIS_FF_Q_28  (
    .CE(\rcr0.s_out_TRELLIS_FF_Q_9_CE ),
    .CLK(clk),
    .DI(A_LUT4_A_Z[25]),
    .LSR(1'h0),
    .Q(\rcr0.s_out [25])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rcr0.s_out_TRELLIS_FF_Q_29  (
    .CE(\control0.w_sh_r_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rcr0.s_out [11]),
    .LSR(\control0.state_LUT4_D_1_Z [4]),
    .Q(\rcr0.s_out [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rcr0.s_out_TRELLIS_FF_Q_3  (
    .CE(\control0.w_sh_r_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rcr0.s_out [12]),
    .LSR(\control0.state_LUT4_D_1_Z [4]),
    .Q(\rcr0.s_out [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rcr0.s_out_TRELLIS_FF_Q_30  (
    .CE(\control0.w_sh_r_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rcr0.s_out [10]),
    .LSR(\control0.state_LUT4_D_1_Z [4]),
    .Q(\rcr0.s_out [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rcr0.s_out_TRELLIS_FF_Q_31  (
    .CE(\control0.w_sh_r_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rcr0.s_out [9]),
    .LSR(\control0.state_LUT4_D_1_Z [4]),
    .Q(\rcr0.s_out [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.s_out_TRELLIS_FF_Q_4  (
    .CE(\rcr0.s_out_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A_LUT4_A_Z[20]),
    .LSR(1'h0),
    .Q(\rcr0.s_out [20])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.s_out_TRELLIS_FF_Q_5  (
    .CE(\rcr0.s_out_TRELLIS_FF_Q_5_CE ),
    .CLK(clk),
    .DI(A_LUT4_A_Z[29]),
    .LSR(1'h0),
    .Q(\rcr0.s_out [29])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h00fc)
  ) \rcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z  (
    .A(1'h0),
    .B(\rcr0.s_out [31]),
    .C(init_LUT4_A_Z_LUT4_D_B[4]),
    .D(\rcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [2]),
    .Z(\rcr0.s_out_TRELLIS_FF_Q_5_CE )
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rcr0.s_out_TRELLIS_FF_Q_6  (
    .CE(\control0.w_sh_r_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rcr0.s_out [14]),
    .LSR(\control0.state_LUT4_D_1_Z [4]),
    .Q(\rcr0.s_out [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.s_out_TRELLIS_FF_Q_7  (
    .CE(\rcr0.s_out_TRELLIS_FF_Q_7_CE ),
    .CLK(clk),
    .DI(A_LUT4_A_Z[16]),
    .LSR(1'h0),
    .Q(\rcr0.s_out [16])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h00fc)
  ) \rcr0.s_out_TRELLIS_FF_Q_7_CE_LUT4_Z  (
    .A(1'h0),
    .B(\rcr0.s_out [19]),
    .C(init_LUT4_A_Z_LUT4_D_B[4]),
    .D(\rcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [2]),
    .Z(\rcr0.s_out_TRELLIS_FF_Q_7_CE )
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rcr0.s_out_TRELLIS_FF_Q_8  (
    .CE(\control0.w_sh_r_LUT4_D_Z ),
    .CLK(clk),
    .DI(\rcr0.s_out [16]),
    .LSR(\control0.state_LUT4_D_1_Z [4]),
    .Q(\rcr0.s_out [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr_32_combined.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.s_out_TRELLIS_FF_Q_9  (
    .CE(\rcr0.s_out_TRELLIS_FF_Q_9_CE ),
    .CLK(clk),
    .DI(A_LUT4_A_Z[24]),
    .LSR(1'h0),
    .Q(\rcr0.s_out [24])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h00fc)
  ) \rcr0.s_out_TRELLIS_FF_Q_9_CE_LUT4_Z  (
    .A(1'h0),
    .B(\rcr0.s_out [27]),
    .C(init_LUT4_A_Z_LUT4_D_B[4]),
    .D(\rcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [2]),
    .Z(\rcr0.s_out_TRELLIS_FF_Q_9_CE )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h00fc)
  ) \rcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z  (
    .A(1'h0),
    .B(\rcr0.s_out [23]),
    .C(init_LUT4_A_Z_LUT4_D_B[4]),
    .D(\rcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [2]),
    .Z(\rcr0.s_out_TRELLIS_FF_Q_CE )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h1020)
  ) \rcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D_LUT4_Z  (
    .A(\control0.state [2]),
    .B(\control0.state [1]),
    .C(init_LUT4_A_Z_LUT4_D_B[4]),
    .D(\control0.state [0]),
    .Z(\rcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hcfcc)
  ) rst_LUT4_B (
    .A(1'h0),
    .B(rst),
    .C(rst_LUT4_B_C[6]),
    .D(\control0.state_LUT4_D_1_Z [4]),
    .Z(rst_LUT4_B_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h3330)
  ) rst_LUT4_B_1 (
    .A(1'h0),
    .B(rst),
    .C(init_LUT4_A_Z[2]),
    .D(rst_LUT4_B_C_L6MUX21_SD_Z[2]),
    .Z(rst_LUT4_B_1_Z[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:184.21-184.63" */
  L6MUX21 rst_LUT4_B_C_L6MUX21_SD (
    .D0(rst_LUT4_B_C_L6MUX21_SD_D0),
    .D1(rst_LUT4_B_C_L6MUX21_SD_D1),
    .SD(rst_LUT4_B_C[6]),
    .Z(rst_LUT4_B_C_L6MUX21_SD_Z[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:182.21-182.64" */
  L6MUX21 rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z (
    .D0(rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D0),
    .D1(rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D1),
    .SD(\control0.cont [0]),
    .Z(rst_LUT4_B_C_L6MUX21_SD_D0)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:178.19-178.65" */
  PFUMX rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D0_PFUMX_Z (
    .ALUT(rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D0_PFUMX_Z_ALUT),
    .BLUT(rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D0_PFUMX_Z_BLUT),
    .C0(\control0.cont [1]),
    .Z(rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D0)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:160.39-161.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D0_PFUMX_Z_ALUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D0_PFUMX_Z_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:158.39-159.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D0_PFUMX_Z_BLUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D0_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:179.19-179.65" */
  PFUMX rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D1_PFUMX_Z (
    .ALUT(rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D1_PFUMX_Z_ALUT),
    .BLUT(rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D1_PFUMX_Z_BLUT),
    .C0(\control0.cont [1]),
    .Z(rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D1)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:165.39-166.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D1_PFUMX_Z_ALUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D1_PFUMX_Z_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:163.39-164.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D1_PFUMX_Z_BLUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(rst_LUT4_B_C_L6MUX21_SD_D0_L6MUX21_Z_D1_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:183.21-183.64" */
  L6MUX21 rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z (
    .D0(rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D0),
    .D1(rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D1),
    .SD(\control0.cont [0]),
    .Z(rst_LUT4_B_C_L6MUX21_SD_D1)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:180.19-180.65" */
  PFUMX rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D0_PFUMX_Z (
    .ALUT(rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D0_PFUMX_Z_ALUT),
    .BLUT(rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D0_PFUMX_Z_BLUT),
    .C0(\control0.cont [1]),
    .Z(rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D0)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:170.39-171.56" */
  LUT4 #(
    .INIT(16'hff00)
  ) rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D0_PFUMX_Z_ALUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\control0.state [2]),
    .Z(rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D0_PFUMX_Z_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:168.39-169.56" */
  LUT4 #(
    .INIT(16'h70f0)
  ) rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D0_PFUMX_Z_BLUT_LUT4_Z (
    .A(\control0.cont [4]),
    .B(\control0.cont [3]),
    .C(\control0.state [2]),
    .D(\control0.cont [2]),
    .Z(rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D0_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:181.19-181.65" */
  PFUMX rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D1_PFUMX_Z (
    .ALUT(rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D1_PFUMX_Z_ALUT),
    .BLUT(rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D1_PFUMX_Z_BLUT),
    .C0(\control0.cont [1]),
    .Z(rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D1)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:175.41-176.56" */
  LUT4 #(
    .INIT(16'hff00)
  ) rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D1_PFUMX_Z_ALUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\control0.state [2]),
    .Z(rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D1_PFUMX_Z_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:173.41-174.56" */
  LUT4 #(
    .INIT(16'hff00)
  ) rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D1_PFUMX_Z_BLUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\control0.state [2]),
    .Z(rst_LUT4_B_C_L6MUX21_SD_D1_L6MUX21_Z_D1_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h0300)
  ) rst_LUT4_B_C_L6MUX21_SD_Z_LUT4_Z (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(rst_LUT4_B_C_L6MUX21_SD_Z[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX rst_LUT4_B_C_L6MUX21_SD_Z_PFUMX_Z (
    .ALUT(rst_LUT4_B_C_L6MUX21_SD_Z_PFUMX_Z_ALUT),
    .BLUT(rst_LUT4_B_C_L6MUX21_SD_Z_PFUMX_Z_BLUT),
    .C0(\count0.val [0]),
    .Z(rst_LUT4_B_C_L6MUX21_SD_Z[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) rst_LUT4_B_C_L6MUX21_SD_Z_PFUMX_Z_ALUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(rst_LUT4_B_C_L6MUX21_SD_Z_PFUMX_Z_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) rst_LUT4_B_C_L6MUX21_SD_Z_PFUMX_Z_BLUT_LUT4_Z (
    .A(\count0.val [4]),
    .B(\count0.val [3]),
    .C(\count0.val [2]),
    .D(\count0.val [1]),
    .Z(rst_LUT4_B_C_L6MUX21_SD_Z_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h000f)
  ) rst_LUT4_B_C_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(rst_LUT4_B_C[6])
  );
  assign rst_LUT4_B_C[5:0] = { \control0.cont [0], \control0.cont [1], \control0.cont [2], \control0.state [2], \control0.cont [3], \control0.cont [4] };
  assign { A_LUT4_B_6_C[2], A_LUT4_B_6_C[0] } = { \control0.state_LUT4_D_1_Z [4], A[13] };
  assign \count0.val_TRELLIS_FF_Q_1_DI_LUT4_Z_D [2:0] = { \control0.w_sh_r , \control0.state_LUT4_D_1_Z [4], \count0.val [4] };
  assign A_LUT4_B_1_D[1:0] = { \control0.state_LUT4_D_1_Z [4], A[6] };
  assign A_LUT4_B_D[1:0] = { \control0.state_LUT4_D_1_Z [4], A[14] };
  assign \rcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [1:0] = { init_LUT4_A_Z_LUT4_D_B[4], \rcr0.s_out [23] };
  assign init_LUT4_A_Z[1:0] = { \control0.w_sh_r , init_LUT4_A_Z_LUT4_D_B[4] };
  assign A_LUT4_B_3_D[1:0] = { \control0.state_LUT4_D_1_Z [4], A[10] };
  assign \control0.state_LUT4_D_1_Z [3:0] = { init_LUT4_A_Z_LUT4_D_B[4], \rcr0.s_out [16], \rcr0.s_out [17], A[0] };
  assign { A_LUT4_A_Z_PFUMX_Z_BLUT_LUT4_Z_D[4], A_LUT4_A_Z_PFUMX_Z_BLUT_LUT4_Z_D[2:0] } = { \control0.state_LUT4_D_1_Z [4], init_LUT4_A_Z_LUT4_D_B[4], \rcr0.s_out [20], A[3] };
  assign { A_LUT4_A_Z_PFUMX_Z_2_BLUT_LUT4_Z_D[4], A_LUT4_A_Z_PFUMX_Z_2_BLUT_LUT4_Z_D[2:0] } = { \control0.state_LUT4_D_1_Z [4], init_LUT4_A_Z_LUT4_D_B[4], \rcr0.s_out [28], A[11] };
  assign { A_LUT4_B_7_C[2], A_LUT4_B_7_C[0] } = { \control0.state_LUT4_D_1_Z [4], A[5] };
  assign \rcr0.clk  = clk;
  assign \acc0.in_bcd  = \rcr0.s_out [31:16];
  assign A_LUT4_B_4_D[1:0] = { \control0.state_LUT4_D_1_Z [4], A[2] };
  assign rst_LUT4_B_1_Z[1] = done;
  assign init_LUT4_A_Z_LUT4_D_B[3:0] = { \rcr0.s_out [16], \rcr0.s_out [17], \rcr0.s_out [18], \rcr0.s_out [19] };
  assign { A_LUT4_B_2_C[2], A_LUT4_B_2_C[0] } = { \control0.state_LUT4_D_1_Z [4], A[1] };
  assign { A_LUT4_B_5_C[2], A_LUT4_B_5_C[0] } = { \control0.state_LUT4_D_1_Z [4], A[9] };
  assign \count0.dec  = \control0.w_sh_r ;
  assign \rcr0.in_A  = { A, 16'h0000 };
  assign \control0.done  = done;
  assign \count0.clk  = clk;
  assign \control0.init  = init;
  assign \control0.rst  = rst;
  assign \control0.clk  = clk;
  assign \rcr0.shift  = \control0.w_sh_r ;
  assign { A_LUT4_A_Z_PFUMX_Z_1_BLUT_LUT4_Z_D[4], A_LUT4_A_Z_PFUMX_Z_1_BLUT_LUT4_Z_D[2:0] } = { \control0.state_LUT4_D_1_Z [4], init_LUT4_A_Z_LUT4_D_B[4], \rcr0.s_out [24], A[7] };
  assign { A_LUT4_A_C[3], A_LUT4_A_C[1:0] } = { \control0.state_LUT4_D_1_Z [4], init_LUT4_A_Z_LUT4_D_B[4], A[15] };
  assign \comp_z0.val  = \count0.val ;
  assign w_val = \count0.val ;
  assign w_BCD_part = \rcr0.s_out [31:16];
  assign w_combined = \rcr0.s_out ;
  assign w_sh_r = \control0.w_sh_r ;
  assign BIN_out = \rcr0.s_out [15:0];
endmodule
