/* Generated by Yosys 0.65+57 (git sha1 9d0cdb855, clang++ 18.1.8 -fPIC -O3) */

/* hdlname = "pariedad_16" */
/* top =  1  */
/* src = "pariedad_16.v:1.1-16.10" */
module pariedad_16(clk, rst, init, N, es_par, es_impar, done);
  /* src = "pariedad_16.v:2.11-2.14" */
  input clk;
  wire clk;
  /* src = "pariedad_16.v:2.16-2.19" */
  input rst;
  wire rst;
  /* src = "pariedad_16.v:2.21-2.25" */
  input init;
  wire init;
  /* src = "pariedad_16.v:3.18-3.19" */
  input [15:0] N;
  wire [15:0] N;
  /* src = "pariedad_16.v:4.12-4.18" */
  output es_par;
  wire es_par;
  /* src = "pariedad_16.v:4.20-4.28" */
  output es_impar;
  wire es_impar;
  /* src = "pariedad_16.v:4.30-4.34" */
  output done;
  wire done;
  /* src = "pariedad_16.v:6.17-6.18" */
  wire [15:0] A;
  /* src = "pariedad_16.v:6.20-6.21" */
  wire [15:0] B;
  /* src = "pariedad_16.v:6.23-6.26" */
  wire [15:0] LSB;
  /* hdlname = "comp0 LSB" */
  /* src = "comp.v:2.18-2.21" */
  wire [15:0] \comp0.LSB ;
  /* hdlname = "comp0 tmp" */
  /* src = "comp.v:4.9-4.12" */
  wire \comp0.tmp ;
  /* hdlname = "comp0 z" */
  /* src = "comp.v:3.12-3.13" */
  wire \comp0.z ;
  /* hdlname = "control0 clk" */
  /* src = "control_pariedad.v:2.11-2.14" */
  wire \control0.clk ;
  /* hdlname = "control0 cont" */
  /* src = "control_pariedad.v:13.15-13.19" */
  wire [4:0] \control0.cont ;
  /* abc9_carry = 32'd1 */
  /* src = "control_pariedad.v:48.32-48.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  /* unused_bits = "0" */
  wire \control0.cont_CCU2C_B0_COUT ;
  /* unused_bits = "0" */
  wire \control0.cont_CCU2C_B0_S1 ;
  /* abc9_carry = 32'd1 */
  /* src = "control_pariedad.v:48.32-48.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \control0.cont_CCU2C_B1_1_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "control_pariedad.v:48.32-48.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \control0.cont_CCU2C_B1_COUT ;
  /* unused_bits = "0" */
  wire \control0.cont_CCU2C_B1_S0 ;
  /* force_downto = 32'd1 */
  /* src = "control_pariedad.v:48.32-48.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:34.26-34.27" */
  wire [4:0] \control0.cont_TRELLIS_FF_Q_DI ;
  /* hdlname = "control0 done" */
  /* src = "control_pariedad.v:3.16-3.20" */
  wire \control0.done ;
  /* hdlname = "control0 init" */
  /* src = "control_pariedad.v:2.21-2.25" */
  wire \control0.init ;
  /* hdlname = "control0 rst" */
  /* src = "control_pariedad.v:2.16-2.19" */
  wire \control0.rst ;
  /* hdlname = "control0 state" */
  /* src = "control_pariedad.v:12.15-12.20" */
  wire [2:0] \control0.state ;
  wire \control0.state_TRELLIS_FF_Q_1_DI ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire \control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z_ALUT ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire \control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z_BLUT ;
  wire \control0.state_TRELLIS_FF_Q_DI ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire \control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire \control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT ;
  /* hdlname = "control0 w_sh_l" */
  /* src = "control_pariedad.v:3.22-3.28" */
  wire \control0.w_sh_l ;
  /* hdlname = "control0 w_sub" */
  /* src = "control_pariedad.v:3.45-3.50" */
  wire \control0.w_sub ;
  /* hdlname = "control0 z" */
  /* src = "control_pariedad.v:2.27-2.28" */
  wire \control0.z ;
  wire done_LUT4_D_Z;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [1:0] done_PFUMX_C0_Z;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [3:0] es_par_LUT4_Z_D;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [4:0] init_LUT4_A_Z;
  /* hdlname = "lcr0 A" */
  /* src = "lcr.v:3.18-3.19" */
  wire [15:0] \lcr0.A ;
  /* hdlname = "lcr0 B" */
  /* src = "lcr.v:4.23-4.24" */
  wire [15:0] \lcr0.B ;
  /* abc9_carry = 32'd1 */
  /* src = "sub.v:12.29-12.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  /* unused_bits = "0" */
  wire \lcr0.B_CCU2C_B0_COUT ;
  /* unused_bits = "0" */
  wire \lcr0.B_CCU2C_B0_S1 ;
  /* abc9_carry = 32'd1 */
  /* src = "sub.v:12.29-12.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \lcr0.B_CCU2C_B1_1_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "sub.v:12.29-12.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \lcr0.B_CCU2C_B1_2_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "sub.v:12.29-12.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \lcr0.B_CCU2C_B1_3_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "sub.v:12.29-12.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \lcr0.B_CCU2C_B1_4_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "sub.v:12.29-12.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \lcr0.B_CCU2C_B1_5_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "sub.v:12.29-12.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \lcr0.B_CCU2C_B1_6_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "sub.v:12.29-12.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \lcr0.B_CCU2C_B1_COUT ;
  /* hdlname = "lcr0 clk" */
  /* src = "lcr.v:2.11-2.14" */
  wire \lcr0.clk ;
  /* hdlname = "lcr0 shift" */
  /* src = "lcr.v:2.16-2.21" */
  wire \lcr0.shift ;
  /* hdlname = "rcr0 A" */
  /* src = "rcr.v:4.23-4.24" */
  wire [15:0] \rcr0.A ;
  wire [14:0] \rcr0.A_TRELLIS_FF_Q_9_DI ;
  wire \rcr0.A_TRELLIS_FF_Q_LSR ;
  /* hdlname = "rcr0 N" */
  /* src = "rcr.v:3.18-3.19" */
  wire [15:0] \rcr0.N ;
  /* hdlname = "rcr0 clk" */
  /* src = "rcr.v:2.11-2.14" */
  wire \rcr0.clk ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire rst_LUT4_A_1_Z;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire rst_LUT4_A_Z;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [4:0] rst_LUT4_B_D;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] rst_LUT4_B_D_LUT4_C_1_Z;
  wire rst_LUT4_B_D_LUT4_C_Z;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire rst_LUT4_B_Z;
  wire rst_LUT4_B_Z_PFUMX_ALUT_Z;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire rst_LUT4_C_Z;
  /* hdlname = "sub0 B" */
  /* src = "sub.v:3.21-3.22" */
  wire [15:0] \sub0.B ;
  /* hdlname = "sub0 LSB" */
  /* src = "sub.v:4.23-4.26" */
  wire [15:0] \sub0.LSB ;
  /* force_downto = 32'd1 */
  /* src = "sub.v:12.29-12.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:34.26-34.27" */
  wire [14:0] \sub0.LSB_TRELLIS_FF_Q_DI ;
  /* hdlname = "sub0 N" */
  /* src = "sub.v:3.18-3.19" */
  wire [15:0] \sub0.N ;
  /* hdlname = "sub0 clk" */
  /* src = "sub.v:2.11-2.14" */
  wire \sub0.clk ;
  /* hdlname = "sub0 subtr" */
  /* src = "sub.v:2.16-2.21" */
  wire \sub0.subtr ;
  /* src = "pariedad_16.v:5.10-5.16" */
  wire w_sh_l;
  /* src = "pariedad_16.v:5.33-5.38" */
  wire w_sub;
  /* src = "pariedad_16.v:5.40-5.41" */
  wire z;
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) N_LUT4_B (
    .A(1'h0),
    .B(N[1]),
    .C(\rcr0.A [2]),
    .D(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Z(\rcr0.A_TRELLIS_FF_Q_9_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) N_LUT4_B_1 (
    .A(1'h0),
    .B(N[14]),
    .C(\rcr0.A [15]),
    .D(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Z(\rcr0.A_TRELLIS_FF_Q_9_DI [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) N_LUT4_B_10 (
    .A(1'h0),
    .B(N[10]),
    .C(\rcr0.A [11]),
    .D(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Z(\rcr0.A_TRELLIS_FF_Q_9_DI [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) N_LUT4_B_11 (
    .A(1'h0),
    .B(N[11]),
    .C(\rcr0.A [12]),
    .D(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Z(\rcr0.A_TRELLIS_FF_Q_9_DI [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) N_LUT4_B_12 (
    .A(1'h0),
    .B(N[12]),
    .C(\rcr0.A [13]),
    .D(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Z(\rcr0.A_TRELLIS_FF_Q_9_DI [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) N_LUT4_B_13 (
    .A(1'h0),
    .B(N[13]),
    .C(\rcr0.A [14]),
    .D(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Z(\rcr0.A_TRELLIS_FF_Q_9_DI [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) N_LUT4_B_14 (
    .A(1'h0),
    .B(N[0]),
    .C(\rcr0.A [1]),
    .D(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Z(\rcr0.A_TRELLIS_FF_Q_9_DI [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) N_LUT4_B_2 (
    .A(1'h0),
    .B(N[2]),
    .C(\rcr0.A [3]),
    .D(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Z(\rcr0.A_TRELLIS_FF_Q_9_DI [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) N_LUT4_B_3 (
    .A(1'h0),
    .B(N[3]),
    .C(\rcr0.A [4]),
    .D(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Z(\rcr0.A_TRELLIS_FF_Q_9_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) N_LUT4_B_4 (
    .A(1'h0),
    .B(N[4]),
    .C(\rcr0.A [5]),
    .D(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Z(\rcr0.A_TRELLIS_FF_Q_9_DI [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) N_LUT4_B_5 (
    .A(1'h0),
    .B(N[5]),
    .C(\rcr0.A [6]),
    .D(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Z(\rcr0.A_TRELLIS_FF_Q_9_DI [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) N_LUT4_B_6 (
    .A(1'h0),
    .B(N[6]),
    .C(\rcr0.A [7]),
    .D(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Z(\rcr0.A_TRELLIS_FF_Q_9_DI [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) N_LUT4_B_7 (
    .A(1'h0),
    .B(N[7]),
    .C(\rcr0.A [8]),
    .D(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Z(\rcr0.A_TRELLIS_FF_Q_9_DI [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) N_LUT4_B_8 (
    .A(1'h0),
    .B(N[8]),
    .C(\rcr0.A [9]),
    .D(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Z(\rcr0.A_TRELLIS_FF_Q_9_DI [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) N_LUT4_B_9 (
    .A(1'h0),
    .B(N[9]),
    .C(\rcr0.A [10]),
    .D(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Z(\rcr0.A_TRELLIS_FF_Q_9_DI [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_pariedad.v:48.32-48.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \control0.cont_CCU2C_B0  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\control0.cont [4]),
    .B1(1'h0),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\control0.cont_CCU2C_B1_1_COUT ),
    .COUT(\control0.cont_CCU2C_B0_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\control0.cont_TRELLIS_FF_Q_DI [4]),
    .S1(\control0.cont_CCU2C_B0_S1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_pariedad.v:48.32-48.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \control0.cont_CCU2C_B1  (
    .A0(1'h1),
    .A1(1'h0),
    .B0(\control0.cont [0]),
    .B1(\control0.cont [1]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(1'h0),
    .COUT(\control0.cont_CCU2C_B1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\control0.cont_CCU2C_B1_S0 ),
    .S1(\control0.cont_TRELLIS_FF_Q_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_pariedad.v:48.32-48.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \control0.cont_CCU2C_B1_1  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\control0.cont [2]),
    .B1(\control0.cont [3]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\control0.cont_CCU2C_B1_COUT ),
    .COUT(\control0.cont_CCU2C_B1_1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\control0.cont_TRELLIS_FF_Q_DI [2]),
    .S1(\control0.cont_TRELLIS_FF_Q_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:114.33-115.56" */
  LUT4 #(
    .INIT(16'h00ff)
  ) \control0.cont_LUT4_D  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\control0.cont [0]),
    .Z(\control0.cont_TRELLIS_FF_Q_DI [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_pariedad.v:21.5-55.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q  (
    .CE(done_PFUMX_C0_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [1]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_pariedad.v:21.5-55.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q_1  (
    .CE(done_PFUMX_C0_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [4]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_pariedad.v:21.5-55.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q_2  (
    .CE(done_PFUMX_C0_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [3]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_pariedad.v:21.5-55.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q_3  (
    .CE(done_PFUMX_C0_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [2]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_pariedad.v:21.5-55.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q_4  (
    .CE(done_PFUMX_C0_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [0]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_pariedad.v:21.5-55.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.state_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\control0.state_TRELLIS_FF_Q_DI ),
    .LSR(rst_LUT4_B_Z_PFUMX_ALUT_Z),
    .Q(\control0.state [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_pariedad.v:21.5-55.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.state_TRELLIS_FF_Q_1  (
    .CLK(clk),
    .DI(\control0.state_TRELLIS_FF_Q_1_DI ),
    .LSR(rst_LUT4_B_Z_PFUMX_ALUT_Z),
    .Q(\control0.state [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX \control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z  (
    .ALUT(\control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z_ALUT ),
    .BLUT(\control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z_BLUT ),
    .C0(init_LUT4_A_Z[3]),
    .Z(\control0.state_TRELLIS_FF_Q_1_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h340c)
  ) \control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z_ALUT_LUT4_Z  (
    .A(\control0.cont [3]),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h3c0c)
  ) \control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_pariedad.v:21.5-55.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.state_TRELLIS_FF_Q_2  (
    .CLK(clk),
    .DI(init_LUT4_A_Z[2]),
    .LSR(rst_LUT4_B_Z_PFUMX_ALUT_Z),
    .Q(\control0.state [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX \control0.state_TRELLIS_FF_Q_DI_PFUMX_Z  (
    .ALUT(\control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT ),
    .BLUT(\control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT ),
    .C0(init_LUT4_A_Z[3]),
    .Z(\control0.state_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h070c)
  ) \control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT_LUT4_Z  (
    .A(\control0.cont [3]),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h0f0c)
  ) \control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h0300)
  ) \control0.w_sh_l_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.w_sh_l )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h3000)
  ) \control0.w_sub_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.w_sub )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h00f0)
  ) done_LUT4_D (
    .A(1'h0),
    .B(1'h0),
    .C(done_PFUMX_C0_Z[0]),
    .D(done),
    .Z(done_LUT4_D_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h0c00)
  ) done_LUT4_Z (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(done)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX done_PFUMX_C0 (
    .ALUT(rst_LUT4_A_Z),
    .BLUT(rst_LUT4_C_Z),
    .C0(done),
    .Z(done_PFUMX_C0_Z[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h8000)
  ) es_impar_LUT4_Z (
    .A(es_par_LUT4_Z_D[0]),
    .B(es_par_LUT4_Z_D[1]),
    .C(es_par_LUT4_Z_D[2]),
    .D(es_par_LUT4_Z_D[3]),
    .Z(es_impar)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h7fff)
  ) es_par_LUT4_Z (
    .A(es_par_LUT4_Z_D[0]),
    .B(es_par_LUT4_Z_D[1]),
    .C(es_par_LUT4_Z_D[2]),
    .D(es_par_LUT4_Z_D[3]),
    .Z(es_par)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) es_par_LUT4_Z_D_LUT4_Z (
    .A(\sub0.LSB [15]),
    .B(\sub0.LSB [14]),
    .C(\sub0.LSB [13]),
    .D(\sub0.LSB [12]),
    .Z(es_par_LUT4_Z_D[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) es_par_LUT4_Z_D_LUT4_Z_1 (
    .A(\sub0.LSB [7]),
    .B(\sub0.LSB [6]),
    .C(\sub0.LSB [5]),
    .D(\sub0.LSB [4]),
    .Z(es_par_LUT4_Z_D[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0100)
  ) es_par_LUT4_Z_D_LUT4_Z_2 (
    .A(\sub0.LSB [3]),
    .B(\sub0.LSB [2]),
    .C(\sub0.LSB [1]),
    .D(\sub0.LSB [0]),
    .Z(es_par_LUT4_Z_D[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) es_par_LUT4_Z_D_LUT4_Z_3 (
    .A(\sub0.LSB [11]),
    .B(\sub0.LSB [10]),
    .C(\sub0.LSB [9]),
    .D(\sub0.LSB [8]),
    .Z(es_par_LUT4_Z_D[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0002)
  ) init_LUT4_A (
    .A(init),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(init_LUT4_A_Z[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0008)
  ) init_LUT4_A_Z_LUT4_Z (
    .A(\control0.cont [4]),
    .B(\control0.cont [2]),
    .C(\control0.cont [1]),
    .D(\control0.cont [0]),
    .Z(init_LUT4_A_Z[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:12.29-12.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \lcr0.B_CCU2C_B0  (
    .A0(N[15]),
    .A1(1'h0),
    .B0(\lcr0.B [15]),
    .B1(1'h0),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(\lcr0.B_CCU2C_B1_2_COUT ),
    .COUT(\lcr0.B_CCU2C_B0_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\sub0.LSB_TRELLIS_FF_Q_DI [14]),
    .S1(\lcr0.B_CCU2C_B0_S1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:12.29-12.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \lcr0.B_CCU2C_B1  (
    .A0(N[7]),
    .A1(N[8]),
    .B0(\lcr0.B [7]),
    .B1(\lcr0.B [8]),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(\lcr0.B_CCU2C_B1_4_COUT ),
    .COUT(\lcr0.B_CCU2C_B1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\sub0.LSB_TRELLIS_FF_Q_DI [6]),
    .S1(\sub0.LSB_TRELLIS_FF_Q_DI [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:12.29-12.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \lcr0.B_CCU2C_B1_1  (
    .A0(N[9]),
    .A1(N[10]),
    .B0(\lcr0.B [9]),
    .B1(\lcr0.B [10]),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(\lcr0.B_CCU2C_B1_COUT ),
    .COUT(\lcr0.B_CCU2C_B1_1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\sub0.LSB_TRELLIS_FF_Q_DI [8]),
    .S1(\sub0.LSB_TRELLIS_FF_Q_DI [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:12.29-12.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \lcr0.B_CCU2C_B1_2  (
    .A0(N[13]),
    .A1(N[14]),
    .B0(\lcr0.B [13]),
    .B1(\lcr0.B [14]),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(\lcr0.B_CCU2C_B1_5_COUT ),
    .COUT(\lcr0.B_CCU2C_B1_2_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\sub0.LSB_TRELLIS_FF_Q_DI [12]),
    .S1(\sub0.LSB_TRELLIS_FF_Q_DI [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:12.29-12.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \lcr0.B_CCU2C_B1_3  (
    .A0(N[3]),
    .A1(N[4]),
    .B0(\lcr0.B [3]),
    .B1(\lcr0.B [4]),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(\lcr0.B_CCU2C_B1_6_COUT ),
    .COUT(\lcr0.B_CCU2C_B1_3_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\sub0.LSB_TRELLIS_FF_Q_DI [2]),
    .S1(\sub0.LSB_TRELLIS_FF_Q_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:12.29-12.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \lcr0.B_CCU2C_B1_4  (
    .A0(N[5]),
    .A1(N[6]),
    .B0(\lcr0.B [5]),
    .B1(\lcr0.B [6]),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(\lcr0.B_CCU2C_B1_3_COUT ),
    .COUT(\lcr0.B_CCU2C_B1_4_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\sub0.LSB_TRELLIS_FF_Q_DI [4]),
    .S1(\sub0.LSB_TRELLIS_FF_Q_DI [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:12.29-12.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \lcr0.B_CCU2C_B1_5  (
    .A0(N[11]),
    .A1(N[12]),
    .B0(\lcr0.B [11]),
    .B1(\lcr0.B [12]),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(\lcr0.B_CCU2C_B1_1_COUT ),
    .COUT(\lcr0.B_CCU2C_B1_5_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\sub0.LSB_TRELLIS_FF_Q_DI [10]),
    .S1(\sub0.LSB_TRELLIS_FF_Q_DI [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:12.29-12.34|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \lcr0.B_CCU2C_B1_6  (
    .A0(N[1]),
    .A1(N[2]),
    .B0(\lcr0.B [1]),
    .B1(\lcr0.B [2]),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(1'h1),
    .COUT(\lcr0.B_CCU2C_B1_6_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\sub0.LSB_TRELLIS_FF_Q_DI [0]),
    .S1(\sub0.LSB_TRELLIS_FF_Q_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.B_TRELLIS_FF_Q  (
    .CE(\control0.w_sh_l ),
    .CLK(clk),
    .DI(\rcr0.A [1]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\lcr0.B [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.B_TRELLIS_FF_Q_1  (
    .CE(\control0.w_sh_l ),
    .CLK(clk),
    .DI(\rcr0.A [2]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\lcr0.B [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.B_TRELLIS_FF_Q_10  (
    .CE(\control0.w_sh_l ),
    .CLK(clk),
    .DI(\rcr0.A [11]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\lcr0.B [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.B_TRELLIS_FF_Q_11  (
    .CE(\control0.w_sh_l ),
    .CLK(clk),
    .DI(\rcr0.A [12]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\lcr0.B [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.B_TRELLIS_FF_Q_12  (
    .CE(\control0.w_sh_l ),
    .CLK(clk),
    .DI(\rcr0.A [13]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\lcr0.B [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.B_TRELLIS_FF_Q_13  (
    .CE(\control0.w_sh_l ),
    .CLK(clk),
    .DI(\rcr0.A [14]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\lcr0.B [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.B_TRELLIS_FF_Q_14  (
    .CE(\control0.w_sh_l ),
    .CLK(clk),
    .DI(\rcr0.A [0]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\lcr0.B [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.B_TRELLIS_FF_Q_2  (
    .CE(\control0.w_sh_l ),
    .CLK(clk),
    .DI(\rcr0.A [3]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\lcr0.B [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.B_TRELLIS_FF_Q_3  (
    .CE(\control0.w_sh_l ),
    .CLK(clk),
    .DI(\rcr0.A [4]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\lcr0.B [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.B_TRELLIS_FF_Q_4  (
    .CE(\control0.w_sh_l ),
    .CLK(clk),
    .DI(\rcr0.A [5]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\lcr0.B [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.B_TRELLIS_FF_Q_5  (
    .CE(\control0.w_sh_l ),
    .CLK(clk),
    .DI(\rcr0.A [6]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\lcr0.B [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.B_TRELLIS_FF_Q_6  (
    .CE(\control0.w_sh_l ),
    .CLK(clk),
    .DI(\rcr0.A [7]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\lcr0.B [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.B_TRELLIS_FF_Q_7  (
    .CE(\control0.w_sh_l ),
    .CLK(clk),
    .DI(\rcr0.A [8]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\lcr0.B [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.B_TRELLIS_FF_Q_8  (
    .CE(\control0.w_sh_l ),
    .CLK(clk),
    .DI(\rcr0.A [9]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\lcr0.B [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.B_TRELLIS_FF_Q_9  (
    .CE(\control0.w_sh_l ),
    .CLK(clk),
    .DI(\rcr0.A [10]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\lcr0.B [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rcr0.A_TRELLIS_FF_Q  (
    .CE(rst_LUT4_B_D_LUT4_C_Z),
    .CLK(clk),
    .DI(N[15]),
    .LSR(\rcr0.A_TRELLIS_FF_Q_LSR ),
    .Q(\rcr0.A [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.A_TRELLIS_FF_Q_1  (
    .CE(rst_LUT4_B_D_LUT4_C_Z),
    .CLK(clk),
    .DI(\rcr0.A_TRELLIS_FF_Q_9_DI [14]),
    .LSR(1'h0),
    .Q(\rcr0.A [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.A_TRELLIS_FF_Q_10  (
    .CE(rst_LUT4_B_D_LUT4_C_Z),
    .CLK(clk),
    .DI(\rcr0.A_TRELLIS_FF_Q_9_DI [5]),
    .LSR(1'h0),
    .Q(\rcr0.A [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.A_TRELLIS_FF_Q_11  (
    .CE(rst_LUT4_B_D_LUT4_C_Z),
    .CLK(clk),
    .DI(\rcr0.A_TRELLIS_FF_Q_9_DI [4]),
    .LSR(1'h0),
    .Q(\rcr0.A [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.A_TRELLIS_FF_Q_12  (
    .CE(rst_LUT4_B_D_LUT4_C_Z),
    .CLK(clk),
    .DI(\rcr0.A_TRELLIS_FF_Q_9_DI [3]),
    .LSR(1'h0),
    .Q(\rcr0.A [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.A_TRELLIS_FF_Q_13  (
    .CE(rst_LUT4_B_D_LUT4_C_Z),
    .CLK(clk),
    .DI(\rcr0.A_TRELLIS_FF_Q_9_DI [2]),
    .LSR(1'h0),
    .Q(\rcr0.A [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.A_TRELLIS_FF_Q_14  (
    .CE(rst_LUT4_B_D_LUT4_C_Z),
    .CLK(clk),
    .DI(\rcr0.A_TRELLIS_FF_Q_9_DI [1]),
    .LSR(1'h0),
    .Q(\rcr0.A [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.A_TRELLIS_FF_Q_15  (
    .CE(rst_LUT4_B_D_LUT4_C_Z),
    .CLK(clk),
    .DI(\rcr0.A_TRELLIS_FF_Q_9_DI [0]),
    .LSR(1'h0),
    .Q(\rcr0.A [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.A_TRELLIS_FF_Q_2  (
    .CE(rst_LUT4_B_D_LUT4_C_Z),
    .CLK(clk),
    .DI(\rcr0.A_TRELLIS_FF_Q_9_DI [13]),
    .LSR(1'h0),
    .Q(\rcr0.A [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.A_TRELLIS_FF_Q_3  (
    .CE(rst_LUT4_B_D_LUT4_C_Z),
    .CLK(clk),
    .DI(\rcr0.A_TRELLIS_FF_Q_9_DI [12]),
    .LSR(1'h0),
    .Q(\rcr0.A [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.A_TRELLIS_FF_Q_4  (
    .CE(rst_LUT4_B_D_LUT4_C_Z),
    .CLK(clk),
    .DI(\rcr0.A_TRELLIS_FF_Q_9_DI [11]),
    .LSR(1'h0),
    .Q(\rcr0.A [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.A_TRELLIS_FF_Q_5  (
    .CE(rst_LUT4_B_D_LUT4_C_Z),
    .CLK(clk),
    .DI(\rcr0.A_TRELLIS_FF_Q_9_DI [10]),
    .LSR(1'h0),
    .Q(\rcr0.A [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.A_TRELLIS_FF_Q_6  (
    .CE(rst_LUT4_B_D_LUT4_C_Z),
    .CLK(clk),
    .DI(\rcr0.A_TRELLIS_FF_Q_9_DI [9]),
    .LSR(1'h0),
    .Q(\rcr0.A [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.A_TRELLIS_FF_Q_7  (
    .CE(rst_LUT4_B_D_LUT4_C_Z),
    .CLK(clk),
    .DI(\rcr0.A_TRELLIS_FF_Q_9_DI [8]),
    .LSR(1'h0),
    .Q(\rcr0.A [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.A_TRELLIS_FF_Q_8  (
    .CE(rst_LUT4_B_D_LUT4_C_Z),
    .CLK(clk),
    .DI(\rcr0.A_TRELLIS_FF_Q_9_DI [7]),
    .LSR(1'h0),
    .Q(\rcr0.A [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rcr.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rcr0.A_TRELLIS_FF_Q_9  (
    .CE(rst_LUT4_B_D_LUT4_C_Z),
    .CLK(clk),
    .DI(\rcr0.A_TRELLIS_FF_Q_9_DI [6]),
    .LSR(1'h0),
    .Q(\rcr0.A [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h0030)
  ) \rcr0.A_TRELLIS_FF_Q_LSR_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\rcr0.A_TRELLIS_FF_Q_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h5155)
  ) rst_LUT4_A (
    .A(rst),
    .B(\control0.cont [3]),
    .C(init_LUT4_A_Z[2]),
    .D(init_LUT4_A_Z[3]),
    .Z(rst_LUT4_A_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'haafe)
  ) rst_LUT4_A_1 (
    .A(rst),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(rst_LUT4_B_D[3]),
    .Z(rst_LUT4_A_1_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hccfc)
  ) rst_LUT4_B (
    .A(1'h0),
    .B(rst),
    .C(\control0.state [2]),
    .D(rst_LUT4_B_D[3]),
    .Z(rst_LUT4_B_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0a4f)
  ) rst_LUT4_B_D_LUT4_C (
    .A(\control0.state [2]),
    .B(\control0.state [1]),
    .C(rst_LUT4_B_D[3]),
    .D(\control0.state [0]),
    .Z(rst_LUT4_B_D_LUT4_C_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0a0b)
  ) rst_LUT4_B_D_LUT4_C_1 (
    .A(\control0.state [2]),
    .B(\control0.state [1]),
    .C(rst_LUT4_B_D[3]),
    .D(\control0.state [0]),
    .Z(rst_LUT4_B_D_LUT4_C_1_Z[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h00f0)
  ) rst_LUT4_B_D_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(\control0.state [2]),
    .D(\control0.state [1]),
    .Z(rst_LUT4_B_D[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX rst_LUT4_B_Z_PFUMX_ALUT (
    .ALUT(rst_LUT4_B_Z),
    .BLUT(rst_LUT4_A_1_Z),
    .C0(\control0.state [0]),
    .Z(rst_LUT4_B_Z_PFUMX_ALUT_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h0f00)
  ) rst_LUT4_C (
    .A(1'h0),
    .B(1'h0),
    .C(rst),
    .D(init_LUT4_A_Z[2]),
    .Z(rst_LUT4_C_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \sub0.LSB_TRELLIS_FF_Q  (
    .CE(\control0.w_sub ),
    .CLK(clk),
    .DI(\sub0.LSB_TRELLIS_FF_Q_DI [12]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\sub0.LSB [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \sub0.LSB_TRELLIS_FF_Q_1  (
    .CE(\control0.w_sub ),
    .CLK(clk),
    .DI(\sub0.LSB_TRELLIS_FF_Q_DI [14]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\sub0.LSB [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \sub0.LSB_TRELLIS_FF_Q_10  (
    .CE(\control0.w_sub ),
    .CLK(clk),
    .DI(\sub0.LSB_TRELLIS_FF_Q_DI [6]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\sub0.LSB [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \sub0.LSB_TRELLIS_FF_Q_11  (
    .CE(\control0.w_sub ),
    .CLK(clk),
    .DI(\sub0.LSB_TRELLIS_FF_Q_DI [10]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\sub0.LSB [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \sub0.LSB_TRELLIS_FF_Q_12  (
    .CE(\control0.w_sub ),
    .CLK(clk),
    .DI(\sub0.LSB_TRELLIS_FF_Q_DI [9]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\sub0.LSB [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \sub0.LSB_TRELLIS_FF_Q_13  (
    .CE(\control0.w_sub ),
    .CLK(clk),
    .DI(\sub0.LSB_TRELLIS_FF_Q_DI [8]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\sub0.LSB [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \sub0.LSB_TRELLIS_FF_Q_14  (
    .CE(\control0.w_sub ),
    .CLK(clk),
    .DI(\sub0.LSB_TRELLIS_FF_Q_DI [5]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\sub0.LSB [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \sub0.LSB_TRELLIS_FF_Q_15  (
    .CE(\control0.w_sub ),
    .CLK(clk),
    .DI(N[0]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\sub0.LSB [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \sub0.LSB_TRELLIS_FF_Q_2  (
    .CE(\control0.w_sub ),
    .CLK(clk),
    .DI(\sub0.LSB_TRELLIS_FF_Q_DI [13]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\sub0.LSB [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \sub0.LSB_TRELLIS_FF_Q_3  (
    .CE(\control0.w_sub ),
    .CLK(clk),
    .DI(\sub0.LSB_TRELLIS_FF_Q_DI [4]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\sub0.LSB [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \sub0.LSB_TRELLIS_FF_Q_4  (
    .CE(\control0.w_sub ),
    .CLK(clk),
    .DI(\sub0.LSB_TRELLIS_FF_Q_DI [11]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\sub0.LSB [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \sub0.LSB_TRELLIS_FF_Q_5  (
    .CE(\control0.w_sub ),
    .CLK(clk),
    .DI(\sub0.LSB_TRELLIS_FF_Q_DI [7]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\sub0.LSB [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \sub0.LSB_TRELLIS_FF_Q_6  (
    .CE(\control0.w_sub ),
    .CLK(clk),
    .DI(\sub0.LSB_TRELLIS_FF_Q_DI [3]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\sub0.LSB [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \sub0.LSB_TRELLIS_FF_Q_7  (
    .CE(\control0.w_sub ),
    .CLK(clk),
    .DI(\sub0.LSB_TRELLIS_FF_Q_DI [2]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\sub0.LSB [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \sub0.LSB_TRELLIS_FF_Q_8  (
    .CE(\control0.w_sub ),
    .CLK(clk),
    .DI(\sub0.LSB_TRELLIS_FF_Q_DI [1]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\sub0.LSB [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "sub.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \sub0.LSB_TRELLIS_FF_Q_9  (
    .CE(\control0.w_sub ),
    .CLK(clk),
    .DI(\sub0.LSB_TRELLIS_FF_Q_DI [0]),
    .LSR(rst_LUT4_B_D_LUT4_C_1_Z[2]),
    .Q(\sub0.LSB [1])
  );
  assign rst_LUT4_B_D_LUT4_C_1_Z[1:0] = { \rcr0.A [1], N[0] };
  assign { init_LUT4_A_Z[4], init_LUT4_A_Z[1:0] } = { done, \control0.cont [3], rst };
  assign \rcr0.clk  = clk;
  assign \control0.init  = init;
  assign \control0.z  = es_impar;
  assign \control0.clk  = clk;
  assign \rcr0.N  = N;
  assign \control0.done  = done;
  assign \lcr0.A  = \rcr0.A ;
  assign { rst_LUT4_B_D[4], rst_LUT4_B_D[2:0] } = { \control0.state [0], \control0.state [1], \control0.state [2], rst };
  assign \control0.rst  = rst;
  assign \sub0.B  = { \lcr0.B [15:1], 1'h0 };
  assign done_PFUMX_C0_Z[1] = done;
  assign \sub0.N  = N;
  assign \lcr0.clk  = clk;
  assign \sub0.subtr  = \control0.w_sub ;
  assign \sub0.clk  = clk;
  assign \lcr0.shift  = \control0.w_sh_l ;
  assign \comp0.tmp  = es_impar;
  assign \comp0.z  = es_impar;
  assign \comp0.LSB  = \sub0.LSB ;
  assign LSB = \sub0.LSB ;
  assign B = { \lcr0.B [15:1], 1'h0 };
  assign A = \rcr0.A ;
  assign z = es_impar;
  assign w_sub = \control0.w_sub ;
  assign \lcr0.B [0] = 1'h0;
  assign w_sh_l = \control0.w_sh_l ;
endmodule
