/* Generated by Yosys 0.65+57 (git sha1 9d0cdb855, clang++ 18.1.8 -fPIC -O3) */

/* hdlname = "raiz_16" */
/* top =  1  */
/* src = "raiz_16.v:1.1-40.10" */
module raiz_16(clk, rst, init, in_N, Q_out, N_out, done);
  /* src = "raiz_16.v:2.11-2.14" */
  input clk;
  wire clk;
  /* src = "raiz_16.v:3.11-3.14" */
  input rst;
  wire rst;
  /* src = "raiz_16.v:4.11-4.15" */
  input init;
  wire init;
  /* src = "raiz_16.v:5.18-5.22" */
  input [15:0] in_N;
  wire [15:0] in_N;
  /* src = "raiz_16.v:6.19-6.24" */
  output [15:0] Q_out;
  wire [15:0] Q_out;
  /* src = "raiz_16.v:7.19-7.24" */
  output [15:0] N_out;
  wire [15:0] N_out;
  /* src = "raiz_16.v:8.12-8.16" */
  output done;
  wire done;
  /* src = "raiz_16.v:16.17-16.18" */
  wire [15:0] Q;
  /* hdlname = "acc0 Q" */
  /* src = "acc_q.v:4.23-4.24" */
  wire [15:0] \acc0.Q ;
  wire [15:0] \acc0.Q_TRELLIS_FF_Q_DI ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_10_D ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_11_D ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_12_D ;
  /* abc9_carry = 32'd1 */
  /* src = "acc_q.v:13.29-13.46|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_12_D_CCU2C_S1_COUT ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_13_D ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_14_D ;
  /* abc9_carry = 32'd1 */
  /* src = "acc_q.v:13.29-13.46|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_14_D_CCU2C_S1_COUT ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [1:0] \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_15_D ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_2_C ;
  /* abc9_carry = 32'd1 */
  /* src = "acc_q.v:13.29-13.46|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_2_C_CCU2C_S1_COUT ;
  /* unused_bits = "0" */
  wire \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_2_C_CCU2C_S1_S0 ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_3_D ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_4_D ;
  /* abc9_carry = 32'd1 */
  /* src = "acc_q.v:13.29-13.46|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_4_D_CCU2C_S1_COUT ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_5_D ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_6_D ;
  /* abc9_carry = 32'd1 */
  /* src = "acc_q.v:13.29-13.46|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_6_D_CCU2C_S1_COUT ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_7_D ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_8_D ;
  /* abc9_carry = 32'd1 */
  /* src = "acc_q.v:13.29-13.46|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_8_D_CCU2C_S1_COUT ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_9_D ;
  /* abc9_carry = 32'd1 */
  /* src = "acc_q.v:13.29-13.46|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_9_D_CCU2C_S0_COUT ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_D ;
  /* abc9_carry = 32'd1 */
  /* src = "acc_q.v:13.29-13.46|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  /* unused_bits = "0" */
  wire \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_D_CCU2C_S0_COUT ;
  /* hdlname = "acc0 clk" */
  /* src = "acc_q.v:2.11-2.14" */
  wire \acc0.clk ;
  /* hdlname = "acc0 load_q" */
  /* src = "acc_q.v:2.16-2.22" */
  wire \acc0.load_q ;
  /* hdlname = "acc0 z_Cont" */
  /* src = "acc_q.v:3.18-3.24" */
  wire [15:0] \acc0.z_Cont ;
  /* hdlname = "acc_n0 clk" */
  /* src = "acc_n.v:2.11-2.14" */
  wire \acc_n0.clk ;
  /* hdlname = "acc_n0 in_N" */
  /* src = "acc_n.v:3.18-3.22" */
  wire [15:0] \acc_n0.in_N ;
  /* hdlname = "acc_n0 w_N" */
  /* src = "acc_n.v:4.23-4.26" */
  wire [15:0] \acc_n0.w_N ;
  wire \acc_n0.w_N_TRELLIS_FF_Q_CE ;
  /* hdlname = "add0 Q" */
  /* src = "add_temp.v:2.18-2.19" */
  wire [15:0] \add0.Q ;
  /* hdlname = "add0 z_Cont" */
  /* src = "add_temp.v:2.21-2.27" */
  wire [15:0] \add0.z_Cont ;
  /* hdlname = "comp_x0 w_N" */
  /* src = "comp_x.v:2.18-2.21" */
  wire [15:0] \comp_x0.w_N ;
  /* hdlname = "comp_y0 z_Cont" */
  /* src = "comp_y.v:2.18-2.24" */
  wire [15:0] \comp_y0.z_Cont ;
  /* hdlname = "control0 clk" */
  /* src = "control_raiz.v:2.11-2.14" */
  wire \control0.clk ;
  /* hdlname = "control0 cont" */
  /* src = "control_raiz.v:14.15-14.19" */
  wire [4:0] \control0.cont ;
  /* force_downto = 32'd1 */
  /* src = "control_raiz.v:53.32-53.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:34.26-34.27" */
  wire [4:0] \control0.cont_TRELLIS_FF_Q_DI ;
  /* abc9_carry = 32'd1 */
  /* src = "control_raiz.v:53.32-53.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  /* unused_bits = "0" */
  wire \control0.cont_TRELLIS_FF_Q_DI_CCU2C_S0_COUT ;
  /* unused_bits = "0" */
  wire \control0.cont_TRELLIS_FF_Q_DI_CCU2C_S0_S1 ;
  /* abc9_carry = 32'd1 */
  /* src = "control_raiz.v:53.32-53.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \control0.cont_TRELLIS_FF_Q_DI_CCU2C_S1_1_COUT ;
  /* abc9_carry = 32'd1 */
  /* src = "control_raiz.v:53.32-53.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \control0.cont_TRELLIS_FF_Q_DI_CCU2C_S1_COUT ;
  /* unused_bits = "0" */
  wire \control0.cont_TRELLIS_FF_Q_DI_CCU2C_S1_S0 ;
  /* hdlname = "control0 done" */
  /* src = "control_raiz.v:3.16-3.20" */
  wire \control0.done ;
  /* hdlname = "control0 init" */
  /* src = "control_raiz.v:2.21-2.25" */
  wire \control0.init ;
  /* hdlname = "control0 rst" */
  /* src = "control_raiz.v:2.16-2.19" */
  wire \control0.rst ;
  /* hdlname = "control0 state" */
  /* src = "control_raiz.v:13.15-13.20" */
  wire [2:0] \control0.state ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [1:0] \control0.state_LUT4_D_Z ;
  wire \control0.state_TRELLIS_FF_Q_1_DI ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire \control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z_ALUT ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire \control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z_BLUT ;
  wire \control0.state_TRELLIS_FF_Q_2_DI ;
  wire \control0.state_TRELLIS_FF_Q_DI ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire \control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire \control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT ;
  /* hdlname = "control0 w_load_q" */
  /* src = "control_raiz.v:3.45-3.53" */
  wire \control0.w_load_q ;
  /* hdlname = "control0 w_sh_r2" */
  /* src = "control_raiz.v:3.29-3.36" */
  wire \control0.w_sh_r2 ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] done_LUT4_D_1_C;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [4:0] done_LUT4_D_1_Z;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] done_LUT4_D_1_Z_LUT4_Z_D;
  wire done_LUT4_D_Z;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [4:0] init_LUT4_A_Z;
  wire init_LUT4_A_Z_CCU2C_COUT_B0;
  wire init_LUT4_A_Z_CCU2C_COUT_B1;
  /* abc9_carry = 32'd1 */
  /* src = "add_temp.v:5.19-5.29|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire init_LUT4_A_Z_CCU2C_COUT_B1_CCU2C_S1_CIN;
  /* abc9_carry = 32'd1 */
  /* src = "add_temp.v:5.19-5.29|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire init_LUT4_A_Z_CCU2C_COUT_B1_CCU2C_S1_CIN_CCU2C_COUT_CIN;
  /* abc9_carry = 32'd1 */
  /* src = "add_temp.v:5.19-5.29|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  /* unused_bits = "0" */
  wire init_LUT4_A_Z_CCU2C_COUT_B1_CCU2C_S1_COUT;
  /* abc9_carry = 32'd1 */
  /* src = "acc_n.v:12.30-12.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire init_LUT4_A_Z_CCU2C_COUT_CIN;
  wire init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_B0;
  wire init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_B1;
  /* abc9_carry = 32'd1 */
  /* src = "acc_n.v:12.30-12.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_CIN;
  wire init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_CIN_CCU2C_COUT_B0;
  wire init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_CIN_CCU2C_COUT_B1;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_S0;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_S1;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] init_LUT4_A_Z_CCU2C_COUT_S0;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] init_LUT4_A_Z_CCU2C_COUT_S1;
  wire [15:0] init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_10_D;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_11_D;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_1_D;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_2_D;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_3_D;
  wire init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_3_D_CCU2C_S1_B0;
  wire init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_3_D_CCU2C_S1_B1;
  /* abc9_carry = 32'd1 */
  /* src = "add_temp.v:5.19-5.29|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_3_D_CCU2C_S1_B1_CCU2C_S1_COUT;
  /* abc9_carry = 32'd1 */
  /* src = "acc_n.v:12.30-12.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_3_D_CCU2C_S1_COUT;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_4_D;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_5_D;
  wire init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_5_D_CCU2C_S1_B0;
  wire init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_5_D_CCU2C_S1_B1;
  /* abc9_carry = 32'd1 */
  /* src = "add_temp.v:5.19-5.29|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_5_D_CCU2C_S1_B1_CCU2C_S1_COUT;
  /* abc9_carry = 32'd1 */
  /* src = "acc_n.v:12.30-12.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_5_D_CCU2C_S1_COUT;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_6_D;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_7_D;
  wire init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_7_D_CCU2C_S1_B0;
  wire init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_7_D_CCU2C_S1_B1;
  /* abc9_carry = 32'd1 */
  /* src = "add_temp.v:5.19-5.29|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_7_D_CCU2C_S1_B1_CCU2C_S1_COUT;
  /* abc9_carry = 32'd1 */
  /* src = "acc_n.v:12.30-12.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_7_D_CCU2C_S1_COUT;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_8_D;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_9_D;
  wire init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_9_D_CCU2C_S1_B0;
  wire init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_9_D_CCU2C_S1_B1;
  /* abc9_carry = 32'd1 */
  /* src = "add_temp.v:5.19-5.29|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_9_D_CCU2C_S1_B1_CCU2C_S1_COUT;
  /* abc9_carry = 32'd1 */
  /* src = "acc_n.v:12.30-12.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_9_D_CCU2C_S1_COUT;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_D;
  wire init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_D_CCU2C_S0_B0;
  wire init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_D_CCU2C_S0_B1;
  /* abc9_carry = 32'd1 */
  /* src = "add_temp.v:5.19-5.29|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_D_CCU2C_S0_B1_CCU2C_S1_COUT;
  /* abc9_carry = 32'd1 */
  /* src = "acc_n.v:12.30-12.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_D_CCU2C_S0_COUT;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] init_LUT4_A_Z_LUT4_D_Z;
  /* hdlname = "rsr0 clk" */
  /* src = "rsr_cont.v:2.11-2.14" */
  wire \rsr0.clk ;
  /* hdlname = "rsr0 shift" */
  /* src = "rsr_cont.v:2.22-2.27" */
  wire \rsr0.shift ;
  /* hdlname = "rsr0 z_Cont" */
  /* src = "rsr_cont.v:3.23-3.29" */
  wire [15:0] \rsr0.z_Cont ;
  wire \rsr0.z_Cont_TRELLIS_FF_Q_DI ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [1:0] rst_LUT4_B_1_Z;
  wire rst_LUT4_B_Z;
  /* src = "raiz_16.v:15.17-15.20" */
  wire [15:0] w_N;
  /* src = "raiz_16.v:10.33-10.41" */
  wire w_load_q;
  /* src = "raiz_16.v:10.17-10.24" */
  wire w_sh_r2;
  wire [14:0] z_Cont;
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:8.5-19.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.Q_TRELLIS_FF_Q  (
    .CE(\acc0.load_q ),
    .CLK(clk),
    .DI(\acc0.Q_TRELLIS_FF_Q_DI [14]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\acc0.Q [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:8.5-19.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.Q_TRELLIS_FF_Q_1  (
    .CE(\acc0.load_q ),
    .CLK(clk),
    .DI(\acc0.Q_TRELLIS_FF_Q_DI [9]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\acc0.Q [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:8.5-19.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.Q_TRELLIS_FF_Q_10  (
    .CE(\acc0.load_q ),
    .CLK(clk),
    .DI(\acc0.Q_TRELLIS_FF_Q_DI [15]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\acc0.Q [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:8.5-19.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.Q_TRELLIS_FF_Q_11  (
    .CE(\acc0.load_q ),
    .CLK(clk),
    .DI(\acc0.Q_TRELLIS_FF_Q_DI [1]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\acc0.Q [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:8.5-19.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.Q_TRELLIS_FF_Q_12  (
    .CE(\acc0.load_q ),
    .CLK(clk),
    .DI(\acc0.Q_TRELLIS_FF_Q_DI [13]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\acc0.Q [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:8.5-19.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.Q_TRELLIS_FF_Q_13  (
    .CE(\acc0.load_q ),
    .CLK(clk),
    .DI(\acc0.Q_TRELLIS_FF_Q_DI [12]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\acc0.Q [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:8.5-19.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.Q_TRELLIS_FF_Q_14  (
    .CE(\acc0.load_q ),
    .CLK(clk),
    .DI(\acc0.Q_TRELLIS_FF_Q_DI [11]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\acc0.Q [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:8.5-19.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.Q_TRELLIS_FF_Q_15  (
    .CE(\acc0.load_q ),
    .CLK(clk),
    .DI(\acc0.Q_TRELLIS_FF_Q_DI [10]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\acc0.Q [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:8.5-19.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.Q_TRELLIS_FF_Q_2  (
    .CE(\acc0.load_q ),
    .CLK(clk),
    .DI(\acc0.Q_TRELLIS_FF_Q_DI [8]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\acc0.Q [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:8.5-19.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.Q_TRELLIS_FF_Q_3  (
    .CE(\acc0.load_q ),
    .CLK(clk),
    .DI(\acc0.Q_TRELLIS_FF_Q_DI [7]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\acc0.Q [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:8.5-19.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.Q_TRELLIS_FF_Q_4  (
    .CE(\acc0.load_q ),
    .CLK(clk),
    .DI(\acc0.Q_TRELLIS_FF_Q_DI [6]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\acc0.Q [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:8.5-19.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.Q_TRELLIS_FF_Q_5  (
    .CE(\acc0.load_q ),
    .CLK(clk),
    .DI(\acc0.Q_TRELLIS_FF_Q_DI [5]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\acc0.Q [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:8.5-19.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.Q_TRELLIS_FF_Q_6  (
    .CE(\acc0.load_q ),
    .CLK(clk),
    .DI(\acc0.Q_TRELLIS_FF_Q_DI [4]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\acc0.Q [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:8.5-19.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.Q_TRELLIS_FF_Q_7  (
    .CE(\acc0.load_q ),
    .CLK(clk),
    .DI(\acc0.Q_TRELLIS_FF_Q_DI [3]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\acc0.Q [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:8.5-19.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.Q_TRELLIS_FF_Q_8  (
    .CE(\acc0.load_q ),
    .CLK(clk),
    .DI(\acc0.Q_TRELLIS_FF_Q_DI [2]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\acc0.Q [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:8.5-19.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \acc0.Q_TRELLIS_FF_Q_9  (
    .CE(\acc0.load_q ),
    .CLK(clk),
    .DI(\acc0.Q_TRELLIS_FF_Q_DI [0]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\acc0.Q [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hfc0c)
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z  (
    .A(1'h0),
    .B(\acc0.Q [15]),
    .C(\control0.state_LUT4_D_Z [0]),
    .D(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_D [2]),
    .Z(\acc0.Q_TRELLIS_FF_Q_DI [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h3cf0)
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_1  (
    .A(1'h0),
    .B(\rsr0.z_Cont [0]),
    .C(\acc0.Q [1]),
    .D(\control0.state_LUT4_D_Z [0]),
    .Z(\acc0.Q_TRELLIS_FF_Q_DI [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hfc0c)
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_10  (
    .A(1'h0),
    .B(\acc0.Q [10]),
    .C(\control0.state_LUT4_D_Z [0]),
    .D(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_10_D [2]),
    .Z(\acc0.Q_TRELLIS_FF_Q_DI [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hfc0c)
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_11  (
    .A(1'h0),
    .B(\acc0.Q [11]),
    .C(\control0.state_LUT4_D_Z [0]),
    .D(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_11_D [2]),
    .Z(\acc0.Q_TRELLIS_FF_Q_DI [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hfc0c)
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_12  (
    .A(1'h0),
    .B(\acc0.Q [12]),
    .C(\control0.state_LUT4_D_Z [0]),
    .D(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_12_D [2]),
    .Z(\acc0.Q_TRELLIS_FF_Q_DI [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:13.29-13.46|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_12_D_CCU2C_S1  (
    .A0(\rsr0.z_Cont [10]),
    .A1(1'h0),
    .B0(\acc0.Q [11]),
    .B1(\acc0.Q [12]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_9_D_CCU2C_S0_COUT ),
    .COUT(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_12_D_CCU2C_S1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_11_D [2]),
    .S1(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_12_D [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hfc0c)
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_13  (
    .A(1'h0),
    .B(\acc0.Q [13]),
    .C(\control0.state_LUT4_D_Z [0]),
    .D(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_13_D [2]),
    .Z(\acc0.Q_TRELLIS_FF_Q_DI [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hfc0c)
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_14  (
    .A(1'h0),
    .B(\acc0.Q [14]),
    .C(\control0.state_LUT4_D_Z [0]),
    .D(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_14_D [2]),
    .Z(\acc0.Q_TRELLIS_FF_Q_DI [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:13.29-13.46|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_14_D_CCU2C_S1  (
    .A0(\rsr0.z_Cont [12]),
    .A1(1'h0),
    .B0(\acc0.Q [13]),
    .B1(\acc0.Q [14]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_12_D_CCU2C_S1_COUT ),
    .COUT(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_14_D_CCU2C_S1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_13_D [2]),
    .S1(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_14_D [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hf000)
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_15  (
    .A(1'h0),
    .B(1'h0),
    .C(\control0.state_LUT4_D_Z [0]),
    .D(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_15_D [1]),
    .Z(\acc0.Q_TRELLIS_FF_Q_DI [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hf0cc)
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_2  (
    .A(1'h0),
    .B(\acc0.Q [2]),
    .C(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_2_C [1]),
    .D(\control0.state_LUT4_D_Z [0]),
    .Z(\acc0.Q_TRELLIS_FF_Q_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:13.29-13.46|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_2_C_CCU2C_S1  (
    .A0(\rsr0.z_Cont [0]),
    .A1(1'h0),
    .B0(\acc0.Q [1]),
    .B1(\acc0.Q [2]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(1'h0),
    .COUT(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_2_C_CCU2C_S1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_2_C_CCU2C_S1_S0 ),
    .S1(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_2_C [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hfc0c)
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_3  (
    .A(1'h0),
    .B(\acc0.Q [3]),
    .C(\control0.state_LUT4_D_Z [0]),
    .D(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_3_D [2]),
    .Z(\acc0.Q_TRELLIS_FF_Q_DI [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hfc0c)
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_4  (
    .A(1'h0),
    .B(\acc0.Q [4]),
    .C(\control0.state_LUT4_D_Z [0]),
    .D(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_4_D [2]),
    .Z(\acc0.Q_TRELLIS_FF_Q_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:13.29-13.46|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_4_D_CCU2C_S1  (
    .A0(\rsr0.z_Cont [2]),
    .A1(1'h0),
    .B0(\acc0.Q [3]),
    .B1(\acc0.Q [4]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_2_C_CCU2C_S1_COUT ),
    .COUT(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_4_D_CCU2C_S1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_3_D [2]),
    .S1(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_4_D [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hfc0c)
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_5  (
    .A(1'h0),
    .B(\acc0.Q [5]),
    .C(\control0.state_LUT4_D_Z [0]),
    .D(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_5_D [2]),
    .Z(\acc0.Q_TRELLIS_FF_Q_DI [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hfc0c)
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_6  (
    .A(1'h0),
    .B(\acc0.Q [6]),
    .C(\control0.state_LUT4_D_Z [0]),
    .D(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_6_D [2]),
    .Z(\acc0.Q_TRELLIS_FF_Q_DI [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:13.29-13.46|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_6_D_CCU2C_S1  (
    .A0(\rsr0.z_Cont [4]),
    .A1(1'h0),
    .B0(\acc0.Q [5]),
    .B1(\acc0.Q [6]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_4_D_CCU2C_S1_COUT ),
    .COUT(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_6_D_CCU2C_S1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_5_D [2]),
    .S1(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_6_D [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hfc0c)
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_7  (
    .A(1'h0),
    .B(\acc0.Q [7]),
    .C(\control0.state_LUT4_D_Z [0]),
    .D(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_7_D [2]),
    .Z(\acc0.Q_TRELLIS_FF_Q_DI [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hfc0c)
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_8  (
    .A(1'h0),
    .B(\acc0.Q [8]),
    .C(\control0.state_LUT4_D_Z [0]),
    .D(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_8_D [2]),
    .Z(\acc0.Q_TRELLIS_FF_Q_DI [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:13.29-13.46|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_8_D_CCU2C_S1  (
    .A0(\rsr0.z_Cont [6]),
    .A1(1'h0),
    .B0(\acc0.Q [7]),
    .B1(\acc0.Q [8]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_6_D_CCU2C_S1_COUT ),
    .COUT(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_8_D_CCU2C_S1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_7_D [2]),
    .S1(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_8_D [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hfc0c)
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_9  (
    .A(1'h0),
    .B(\acc0.Q [9]),
    .C(\control0.state_LUT4_D_Z [0]),
    .D(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_9_D [2]),
    .Z(\acc0.Q_TRELLIS_FF_Q_DI [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:13.29-13.46|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_9_D_CCU2C_S0  (
    .A0(\rsr0.z_Cont [8]),
    .A1(1'h0),
    .B0(\acc0.Q [9]),
    .B1(\acc0.Q [10]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_8_D_CCU2C_S1_COUT ),
    .COUT(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_9_D_CCU2C_S0_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_9_D [2]),
    .S1(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_10_D [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_q.v:13.29-13.46|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_D_CCU2C_S0  (
    .A0(\rsr0.z_Cont [14]),
    .A1(1'h0),
    .B0(\acc0.Q [15]),
    .B1(1'h0),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_14_D_CCU2C_S1_COUT ),
    .COUT(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_D_CCU2C_S0_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_D [2]),
    .S1(\acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_15_D [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h300c)
  ) \acc0.load_q_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\acc0.load_q )
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \acc_n0.w_N_TRELLIS_FF_Q  (
    .CE(\acc_n0.w_N_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[8]),
    .LSR(1'h0),
    .Q(\acc_n0.w_N [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \acc_n0.w_N_TRELLIS_FF_Q_1  (
    .CE(\acc_n0.w_N_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[0]),
    .LSR(1'h0),
    .Q(\acc_n0.w_N [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \acc_n0.w_N_TRELLIS_FF_Q_10  (
    .CE(\acc_n0.w_N_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[5]),
    .LSR(1'h0),
    .Q(\acc_n0.w_N [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \acc_n0.w_N_TRELLIS_FF_Q_11  (
    .CE(\acc_n0.w_N_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[11]),
    .LSR(1'h0),
    .Q(\acc_n0.w_N [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \acc_n0.w_N_TRELLIS_FF_Q_12  (
    .CE(\acc_n0.w_N_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[12]),
    .LSR(1'h0),
    .Q(\acc_n0.w_N [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \acc_n0.w_N_TRELLIS_FF_Q_13  (
    .CE(\acc_n0.w_N_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[13]),
    .LSR(1'h0),
    .Q(\acc_n0.w_N [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \acc_n0.w_N_TRELLIS_FF_Q_14  (
    .CE(\acc_n0.w_N_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[14]),
    .LSR(1'h0),
    .Q(\acc_n0.w_N [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \acc_n0.w_N_TRELLIS_FF_Q_15  (
    .CE(\acc_n0.w_N_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[15]),
    .LSR(1'h0),
    .Q(\acc_n0.w_N [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \acc_n0.w_N_TRELLIS_FF_Q_2  (
    .CE(\acc_n0.w_N_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[10]),
    .LSR(1'h0),
    .Q(\acc_n0.w_N [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \acc_n0.w_N_TRELLIS_FF_Q_3  (
    .CE(\acc_n0.w_N_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[1]),
    .LSR(1'h0),
    .Q(\acc_n0.w_N [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \acc_n0.w_N_TRELLIS_FF_Q_4  (
    .CE(\acc_n0.w_N_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[9]),
    .LSR(1'h0),
    .Q(\acc_n0.w_N [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \acc_n0.w_N_TRELLIS_FF_Q_5  (
    .CE(\acc_n0.w_N_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[7]),
    .LSR(1'h0),
    .Q(\acc_n0.w_N [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \acc_n0.w_N_TRELLIS_FF_Q_6  (
    .CE(\acc_n0.w_N_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[4]),
    .LSR(1'h0),
    .Q(\acc_n0.w_N [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \acc_n0.w_N_TRELLIS_FF_Q_7  (
    .CE(\acc_n0.w_N_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[6]),
    .LSR(1'h0),
    .Q(\acc_n0.w_N [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \acc_n0.w_N_TRELLIS_FF_Q_8  (
    .CE(\acc_n0.w_N_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[3]),
    .LSR(1'h0),
    .Q(\acc_n0.w_N [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:8.5-15.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \acc_n0.w_N_TRELLIS_FF_Q_9  (
    .CE(\acc_n0.w_N_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[2]),
    .LSR(1'h0),
    .Q(\acc_n0.w_N [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'hfff0)
  ) \acc_n0.w_N_TRELLIS_FF_Q_CE_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(\control0.state_LUT4_D_Z [0]),
    .D(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Z(\acc_n0.w_N_TRELLIS_FF_Q_CE )
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_raiz.v:22.5-60.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q  (
    .CE(rst_LUT4_B_1_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [4]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_raiz.v:22.5-60.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q_1  (
    .CE(rst_LUT4_B_1_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [0]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_raiz.v:22.5-60.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q_2  (
    .CE(rst_LUT4_B_1_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [3]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_raiz.v:22.5-60.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q_3  (
    .CE(rst_LUT4_B_1_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [2]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_raiz.v:22.5-60.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q_4  (
    .CE(rst_LUT4_B_1_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [1]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_raiz.v:53.32-53.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \control0.cont_TRELLIS_FF_Q_DI_CCU2C_S0  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\control0.cont [4]),
    .B1(1'h0),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\control0.cont_TRELLIS_FF_Q_DI_CCU2C_S1_1_COUT ),
    .COUT(\control0.cont_TRELLIS_FF_Q_DI_CCU2C_S0_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\control0.cont_TRELLIS_FF_Q_DI [4]),
    .S1(\control0.cont_TRELLIS_FF_Q_DI_CCU2C_S0_S1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_raiz.v:53.32-53.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \control0.cont_TRELLIS_FF_Q_DI_CCU2C_S1  (
    .A0(1'h1),
    .A1(1'h0),
    .B0(\control0.cont [0]),
    .B1(\control0.cont [1]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(1'h0),
    .COUT(\control0.cont_TRELLIS_FF_Q_DI_CCU2C_S1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\control0.cont_TRELLIS_FF_Q_DI_CCU2C_S1_S0 ),
    .S1(\control0.cont_TRELLIS_FF_Q_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_raiz.v:53.32-53.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \control0.cont_TRELLIS_FF_Q_DI_CCU2C_S1_1  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\control0.cont [2]),
    .B1(\control0.cont [3]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\control0.cont_TRELLIS_FF_Q_DI_CCU2C_S1_COUT ),
    .COUT(\control0.cont_TRELLIS_FF_Q_DI_CCU2C_S1_1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\control0.cont_TRELLIS_FF_Q_DI [2]),
    .S1(\control0.cont_TRELLIS_FF_Q_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:114.33-115.56" */
  LUT4 #(
    .INIT(16'h00ff)
  ) \control0.cont_TRELLIS_FF_Q_DI_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\control0.cont [0]),
    .Z(\control0.cont_TRELLIS_FF_Q_DI [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h3000)
  ) \control0.state_LUT4_D  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.state_LUT4_D_Z [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_raiz.v:22.5-60.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.state_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\control0.state_TRELLIS_FF_Q_DI ),
    .LSR(rst_LUT4_B_Z),
    .Q(\control0.state [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_raiz.v:22.5-60.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.state_TRELLIS_FF_Q_1  (
    .CLK(clk),
    .DI(\control0.state_TRELLIS_FF_Q_1_DI ),
    .LSR(rst_LUT4_B_Z),
    .Q(\control0.state [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX \control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z  (
    .ALUT(\control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z_ALUT ),
    .BLUT(\control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z_BLUT ),
    .C0(init_LUT4_A_Z[4]),
    .Z(\control0.state_TRELLIS_FF_Q_1_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hfffc)
  ) \control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z_ALUT_LUT4_Z  (
    .A(1'h0),
    .B(\acc0.load_q ),
    .C(done_LUT4_D_1_Z[2]),
    .D(done_LUT4_D_1_Z[3]),
    .Z(\control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hfffe)
  ) \control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z_BLUT_LUT4_Z  (
    .A(init_LUT4_A_Z[0]),
    .B(\acc0.load_q ),
    .C(done_LUT4_D_1_Z[2]),
    .D(done_LUT4_D_1_Z[3]),
    .Z(\control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_raiz.v:22.5-60.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.state_TRELLIS_FF_Q_2  (
    .CLK(clk),
    .DI(\control0.state_TRELLIS_FF_Q_2_DI ),
    .LSR(rst_LUT4_B_Z),
    .Q(\control0.state [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hfefc)
  ) \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z  (
    .A(init_LUT4_A_Z[0]),
    .B(done_LUT4_D_1_Z_LUT4_Z_D[2]),
    .C(done_LUT4_D_1_Z[2]),
    .D(init_LUT4_A_Z[4]),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX \control0.state_TRELLIS_FF_Q_DI_PFUMX_Z  (
    .ALUT(\control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT ),
    .BLUT(\control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT ),
    .C0(init_LUT4_A_Z[4]),
    .Z(\control0.state_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hfffe)
  ) \control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT_LUT4_Z  (
    .A(init_LUT4_A_Z[0]),
    .B(init_LUT4_A_Z[1]),
    .C(\acc0.load_q ),
    .D(\control0.w_sh_r2 ),
    .Z(\control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_ALUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hfffc)
  ) \control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(init_LUT4_A_Z[1]),
    .C(\acc0.load_q ),
    .D(\control0.w_sh_r2 ),
    .Z(\control0.state_TRELLIS_FF_Q_DI_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h0c00)
  ) \control0.w_sh_r2_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.w_sh_r2 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h00f0)
  ) done_LUT4_D (
    .A(1'h0),
    .B(1'h0),
    .C(rst_LUT4_B_1_Z[0]),
    .D(done),
    .Z(done_LUT4_D_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h3f00)
  ) done_LUT4_D_1 (
    .A(1'h0),
    .B(\control0.cont [3]),
    .C(done_LUT4_D_1_C[1]),
    .D(done),
    .Z(done_LUT4_D_1_Z[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0008)
  ) done_LUT4_D_1_C_LUT4_Z (
    .A(\control0.cont [4]),
    .B(\control0.cont [2]),
    .C(\control0.cont [1]),
    .D(\control0.cont [0]),
    .Z(done_LUT4_D_1_C[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hc000)
  ) done_LUT4_D_1_Z_LUT4_Z (
    .A(1'h0),
    .B(done_LUT4_D_1_Z_LUT4_Z_D[0]),
    .C(done_LUT4_D_1_Z_LUT4_Z_D[1]),
    .D(done_LUT4_D_1_Z_LUT4_Z_D[2]),
    .Z(done_LUT4_D_1_Z[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) done_LUT4_D_1_Z_LUT4_Z_D_LUT4_Z (
    .A(\rsr0.z_Cont [14]),
    .B(\rsr0.z_Cont [12]),
    .C(\rsr0.z_Cont [10]),
    .D(\rsr0.z_Cont [8]),
    .Z(done_LUT4_D_1_Z_LUT4_Z_D[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h0300)
  ) done_LUT4_D_1_Z_LUT4_Z_D_LUT4_Z_1 (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(done_LUT4_D_1_Z_LUT4_Z_D[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) done_LUT4_D_1_Z_LUT4_Z_D_LUT4_Z_2 (
    .A(\rsr0.z_Cont [6]),
    .B(\rsr0.z_Cont [4]),
    .C(\rsr0.z_Cont [2]),
    .D(\rsr0.z_Cont [0]),
    .Z(done_LUT4_D_1_Z_LUT4_Z_D[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h00c0)
  ) done_LUT4_Z (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(done)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0002)
  ) init_LUT4_A (
    .A(init),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(init_LUT4_A_Z[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:12.30-12.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) init_LUT4_A_Z_CCU2C_COUT (
    .A0(\acc_n0.w_N [14]),
    .A1(\acc_n0.w_N [15]),
    .B0(init_LUT4_A_Z_CCU2C_COUT_B0),
    .B1(init_LUT4_A_Z_CCU2C_COUT_B1),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(init_LUT4_A_Z_CCU2C_COUT_CIN),
    .COUT(init_LUT4_A_Z[4]),
    .D0(1'h1),
    .D1(1'h1),
    .S0(init_LUT4_A_Z_CCU2C_COUT_S0[2]),
    .S1(init_LUT4_A_Z_CCU2C_COUT_S1[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "add_temp.v:5.19-5.29|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) init_LUT4_A_Z_CCU2C_COUT_B1_CCU2C_S1 (
    .A0(\rsr0.z_Cont [14]),
    .A1(1'h0),
    .B0(\acc0.Q [14]),
    .B1(\acc0.Q [15]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(init_LUT4_A_Z_CCU2C_COUT_B1_CCU2C_S1_CIN),
    .COUT(init_LUT4_A_Z_CCU2C_COUT_B1_CCU2C_S1_COUT),
    .D0(1'h1),
    .D1(1'h1),
    .S0(init_LUT4_A_Z_CCU2C_COUT_B0),
    .S1(init_LUT4_A_Z_CCU2C_COUT_B1)
  );
  /* module_not_derived = 32'd1 */
  /* src = "add_temp.v:5.19-5.29|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) init_LUT4_A_Z_CCU2C_COUT_B1_CCU2C_S1_CIN_CCU2C_COUT (
    .A0(\rsr0.z_Cont [12]),
    .A1(1'h0),
    .B0(\acc0.Q [12]),
    .B1(\acc0.Q [13]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(init_LUT4_A_Z_CCU2C_COUT_B1_CCU2C_S1_CIN_CCU2C_COUT_CIN),
    .COUT(init_LUT4_A_Z_CCU2C_COUT_B1_CCU2C_S1_CIN),
    .D0(1'h1),
    .D1(1'h1),
    .S0(init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_B0),
    .S1(init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_B1)
  );
  /* module_not_derived = 32'd1 */
  /* src = "add_temp.v:5.19-5.29|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) init_LUT4_A_Z_CCU2C_COUT_B1_CCU2C_S1_CIN_CCU2C_COUT_CIN_CCU2C_COUT (
    .A0(\rsr0.z_Cont [10]),
    .A1(1'h0),
    .B0(\acc0.Q [10]),
    .B1(\acc0.Q [11]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_9_D_CCU2C_S1_B1_CCU2C_S1_COUT),
    .COUT(init_LUT4_A_Z_CCU2C_COUT_B1_CCU2C_S1_CIN_CCU2C_COUT_CIN),
    .D0(1'h1),
    .D1(1'h1),
    .S0(init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_CIN_CCU2C_COUT_B0),
    .S1(init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_CIN_CCU2C_COUT_B1)
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:12.30-12.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT (
    .A0(\acc_n0.w_N [12]),
    .A1(\acc_n0.w_N [13]),
    .B0(init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_B0),
    .B1(init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_B1),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_CIN),
    .COUT(init_LUT4_A_Z_CCU2C_COUT_CIN),
    .D0(1'h1),
    .D1(1'h1),
    .S0(init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_S0[2]),
    .S1(init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_S1[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:12.30-12.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_CIN_CCU2C_COUT (
    .A0(\acc_n0.w_N [10]),
    .A1(\acc_n0.w_N [11]),
    .B0(init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_CIN_CCU2C_COUT_B0),
    .B1(init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_CIN_CCU2C_COUT_B1),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_9_D_CCU2C_S1_COUT),
    .COUT(init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_CIN),
    .D0(1'h1),
    .D1(1'h1),
    .S0(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_10_D[2]),
    .S1(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_11_D[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hcfc0)
  ) init_LUT4_A_Z_CCU2C_COUT_S0_LUT4_D (
    .A(1'h0),
    .B(in_N[14]),
    .C(init_LUT4_A_Z_LUT4_D_Z[2]),
    .D(init_LUT4_A_Z_CCU2C_COUT_S0[2]),
    .Z(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hcfc0)
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D (
    .A(1'h0),
    .B(in_N[15]),
    .C(init_LUT4_A_Z_LUT4_D_Z[2]),
    .D(init_LUT4_A_Z_CCU2C_COUT_S1[2]),
    .Z(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hcfc0)
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z (
    .A(1'h0),
    .B(in_N[0]),
    .C(init_LUT4_A_Z_LUT4_D_Z[2]),
    .D(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_D[2]),
    .Z(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hcfc0)
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_1 (
    .A(1'h0),
    .B(in_N[1]),
    .C(init_LUT4_A_Z_LUT4_D_Z[2]),
    .D(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_1_D[2]),
    .Z(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hcfc0)
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_10 (
    .A(1'h0),
    .B(in_N[10]),
    .C(init_LUT4_A_Z_LUT4_D_Z[2]),
    .D(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_10_D[2]),
    .Z(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hcfc0)
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_11 (
    .A(1'h0),
    .B(in_N[11]),
    .C(init_LUT4_A_Z_LUT4_D_Z[2]),
    .D(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_11_D[2]),
    .Z(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hcfc0)
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_12 (
    .A(1'h0),
    .B(in_N[12]),
    .C(init_LUT4_A_Z_LUT4_D_Z[2]),
    .D(init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_S0[2]),
    .Z(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hcfc0)
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_13 (
    .A(1'h0),
    .B(in_N[13]),
    .C(init_LUT4_A_Z_LUT4_D_Z[2]),
    .D(init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_S1[2]),
    .Z(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hcfc0)
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_2 (
    .A(1'h0),
    .B(in_N[2]),
    .C(init_LUT4_A_Z_LUT4_D_Z[2]),
    .D(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_2_D[2]),
    .Z(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hcfc0)
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_3 (
    .A(1'h0),
    .B(in_N[3]),
    .C(init_LUT4_A_Z_LUT4_D_Z[2]),
    .D(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_3_D[2]),
    .Z(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:12.30-12.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_3_D_CCU2C_S1 (
    .A0(\acc_n0.w_N [2]),
    .A1(\acc_n0.w_N [3]),
    .B0(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_3_D_CCU2C_S1_B0),
    .B1(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_3_D_CCU2C_S1_B1),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_D_CCU2C_S0_COUT),
    .COUT(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_3_D_CCU2C_S1_COUT),
    .D0(1'h1),
    .D1(1'h1),
    .S0(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_2_D[2]),
    .S1(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_3_D[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "add_temp.v:5.19-5.29|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_3_D_CCU2C_S1_B1_CCU2C_S1 (
    .A0(\rsr0.z_Cont [2]),
    .A1(1'h0),
    .B0(\acc0.Q [2]),
    .B1(\acc0.Q [3]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_D_CCU2C_S0_B1_CCU2C_S1_COUT),
    .COUT(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_3_D_CCU2C_S1_B1_CCU2C_S1_COUT),
    .D0(1'h1),
    .D1(1'h1),
    .S0(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_3_D_CCU2C_S1_B0),
    .S1(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_3_D_CCU2C_S1_B1)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hcfc0)
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_4 (
    .A(1'h0),
    .B(in_N[4]),
    .C(init_LUT4_A_Z_LUT4_D_Z[2]),
    .D(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_4_D[2]),
    .Z(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hcfc0)
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_5 (
    .A(1'h0),
    .B(in_N[5]),
    .C(init_LUT4_A_Z_LUT4_D_Z[2]),
    .D(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_5_D[2]),
    .Z(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:12.30-12.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_5_D_CCU2C_S1 (
    .A0(\acc_n0.w_N [4]),
    .A1(\acc_n0.w_N [5]),
    .B0(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_5_D_CCU2C_S1_B0),
    .B1(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_5_D_CCU2C_S1_B1),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_3_D_CCU2C_S1_COUT),
    .COUT(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_5_D_CCU2C_S1_COUT),
    .D0(1'h1),
    .D1(1'h1),
    .S0(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_4_D[2]),
    .S1(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_5_D[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "add_temp.v:5.19-5.29|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_5_D_CCU2C_S1_B1_CCU2C_S1 (
    .A0(\rsr0.z_Cont [4]),
    .A1(1'h0),
    .B0(\acc0.Q [4]),
    .B1(\acc0.Q [5]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_3_D_CCU2C_S1_B1_CCU2C_S1_COUT),
    .COUT(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_5_D_CCU2C_S1_B1_CCU2C_S1_COUT),
    .D0(1'h1),
    .D1(1'h1),
    .S0(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_5_D_CCU2C_S1_B0),
    .S1(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_5_D_CCU2C_S1_B1)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hcfc0)
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_6 (
    .A(1'h0),
    .B(in_N[6]),
    .C(init_LUT4_A_Z_LUT4_D_Z[2]),
    .D(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_6_D[2]),
    .Z(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hcfc0)
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_7 (
    .A(1'h0),
    .B(in_N[7]),
    .C(init_LUT4_A_Z_LUT4_D_Z[2]),
    .D(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_7_D[2]),
    .Z(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:12.30-12.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_7_D_CCU2C_S1 (
    .A0(\acc_n0.w_N [6]),
    .A1(\acc_n0.w_N [7]),
    .B0(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_7_D_CCU2C_S1_B0),
    .B1(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_7_D_CCU2C_S1_B1),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_5_D_CCU2C_S1_COUT),
    .COUT(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_7_D_CCU2C_S1_COUT),
    .D0(1'h1),
    .D1(1'h1),
    .S0(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_6_D[2]),
    .S1(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_7_D[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "add_temp.v:5.19-5.29|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_7_D_CCU2C_S1_B1_CCU2C_S1 (
    .A0(\rsr0.z_Cont [6]),
    .A1(1'h0),
    .B0(\acc0.Q [6]),
    .B1(\acc0.Q [7]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_5_D_CCU2C_S1_B1_CCU2C_S1_COUT),
    .COUT(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_7_D_CCU2C_S1_B1_CCU2C_S1_COUT),
    .D0(1'h1),
    .D1(1'h1),
    .S0(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_7_D_CCU2C_S1_B0),
    .S1(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_7_D_CCU2C_S1_B1)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hcfc0)
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_8 (
    .A(1'h0),
    .B(in_N[8]),
    .C(init_LUT4_A_Z_LUT4_D_Z[2]),
    .D(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_8_D[2]),
    .Z(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hcfc0)
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_9 (
    .A(1'h0),
    .B(in_N[9]),
    .C(init_LUT4_A_Z_LUT4_D_Z[2]),
    .D(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_9_D[2]),
    .Z(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z[9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:12.30-12.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_9_D_CCU2C_S1 (
    .A0(\acc_n0.w_N [8]),
    .A1(\acc_n0.w_N [9]),
    .B0(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_9_D_CCU2C_S1_B0),
    .B1(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_9_D_CCU2C_S1_B1),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_7_D_CCU2C_S1_COUT),
    .COUT(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_9_D_CCU2C_S1_COUT),
    .D0(1'h1),
    .D1(1'h1),
    .S0(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_8_D[2]),
    .S1(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_9_D[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "add_temp.v:5.19-5.29|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_9_D_CCU2C_S1_B1_CCU2C_S1 (
    .A0(\rsr0.z_Cont [8]),
    .A1(1'h0),
    .B0(\acc0.Q [8]),
    .B1(\acc0.Q [9]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_7_D_CCU2C_S1_B1_CCU2C_S1_COUT),
    .COUT(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_9_D_CCU2C_S1_B1_CCU2C_S1_COUT),
    .D0(1'h1),
    .D1(1'h1),
    .S0(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_9_D_CCU2C_S1_B0),
    .S1(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_9_D_CCU2C_S1_B1)
  );
  /* module_not_derived = 32'd1 */
  /* src = "acc_n.v:12.30-12.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_D_CCU2C_S0 (
    .A0(\acc_n0.w_N [0]),
    .A1(\acc_n0.w_N [1]),
    .B0(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_D_CCU2C_S0_B0),
    .B1(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_D_CCU2C_S0_B1),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(1'h1),
    .COUT(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_D_CCU2C_S0_COUT),
    .D0(1'h1),
    .D1(1'h1),
    .S0(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_D[2]),
    .S1(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_1_D[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "add_temp.v:5.19-5.29|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_D_CCU2C_S0_B1_CCU2C_S1 (
    .A0(\rsr0.z_Cont [0]),
    .A1(1'h0),
    .B0(\acc0.Q [0]),
    .B1(\acc0.Q [1]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(1'h0),
    .COUT(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_D_CCU2C_S0_B1_CCU2C_S1_COUT),
    .D0(1'h1),
    .D1(1'h1),
    .S0(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_D_CCU2C_S0_B0),
    .S1(init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_D_CCU2C_S0_B1)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0085)
  ) init_LUT4_A_Z_LUT4_D (
    .A(\control0.state [2]),
    .B(\control0.state [1]),
    .C(\control0.state [0]),
    .D(init_LUT4_A_Z[0]),
    .Z(init_LUT4_A_Z_LUT4_D_Z[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h0030)
  ) init_LUT4_A_Z_LUT4_Z (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(init_LUT4_A_Z[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr_cont.v:7.5-14.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:16.100-16.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \rsr0.z_Cont_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\rsr0.z_Cont_TRELLIS_FF_Q_DI ),
    .LSR(1'h0),
    .Q(\rsr0.z_Cont [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr_cont.v:7.5-14.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rsr0.z_Cont_TRELLIS_FF_Q_1  (
    .CE(\control0.w_sh_r2 ),
    .CLK(clk),
    .DI(\rsr0.z_Cont [2]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\rsr0.z_Cont [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr_cont.v:7.5-14.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rsr0.z_Cont_TRELLIS_FF_Q_2  (
    .CE(\control0.w_sh_r2 ),
    .CLK(clk),
    .DI(\rsr0.z_Cont [4]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\rsr0.z_Cont [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr_cont.v:7.5-14.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rsr0.z_Cont_TRELLIS_FF_Q_3  (
    .CE(\control0.w_sh_r2 ),
    .CLK(clk),
    .DI(\rsr0.z_Cont [8]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\rsr0.z_Cont [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr_cont.v:7.5-14.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rsr0.z_Cont_TRELLIS_FF_Q_4  (
    .CE(\control0.w_sh_r2 ),
    .CLK(clk),
    .DI(\rsr0.z_Cont [6]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\rsr0.z_Cont [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr_cont.v:7.5-14.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rsr0.z_Cont_TRELLIS_FF_Q_5  (
    .CE(\control0.w_sh_r2 ),
    .CLK(clk),
    .DI(\rsr0.z_Cont [14]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\rsr0.z_Cont [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr_cont.v:7.5-14.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rsr0.z_Cont_TRELLIS_FF_Q_6  (
    .CE(\control0.w_sh_r2 ),
    .CLK(clk),
    .DI(\rsr0.z_Cont [12]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\rsr0.z_Cont [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "rsr_cont.v:7.5-14.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \rsr0.z_Cont_TRELLIS_FF_Q_7  (
    .CE(\control0.w_sh_r2 ),
    .CLK(clk),
    .DI(\rsr0.z_Cont [10]),
    .LSR(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Q(\rsr0.z_Cont [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hff0c)
  ) \rsr0.z_Cont_TRELLIS_FF_Q_DI_LUT4_Z  (
    .A(1'h0),
    .B(\rsr0.z_Cont [14]),
    .C(\control0.w_sh_r2 ),
    .D(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Z(\rsr0.z_Cont_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hfccc)
  ) rst_LUT4_B (
    .A(1'h0),
    .B(rst),
    .C(\control0.state [1]),
    .D(init_LUT4_A_Z_LUT4_D_Z[2]),
    .Z(rst_LUT4_B_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h3330)
  ) rst_LUT4_B_1 (
    .A(1'h0),
    .B(rst),
    .C(init_LUT4_A_Z[1]),
    .D(done_LUT4_D_1_Z[2]),
    .Z(rst_LUT4_B_1_Z[0])
  );
  assign { done_LUT4_D_1_Z[4], done_LUT4_D_1_Z[1:0] } = { init_LUT4_A_Z[4], \acc0.load_q , init_LUT4_A_Z[0] };
  assign init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_7_D[1:0] = { init_LUT4_A_Z_LUT4_D_Z[2], in_N[7] };
  assign init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_2_D[1:0] = { init_LUT4_A_Z_LUT4_D_Z[2], in_N[2] };
  assign \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_8_D [1:0] = { \control0.state_LUT4_D_Z [0], \acc0.Q [8] };
  assign { done_LUT4_D_1_C[2], done_LUT4_D_1_C[0] } = { done, \control0.cont [3] };
  assign init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_8_D[1:0] = { init_LUT4_A_Z_LUT4_D_Z[2], in_N[8] };
  assign \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_9_D [1:0] = { \control0.state_LUT4_D_Z [0], \acc0.Q [9] };
  assign \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_3_D [1:0] = { \control0.state_LUT4_D_Z [0], \acc0.Q [3] };
  assign init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_9_D[1:0] = { init_LUT4_A_Z_LUT4_D_Z[2], in_N[9] };
  assign \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_10_D [1:0] = { \control0.state_LUT4_D_Z [0], \acc0.Q [10] };
  assign init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_3_D[1:0] = { init_LUT4_A_Z_LUT4_D_Z[2], in_N[3] };
  assign \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_11_D [1:0] = { \control0.state_LUT4_D_Z [0], \acc0.Q [11] };
  assign init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_10_D[1:0] = { init_LUT4_A_Z_LUT4_D_Z[2], in_N[10] };
  assign \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_4_D [1:0] = { \control0.state_LUT4_D_Z [0], \acc0.Q [4] };
  assign \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_12_D [1:0] = { \control0.state_LUT4_D_Z [0], \acc0.Q [12] };
  assign init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_11_D[1:0] = { init_LUT4_A_Z_LUT4_D_Z[2], in_N[11] };
  assign \control0.state_LUT4_D_Z [1] = init_LUT4_A_Z_LUT4_D_Z[2];
  assign \acc0.z_Cont  = { 1'h0, \rsr0.z_Cont [14], 1'h0, \rsr0.z_Cont [12], 1'h0, \rsr0.z_Cont [10], 1'h0, \rsr0.z_Cont [8], 1'h0, \rsr0.z_Cont [6], 1'h0, \rsr0.z_Cont [4], 1'h0, \rsr0.z_Cont [2], 1'h0, \rsr0.z_Cont [0] };
  assign \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_13_D [1:0] = { \control0.state_LUT4_D_Z [0], \acc0.Q [13] };
  assign \control0.clk  = clk;
  assign init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_4_D[1:0] = { init_LUT4_A_Z_LUT4_D_Z[2], in_N[4] };
  assign init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_S0[1:0] = { init_LUT4_A_Z_LUT4_D_Z[2], in_N[12] };
  assign \acc_n0.in_N  = in_N;
  assign \acc_n0.clk  = clk;
  assign init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_D[1:0] = { init_LUT4_A_Z_LUT4_D_Z[2], in_N[0] };
  assign \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_14_D [1:0] = { \control0.state_LUT4_D_Z [0], \acc0.Q [14] };
  assign \control0.rst  = rst;
  assign \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_5_D [1:0] = { \control0.state_LUT4_D_Z [0], \acc0.Q [5] };
  assign \add0.z_Cont  = { 1'h0, \rsr0.z_Cont [14], 1'h0, \rsr0.z_Cont [12], 1'h0, \rsr0.z_Cont [10], 1'h0, \rsr0.z_Cont [8], 1'h0, \rsr0.z_Cont [6], 1'h0, \rsr0.z_Cont [4], 1'h0, \rsr0.z_Cont [2], 1'h0, \rsr0.z_Cont [0] };
  assign \rsr0.clk  = clk;
  assign init_LUT4_A_Z_CCU2C_COUT_CIN_CCU2C_COUT_S1[1:0] = { init_LUT4_A_Z_LUT4_D_Z[2], in_N[13] };
  assign \add0.Q  = \acc0.Q ;
  assign \control0.init  = init;
  assign init_LUT4_A_Z_LUT4_D_Z[1:0] = { \control0.w_sh_r2 , \rsr0.z_Cont [14] };
  assign init_LUT4_A_Z_CCU2C_COUT_S0[1:0] = { init_LUT4_A_Z_LUT4_D_Z[2], in_N[14] };
  assign \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_D [1:0] = { \control0.state_LUT4_D_Z [0], \acc0.Q [15] };
  assign \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_6_D [1:0] = { \control0.state_LUT4_D_Z [0], \acc0.Q [6] };
  assign init_LUT4_A_Z_CCU2C_COUT_S1[1:0] = { init_LUT4_A_Z_LUT4_D_Z[2], in_N[15] };
  assign init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_1_D[1:0] = { init_LUT4_A_Z_LUT4_D_Z[2], in_N[1] };
  assign init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_5_D[1:0] = { init_LUT4_A_Z_LUT4_D_Z[2], in_N[5] };
  assign init_LUT4_A_Z[3:2] = { \control0.w_sh_r2 , \acc0.load_q  };
  assign \comp_x0.w_N  = \acc_n0.w_N ;
  assign \control0.done  = done;
  assign \control0.w_load_q  = \acc0.load_q ;
  assign rst_LUT4_B_1_Z[1] = done;
  assign { \rsr0.z_Cont [15], \rsr0.z_Cont [13], \rsr0.z_Cont [11], \rsr0.z_Cont [9], \rsr0.z_Cont [7], \rsr0.z_Cont [5], \rsr0.z_Cont [3], \rsr0.z_Cont [1] } = 8'h00;
  assign \acc0.clk  = clk;
  assign init_LUT4_A_Z_CCU2C_COUT_S1_LUT4_D_Z_LUT4_Z_6_D[1:0] = { init_LUT4_A_Z_LUT4_D_Z[2], in_N[6] };
  assign \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_15_D [0] = \control0.state_LUT4_D_Z [0];
  assign { \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_2_C [2], \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_2_C [0] } = { \control0.state_LUT4_D_Z [0], \acc0.Q [2] };
  assign \comp_y0.z_Cont  = { 1'h0, \rsr0.z_Cont [14], 1'h0, \rsr0.z_Cont [12], 1'h0, \rsr0.z_Cont [10], 1'h0, \rsr0.z_Cont [8], 1'h0, \rsr0.z_Cont [6], 1'h0, \rsr0.z_Cont [4], 1'h0, \rsr0.z_Cont [2], 1'h0, \rsr0.z_Cont [0] };
  assign Q = \acc0.Q ;
  assign w_N = \acc_n0.w_N ;
  assign z_Cont = { \rsr0.z_Cont [14], 1'h0, \rsr0.z_Cont [12], 1'h0, \rsr0.z_Cont [10], 1'h0, \rsr0.z_Cont [8], 1'h0, \rsr0.z_Cont [6], 1'h0, \rsr0.z_Cont [4], 1'h0, \rsr0.z_Cont [2], 1'h0, \rsr0.z_Cont [0] };
  assign \acc0.Q_TRELLIS_FF_Q_DI_LUT4_Z_7_D [1:0] = { \control0.state_LUT4_D_Z [0], \acc0.Q [7] };
  assign w_load_q = \acc0.load_q ;
  assign w_sh_r2 = \control0.w_sh_r2 ;
  assign \rsr0.shift  = \control0.w_sh_r2 ;
  assign N_out = \acc_n0.w_N ;
  assign Q_out = \acc0.Q ;
endmodule
