/* Generated by Yosys 0.65+57 (git sha1 9d0cdb855, clang++ 18.1.8 -fPIC -O3) */

/* hdlname = "bin_to_bcd_16" */
/* top =  1  */
/* src = "bin_to_bcd_16.v:1.1-28.10" */
module bin_to_bcd_16(clk, rst, init, A, BCD_out, done);
  /* src = "bin_to_bcd_16.v:2.11-2.14" */
  input clk;
  wire clk;
  /* src = "bin_to_bcd_16.v:2.16-2.19" */
  input rst;
  wire rst;
  /* src = "bin_to_bcd_16.v:2.21-2.25" */
  input init;
  wire init;
  /* src = "bin_to_bcd_16.v:3.18-3.19" */
  input [15:0] A;
  wire [15:0] A;
  /* src = "bin_to_bcd_16.v:4.19-4.26" */
  output [15:0] BCD_out;
  wire [15:0] BCD_out;
  /* src = "bin_to_bcd_16.v:5.12-5.16" */
  output done;
  wire done;
  wire [15:1] A_LUT4_B_Z;
  /* hdlname = "acc0 in_bcd" */
  /* src = "acc_bcd_adjust.v:2.18-2.24" */
  wire [15:0] \acc0.in_bcd ;
  /* hdlname = "comp_z0 val" */
  /* src = "comp_z.v:2.17-2.20" */
  wire [4:0] \comp_z0.val ;
  /* hdlname = "control0 clk" */
  /* src = "control_bcd.v:2.11-2.14" */
  wire \control0.clk ;
  /* hdlname = "control0 cont" */
  /* src = "control_bcd.v:12.15-12.19" */
  wire [4:0] \control0.cont ;
  /* abc9_carry = 32'd1 */
  /* src = "control_bcd.v:42.32-42.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  /* unused_bits = "0" */
  wire \control0.cont_CCU2C_B0_COUT ;
  /* unused_bits = "0" */
  wire \control0.cont_CCU2C_B0_S1 ;
  /* abc9_carry = 32'd1 */
  /* src = "control_bcd.v:42.32-42.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \control0.cont_CCU2C_B1_1_COUT ;
  /* unused_bits = "0" */
  wire \control0.cont_CCU2C_B1_1_S0 ;
  /* abc9_carry = 32'd1 */
  /* src = "control_bcd.v:42.32-42.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \control0.cont_CCU2C_B1_COUT ;
  /* force_downto = 32'd1 */
  /* src = "control_bcd.v:42.32-42.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:34.26-34.27" */
  wire [4:0] \control0.cont_TRELLIS_FF_Q_DI ;
  /* hdlname = "control0 done" */
  /* src = "control_bcd.v:3.16-3.20" */
  wire \control0.done ;
  /* hdlname = "control0 init" */
  /* src = "control_bcd.v:2.21-2.25" */
  wire \control0.init ;
  /* hdlname = "control0 rst" */
  /* src = "control_bcd.v:2.16-2.19" */
  wire \control0.rst ;
  /* hdlname = "control0 state" */
  /* src = "control_bcd.v:11.15-11.20" */
  wire [2:0] \control0.state ;
  wire \control0.state_TRELLIS_FF_Q_1_DI ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire \control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z_BLUT ;
  wire \control0.state_TRELLIS_FF_Q_2_DI ;
  wire \control0.state_TRELLIS_FF_Q_DI ;
  /* hdlname = "control0 w_sh_l" */
  /* src = "control_bcd.v:3.22-3.28" */
  wire \control0.w_sh_l ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [0:0] \control0.w_sh_l_LUT4_Z_D ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [2:0] \control0.w_sh_l_LUT4_Z_D_LUT4_D_Z ;
  /* hdlname = "count0 clk" */
  /* src = "contador_desc.v:2.11-2.14" */
  wire \count0.clk ;
  /* hdlname = "count0 dec" */
  /* src = "contador_desc.v:2.22-2.25" */
  wire \count0.dec ;
  /* hdlname = "count0 val" */
  /* src = "contador_desc.v:3.22-3.25" */
  wire [4:0] \count0.val ;
  wire \count0.val_TRELLIS_FF_Q_4_DI ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [3:0] \count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D ;
  /* abc9_carry = 32'd1 */
  /* src = "contador_desc.v:10.19-10.26|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_CIN ;
  /* force_downto = 32'd1 */
  /* src = "contador_desc.v:10.19-10.26|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:34.26-34.27" */
  /* unused_bits = "4" */
  wire [4:0] \count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1 ;
  /* abc9_carry = 32'd1 */
  /* src = "contador_desc.v:10.19-10.26|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  wire \count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1_CCU2C_S1_COUT ;
  /* unused_bits = "0" */
  wire \count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1_CCU2C_S1_S0 ;
  /* abc9_carry = 32'd1 */
  /* src = "contador_desc.v:10.19-10.26|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/ccu2c_sim.vh:9.9-9.13" */
  /* unused_bits = "0" */
  wire \count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_COUT ;
  /* unused_bits = "0" */
  wire \count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_S1 ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [3:0] done_LUT4_C_B;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.66-157.68" */
  wire done_LUT4_C_B_L6MUX21_Z_D0;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.50-157.52" */
  wire done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D0;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.22-157.24" */
  wire done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_ALUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.18-157.20" */
  wire done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_BLUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.54-157.56" */
  wire done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D1;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.30-157.32" */
  wire done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_ALUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.26-157.28" */
  wire done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_BLUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.70-157.72" */
  wire done_LUT4_C_B_L6MUX21_Z_D1;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.58-157.60" */
  wire done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D0;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.38-157.40" */
  wire done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_ALUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.34-157.36" */
  wire done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_BLUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.62-157.64" */
  wire done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D1;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.46-157.48" */
  wire done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_ALUT;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:157.42-157.44" */
  wire done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_BLUT;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [6:0] done_LUT4_C_B_L6MUX21_Z_SD;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [3:0] done_LUT4_C_D;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [1:0] done_LUT4_C_Z;
  wire done_LUT4_D_Z;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire init_LUT4_A_1_Z;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire init_LUT4_A_Z;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire init_LUT4_A_Z_PFUMX_BLUT_ALUT;
  /* hdlname = "lcr0 clk" */
  /* src = "lcr_32.v:2.11-2.14" */
  wire \lcr0.clk ;
  /* hdlname = "lcr0 in_A" */
  /* src = "lcr_32.v:3.18-3.22" */
  wire [31:0] \lcr0.in_A ;
  /* hdlname = "lcr0 s_out" */
  /* src = "lcr_32.v:5.23-5.28" */
  wire [31:0] \lcr0.s_out ;
  wire \lcr0.s_out_TRELLIS_FF_Q_14_LSR ;
  wire \lcr0.s_out_TRELLIS_FF_Q_15_CE ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [3:0] \lcr0.s_out_TRELLIS_FF_Q_15_CE_LUT4_Z_C ;
  wire \lcr0.s_out_TRELLIS_FF_Q_25_CE ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [3:0] \lcr0.s_out_TRELLIS_FF_Q_25_CE_LUT4_Z_C ;
  wire \lcr0.s_out_TRELLIS_FF_Q_27_CE ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [3:0] \lcr0.s_out_TRELLIS_FF_Q_27_CE_LUT4_Z_C ;
  wire \lcr0.s_out_TRELLIS_FF_Q_5_CE ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [3:0] \lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C ;
  wire [31:16] \lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z ;
  wire \lcr0.s_out_TRELLIS_FF_Q_CE ;
  /* force_downto = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:108.23-108.24" */
  wire [3:0] \lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D ;
  /* hdlname = "lcr0 shift" */
  /* src = "lcr_32.v:2.16-2.21" */
  wire \lcr0.shift ;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.22-133.24" */
  wire rst_LUT4_A_Z;
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:133.18-133.20" */
  wire rst_LUT4_D_Z;
  wire rst_LUT4_D_Z_PFUMX_BLUT_Z;
  /* src = "bin_to_bcd_16.v:10.17-10.27" */
  wire [15:0] w_BCD_part;
  /* src = "bin_to_bcd_16.v:9.17-9.27" */
  wire [31:0] w_combined;
  /* src = "bin_to_bcd_16.v:7.10-7.16" */
  wire w_sh_l;
  /* src = "bin_to_bcd_16.v:12.16-12.21" */
  wire [4:0] w_val;
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B (
    .A(1'h0),
    .B(A[5]),
    .C(\lcr0.s_out [4]),
    .D(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Z(A_LUT4_B_Z[5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_1 (
    .A(1'h0),
    .B(A[3]),
    .C(\lcr0.s_out [2]),
    .D(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Z(A_LUT4_B_Z[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_10 (
    .A(1'h0),
    .B(A[12]),
    .C(\lcr0.s_out [11]),
    .D(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Z(A_LUT4_B_Z[12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_11 (
    .A(1'h0),
    .B(A[9]),
    .C(\lcr0.s_out [8]),
    .D(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Z(A_LUT4_B_Z[9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_12 (
    .A(1'h0),
    .B(A[15]),
    .C(\lcr0.s_out [14]),
    .D(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Z(A_LUT4_B_Z[15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_13 (
    .A(1'h0),
    .B(A[10]),
    .C(\lcr0.s_out [9]),
    .D(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Z(A_LUT4_B_Z[10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_14 (
    .A(1'h0),
    .B(A[7]),
    .C(\lcr0.s_out [6]),
    .D(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Z(A_LUT4_B_Z[7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_2 (
    .A(1'h0),
    .B(A[14]),
    .C(\lcr0.s_out [13]),
    .D(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Z(A_LUT4_B_Z[14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_3 (
    .A(1'h0),
    .B(A[13]),
    .C(\lcr0.s_out [12]),
    .D(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Z(A_LUT4_B_Z[13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_4 (
    .A(1'h0),
    .B(A[1]),
    .C(\lcr0.s_out [0]),
    .D(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Z(A_LUT4_B_Z[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_5 (
    .A(1'h0),
    .B(A[6]),
    .C(\lcr0.s_out [5]),
    .D(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Z(A_LUT4_B_Z[6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_6 (
    .A(1'h0),
    .B(A[8]),
    .C(\lcr0.s_out [7]),
    .D(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Z(A_LUT4_B_Z[8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_7 (
    .A(1'h0),
    .B(A[2]),
    .C(\lcr0.s_out [1]),
    .D(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Z(A_LUT4_B_Z[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_8 (
    .A(1'h0),
    .B(A[4]),
    .C(\lcr0.s_out [3]),
    .D(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Z(A_LUT4_B_Z[4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccf0)
  ) A_LUT4_B_9 (
    .A(1'h0),
    .B(A[11]),
    .C(\lcr0.s_out [10]),
    .D(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Z(A_LUT4_B_Z[11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd.v:42.32-42.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \control0.cont_CCU2C_B0  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\control0.cont [4]),
    .B1(1'h0),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\control0.cont_CCU2C_B1_COUT ),
    .COUT(\control0.cont_CCU2C_B0_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\control0.cont_TRELLIS_FF_Q_DI [4]),
    .S1(\control0.cont_CCU2C_B0_S1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd.v:42.32-42.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \control0.cont_CCU2C_B1  (
    .A0(1'h0),
    .A1(1'h0),
    .B0(\control0.cont [2]),
    .B1(\control0.cont [3]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(\control0.cont_CCU2C_B1_1_COUT ),
    .COUT(\control0.cont_CCU2C_B1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\control0.cont_TRELLIS_FF_Q_DI [2]),
    .S1(\control0.cont_TRELLIS_FF_Q_DI [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd.v:42.32-42.40|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \control0.cont_CCU2C_B1_1  (
    .A0(1'h1),
    .A1(1'h0),
    .B0(\control0.cont [0]),
    .B1(\control0.cont [1]),
    .C0(1'h0),
    .C1(1'h0),
    .CIN(1'h0),
    .COUT(\control0.cont_CCU2C_B1_1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\control0.cont_CCU2C_B1_1_S0 ),
    .S1(\control0.cont_TRELLIS_FF_Q_DI [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:114.33-115.56" */
  LUT4 #(
    .INIT(16'h00ff)
  ) \control0.cont_LUT4_D  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\control0.cont [0]),
    .Z(\control0.cont_TRELLIS_FF_Q_DI [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd.v:18.5-49.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q  (
    .CE(done_LUT4_C_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [1]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd.v:18.5-49.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q_1  (
    .CE(done_LUT4_C_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [4]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd.v:18.5-49.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q_2  (
    .CE(done_LUT4_C_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [3]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd.v:18.5-49.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q_3  (
    .CE(done_LUT4_C_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [2]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd.v:18.5-49.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.cont_TRELLIS_FF_Q_4  (
    .CE(done_LUT4_C_Z[0]),
    .CLK(clk),
    .DI(\control0.cont_TRELLIS_FF_Q_DI [0]),
    .LSR(done_LUT4_D_Z),
    .Q(\control0.cont [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd.v:18.5-49.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.state_TRELLIS_FF_Q  (
    .CLK(clk),
    .DI(\control0.state_TRELLIS_FF_Q_DI ),
    .LSR(rst_LUT4_D_Z_PFUMX_BLUT_Z),
    .Q(\control0.state [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd.v:18.5-49.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.state_TRELLIS_FF_Q_1  (
    .CLK(clk),
    .DI(\control0.state_TRELLIS_FF_Q_1_DI ),
    .LSR(rst_LUT4_D_Z_PFUMX_BLUT_Z),
    .Q(\control0.state [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX \control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z  (
    .ALUT(init_LUT4_A_1_Z),
    .BLUT(\control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z_BLUT ),
    .C0(\control0.w_sh_l_LUT4_Z_D ),
    .Z(\control0.state_TRELLIS_FF_Q_1_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hffff)
  ) \control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z_BLUT_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(\control0.state_TRELLIS_FF_Q_1_DI_PFUMX_Z_BLUT )
  );
  /* module_not_derived = 32'd1 */
  /* src = "control_bcd.v:18.5-49.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:68.164-68.215" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \control0.state_TRELLIS_FF_Q_2  (
    .CLK(clk),
    .DI(\control0.state_TRELLIS_FF_Q_2_DI ),
    .LSR(rst_LUT4_D_Z_PFUMX_BLUT_Z),
    .Q(\control0.state [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h0130)
  ) \control0.state_TRELLIS_FF_Q_2_DI_LUT4_Z  (
    .A(done_LUT4_C_B[3]),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.state_TRELLIS_FF_Q_2_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:114.33-115.56" */
  LUT4 #(
    .INIT(16'h00ff)
  ) \control0.w_sh_l_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\control0.w_sh_l_LUT4_Z_D ),
    .Z(\control0.w_sh_l )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'he900)
  ) \control0.w_sh_l_LUT4_Z_D_LUT4_D  (
    .A(\control0.state [2]),
    .B(\control0.state [1]),
    .C(\control0.state [0]),
    .D(\control0.w_sh_l_LUT4_Z_D ),
    .Z(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hcfff)
  ) \control0.w_sh_l_LUT4_Z_D_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\control0.w_sh_l_LUT4_Z_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "contador_desc.v:6.5-11.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \count0.val_TRELLIS_FF_Q  (
    .CE(\control0.w_sh_l ),
    .CLK(clk),
    .DI(\count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1 [0]),
    .LSR(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Q(\count0.val [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "contador_desc.v:6.5-11.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \count0.val_TRELLIS_FF_Q_1  (
    .CE(\control0.w_sh_l ),
    .CLK(clk),
    .DI(\count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1 [3]),
    .LSR(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Q(\count0.val [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "contador_desc.v:6.5-11.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \count0.val_TRELLIS_FF_Q_2  (
    .CE(\control0.w_sh_l ),
    .CLK(clk),
    .DI(\count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1 [2]),
    .LSR(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Q(\count0.val [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "contador_desc.v:6.5-11.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \count0.val_TRELLIS_FF_Q_3  (
    .CE(\control0.w_sh_l ),
    .CLK(clk),
    .DI(\count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1 [1]),
    .LSR(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Q(\count0.val [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "contador_desc.v:6.5-11.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:16.100-16.154" */
  TRELLIS_FF #(
    .CEMUX("1"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \count0.val_TRELLIS_FF_Q_4  (
    .CLK(clk),
    .DI(\count0.val_TRELLIS_FF_Q_4_DI ),
    .LSR(1'h0),
    .Q(\count0.val [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hfbc8)
  ) \count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z  (
    .A(\count0.val [4]),
    .B(\control0.w_sh_l_LUT4_Z_D ),
    .C(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .D(\count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D [3]),
    .Z(\count0.val_TRELLIS_FF_Q_4_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "contador_desc.v:10.19-10.26|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0  (
    .A0(\count0.val [4]),
    .A1(1'h0),
    .B0(1'h0),
    .B1(1'h0),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(\count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_CIN ),
    .COUT(\count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D [3]),
    .S1(\count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_S1 )
  );
  /* module_not_derived = 32'd1 */
  /* src = "contador_desc.v:10.19-10.26|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT  (
    .A0(\count0.val [2]),
    .A1(\count0.val [3]),
    .B0(1'h0),
    .B1(1'h0),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(\count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1_CCU2C_S1_COUT ),
    .COUT(\count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_CIN ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1 [2]),
    .S1(\count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1 [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "contador_desc.v:10.19-10.26|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/arith_map_ccu2c.v:74.7-80.4" */
  CCU2C #(
    .INIT0(16'h96aa),
    .INIT1(16'h96aa),
    .INJECT1_0("NO"),
    .INJECT1_1("NO")
  ) \count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1_CCU2C_S1  (
    .A0(\count0.val [0]),
    .A1(\count0.val [1]),
    .B0(1'h1),
    .B1(1'h0),
    .C0(1'h1),
    .C1(1'h1),
    .CIN(1'h1),
    .COUT(\count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1_CCU2C_S1_COUT ),
    .D0(1'h1),
    .D1(1'h1),
    .S0(\count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1_CCU2C_S1_S0 ),
    .S1(\count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1 [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:114.33-115.56" */
  LUT4 #(
    .INIT(16'h00ff)
  ) \count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(\count0.val [0]),
    .Z(\count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D_CCU2C_S0_CIN_CCU2C_COUT_S1 [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h7f00)
  ) done_LUT4_C (
    .A(done_LUT4_C_B[0]),
    .B(done_LUT4_C_B[1]),
    .C(done),
    .D(done_LUT4_C_D[3]),
    .Z(done_LUT4_C_Z[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hff70)
  ) done_LUT4_C_1 (
    .A(done_LUT4_C_B[0]),
    .B(done_LUT4_C_B[1]),
    .C(done),
    .D(done_LUT4_C_B[3]),
    .Z(\control0.state_TRELLIS_FF_Q_DI )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:184.21-184.63" */
  L6MUX21 done_LUT4_C_B_L6MUX21_Z (
    .D0(done_LUT4_C_B_L6MUX21_Z_D0),
    .D1(done_LUT4_C_B_L6MUX21_Z_D1),
    .SD(done_LUT4_C_B_L6MUX21_Z_SD[6]),
    .Z(done_LUT4_C_B[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:182.21-182.64" */
  L6MUX21 done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z (
    .D0(done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D0),
    .D1(done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D1),
    .SD(\control0.state [0]),
    .Z(done_LUT4_C_B_L6MUX21_Z_D0)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:178.19-178.65" */
  PFUMX done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z (
    .ALUT(done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_ALUT),
    .BLUT(done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_BLUT),
    .C0(\control0.state [1]),
    .Z(done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D0)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:160.39-161.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_ALUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:158.39-159.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_BLUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D0_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:179.19-179.65" */
  PFUMX done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z (
    .ALUT(done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_ALUT),
    .BLUT(done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_BLUT),
    .C0(\control0.state [1]),
    .Z(done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D1)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:165.39-166.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_ALUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:163.39-164.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_BLUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(done_LUT4_C_B_L6MUX21_Z_D0_L6MUX21_Z_D1_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:183.21-183.64" */
  L6MUX21 done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z (
    .D0(done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D0),
    .D1(done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D1),
    .SD(\control0.state [0]),
    .Z(done_LUT4_C_B_L6MUX21_Z_D1)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:180.19-180.65" */
  PFUMX done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z (
    .ALUT(done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_ALUT),
    .BLUT(done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_BLUT),
    .C0(\control0.state [1]),
    .Z(done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D0)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:170.39-171.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_ALUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:168.39-169.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_BLUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D0_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:181.19-181.65" */
  PFUMX done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z (
    .ALUT(done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_ALUT),
    .BLUT(done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_BLUT),
    .C0(\control0.state [1]),
    .Z(done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D1)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:175.41-176.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_ALUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:173.41-174.56" */
  LUT4 #(
    .INIT(16'h0001)
  ) done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_BLUT_LUT4_Z (
    .A(\count0.val [4]),
    .B(\count0.val [3]),
    .C(\count0.val [2]),
    .D(\control0.state [2]),
    .Z(done_LUT4_C_B_L6MUX21_Z_D1_L6MUX21_Z_D1_PFUMX_Z_BLUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h000f)
  ) done_LUT4_C_B_L6MUX21_Z_SD_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(\count0.val [1]),
    .D(\count0.val [0]),
    .Z(done_LUT4_C_B_L6MUX21_Z_SD[6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hc000)
  ) done_LUT4_C_B_LUT4_Z (
    .A(1'h0),
    .B(\control0.cont [4]),
    .C(\control0.cont [3]),
    .D(\control0.cont [2]),
    .Z(done_LUT4_C_B[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h000f)
  ) done_LUT4_C_B_LUT4_Z_1 (
    .A(1'h0),
    .B(1'h0),
    .C(\control0.cont [1]),
    .D(\control0.cont [0]),
    .Z(done_LUT4_C_B[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h00f0)
  ) done_LUT4_D (
    .A(1'h0),
    .B(1'h0),
    .C(done_LUT4_C_Z[0]),
    .D(done),
    .Z(done_LUT4_D_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h000c)
  ) done_LUT4_Z (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(done)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'h0032)
  ) init_LUT4_A (
    .A(init),
    .B(rst),
    .C(\control0.state [2]),
    .D(\control0.state [1]),
    .Z(init_LUT4_A_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h0032)
  ) init_LUT4_A_1 (
    .A(init),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(init_LUT4_A_1_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX init_LUT4_A_Z_PFUMX_BLUT (
    .ALUT(init_LUT4_A_Z_PFUMX_BLUT_ALUT),
    .BLUT(init_LUT4_A_Z),
    .C0(\control0.state [0]),
    .Z(done_LUT4_C_D[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'h0000)
  ) init_LUT4_A_Z_PFUMX_BLUT_ALUT_LUT4_Z (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(1'h0),
    .Z(init_LUT4_A_Z_PFUMX_BLUT_ALUT)
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lcr0.s_out_TRELLIS_FF_Q  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[6]),
    .LSR(1'h0),
    .Q(\lcr0.s_out [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lcr0.s_out_TRELLIS_FF_Q_1  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[7]),
    .LSR(1'h0),
    .Q(\lcr0.s_out [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lcr0.s_out_TRELLIS_FF_Q_10  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[15]),
    .LSR(1'h0),
    .Q(\lcr0.s_out [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.s_out_TRELLIS_FF_Q_11  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_15_CE ),
    .CLK(clk),
    .DI(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [27]),
    .LSR(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Q(\lcr0.s_out [27])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.s_out_TRELLIS_FF_Q_12  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_15_CE ),
    .CLK(clk),
    .DI(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [26]),
    .LSR(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Q(\lcr0.s_out [26])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.s_out_TRELLIS_FF_Q_13  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_15_CE ),
    .CLK(clk),
    .DI(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [25]),
    .LSR(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Q(\lcr0.s_out [25])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.s_out_TRELLIS_FF_Q_14  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A[0]),
    .LSR(\lcr0.s_out_TRELLIS_FF_Q_14_LSR ),
    .Q(\lcr0.s_out [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:119.33-120.56" */
  LUT4 #(
    .INIT(16'h000f)
  ) \lcr0.s_out_TRELLIS_FF_Q_14_LSR_LUT4_Z  (
    .A(1'h0),
    .B(1'h0),
    .C(\control0.w_sh_l_LUT4_Z_D ),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_14_LSR )
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.s_out_TRELLIS_FF_Q_15  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_15_CE ),
    .CLK(clk),
    .DI(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [24]),
    .LSR(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Q(\lcr0.s_out [24])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hfa33)
  ) \lcr0.s_out_TRELLIS_FF_Q_15_CE_LUT4_Z  (
    .A(\lcr0.s_out [27]),
    .B(\control0.w_sh_l_LUT4_Z_D ),
    .C(\lcr0.s_out_TRELLIS_FF_Q_15_CE_LUT4_Z_C [2]),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_15_CE )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h5acc)
  ) \lcr0.s_out_TRELLIS_FF_Q_15_CE_LUT4_Z_C_LUT4_C  (
    .A(\lcr0.s_out [27]),
    .B(\lcr0.s_out [26]),
    .C(\lcr0.s_out_TRELLIS_FF_Q_15_CE_LUT4_Z_C [2]),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [27])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccc0)
  ) \lcr0.s_out_TRELLIS_FF_Q_15_CE_LUT4_Z_C_LUT4_Z  (
    .A(1'h0),
    .B(\lcr0.s_out [26]),
    .C(\lcr0.s_out [25]),
    .D(\lcr0.s_out [24]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_15_CE_LUT4_Z_C [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.s_out_TRELLIS_FF_Q_16  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_5_CE ),
    .CLK(clk),
    .DI(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [20]),
    .LSR(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Q(\lcr0.s_out [20])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.s_out_TRELLIS_FF_Q_17  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_27_CE ),
    .CLK(clk),
    .DI(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [17]),
    .LSR(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Q(\lcr0.s_out [17])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.s_out_TRELLIS_FF_Q_18  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_5_CE ),
    .CLK(clk),
    .DI(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [23]),
    .LSR(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Q(\lcr0.s_out [23])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lcr0.s_out_TRELLIS_FF_Q_19  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[1]),
    .LSR(1'h0),
    .Q(\lcr0.s_out [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lcr0.s_out_TRELLIS_FF_Q_2  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[8]),
    .LSR(1'h0),
    .Q(\lcr0.s_out [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.s_out_TRELLIS_FF_Q_20  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_25_CE ),
    .CLK(clk),
    .DI(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [28]),
    .LSR(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Q(\lcr0.s_out [28])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.s_out_TRELLIS_FF_Q_21  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_27_CE ),
    .CLK(clk),
    .DI(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [16]),
    .LSR(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Q(\lcr0.s_out [16])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.s_out_TRELLIS_FF_Q_22  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_25_CE ),
    .CLK(clk),
    .DI(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [31]),
    .LSR(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Q(\lcr0.s_out [31])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.s_out_TRELLIS_FF_Q_23  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_25_CE ),
    .CLK(clk),
    .DI(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [30]),
    .LSR(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Q(\lcr0.s_out [30])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.s_out_TRELLIS_FF_Q_24  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_5_CE ),
    .CLK(clk),
    .DI(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [22]),
    .LSR(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Q(\lcr0.s_out [22])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.s_out_TRELLIS_FF_Q_25  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_25_CE ),
    .CLK(clk),
    .DI(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [29]),
    .LSR(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Q(\lcr0.s_out [29])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hfa33)
  ) \lcr0.s_out_TRELLIS_FF_Q_25_CE_LUT4_Z  (
    .A(\lcr0.s_out [31]),
    .B(\control0.w_sh_l_LUT4_Z_D ),
    .C(\lcr0.s_out_TRELLIS_FF_Q_25_CE_LUT4_Z_C [2]),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_25_CE )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h5acc)
  ) \lcr0.s_out_TRELLIS_FF_Q_25_CE_LUT4_Z_C_LUT4_C  (
    .A(\lcr0.s_out [31]),
    .B(\lcr0.s_out [30]),
    .C(\lcr0.s_out_TRELLIS_FF_Q_25_CE_LUT4_Z_C [2]),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [31])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccc0)
  ) \lcr0.s_out_TRELLIS_FF_Q_25_CE_LUT4_Z_C_LUT4_Z  (
    .A(1'h0),
    .B(\lcr0.s_out [30]),
    .C(\lcr0.s_out [29]),
    .D(\lcr0.s_out [28]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_25_CE_LUT4_Z_C [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.s_out_TRELLIS_FF_Q_26  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_27_CE ),
    .CLK(clk),
    .DI(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [19]),
    .LSR(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Q(\lcr0.s_out [19])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.s_out_TRELLIS_FF_Q_27  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_27_CE ),
    .CLK(clk),
    .DI(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [18]),
    .LSR(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Q(\lcr0.s_out [18])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hfa33)
  ) \lcr0.s_out_TRELLIS_FF_Q_27_CE_LUT4_Z  (
    .A(\lcr0.s_out [19]),
    .B(\control0.w_sh_l_LUT4_Z_D ),
    .C(\lcr0.s_out_TRELLIS_FF_Q_27_CE_LUT4_Z_C [2]),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_27_CE )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h5acc)
  ) \lcr0.s_out_TRELLIS_FF_Q_27_CE_LUT4_Z_C_LUT4_C  (
    .A(\lcr0.s_out [19]),
    .B(\lcr0.s_out [18]),
    .C(\lcr0.s_out_TRELLIS_FF_Q_27_CE_LUT4_Z_C [2]),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [19])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccc0)
  ) \lcr0.s_out_TRELLIS_FF_Q_27_CE_LUT4_Z_C_LUT4_Z  (
    .A(1'h0),
    .B(\lcr0.s_out [18]),
    .C(\lcr0.s_out [17]),
    .D(\lcr0.s_out [16]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_27_CE_LUT4_Z_C [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lcr0.s_out_TRELLIS_FF_Q_28  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[2]),
    .LSR(1'h0),
    .Q(\lcr0.s_out [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lcr0.s_out_TRELLIS_FF_Q_29  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[3]),
    .LSR(1'h0),
    .Q(\lcr0.s_out [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lcr0.s_out_TRELLIS_FF_Q_3  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[9]),
    .LSR(1'h0),
    .Q(\lcr0.s_out [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lcr0.s_out_TRELLIS_FF_Q_30  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[4]),
    .LSR(1'h0),
    .Q(\lcr0.s_out [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lcr0.s_out_TRELLIS_FF_Q_31  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[5]),
    .LSR(1'h0),
    .Q(\lcr0.s_out [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lcr0.s_out_TRELLIS_FF_Q_4  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[10]),
    .LSR(1'h0),
    .Q(\lcr0.s_out [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:83.170-83.229" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET"),
    .SRMODE("LSR_OVER_CE")
  ) \lcr0.s_out_TRELLIS_FF_Q_5  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_5_CE ),
    .CLK(clk),
    .DI(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [21]),
    .LSR(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .Q(\lcr0.s_out [21])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'hfa33)
  ) \lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z  (
    .A(\lcr0.s_out [23]),
    .B(\control0.w_sh_l_LUT4_Z_D ),
    .C(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C [2]),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_5_CE )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h5acc)
  ) \lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C  (
    .A(\lcr0.s_out [23]),
    .B(\lcr0.s_out [22]),
    .C(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C [2]),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [23])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h33f0)
  ) \lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z_LUT4_Z  (
    .A(1'h0),
    .B(\lcr0.s_out [20]),
    .C(\lcr0.s_out [19]),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [20])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h33f0)
  ) \lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z_LUT4_Z_1  (
    .A(1'h0),
    .B(\lcr0.s_out [24]),
    .C(\lcr0.s_out [23]),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [24])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h33f0)
  ) \lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z_LUT4_Z_10  (
    .A(1'h0),
    .B(\lcr0.s_out [28]),
    .C(\lcr0.s_out [27]),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [28])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hc3f0)
  ) \lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z_LUT4_Z_11  (
    .A(1'h0),
    .B(\lcr0.s_out [25]),
    .C(\lcr0.s_out [24]),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [25])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h33f0)
  ) \lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z_LUT4_Z_2  (
    .A(1'h0),
    .B(\lcr0.s_out [16]),
    .C(\lcr0.s_out [15]),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [16])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h56cc)
  ) \lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z_LUT4_Z_3  (
    .A(\lcr0.s_out [18]),
    .B(\lcr0.s_out [17]),
    .C(\lcr0.s_out [16]),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [18])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hc3f0)
  ) \lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z_LUT4_Z_4  (
    .A(1'h0),
    .B(\lcr0.s_out [21]),
    .C(\lcr0.s_out [20]),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [21])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h56cc)
  ) \lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z_LUT4_Z_5  (
    .A(\lcr0.s_out [22]),
    .B(\lcr0.s_out [21]),
    .C(\lcr0.s_out [20]),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [22])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hc3f0)
  ) \lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z_LUT4_Z_6  (
    .A(1'h0),
    .B(\lcr0.s_out [29]),
    .C(\lcr0.s_out [28]),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [29])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hc3f0)
  ) \lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z_LUT4_Z_7  (
    .A(1'h0),
    .B(\lcr0.s_out [17]),
    .C(\lcr0.s_out [16]),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [17])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h56cc)
  ) \lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z_LUT4_Z_8  (
    .A(\lcr0.s_out [30]),
    .B(\lcr0.s_out [29]),
    .C(\lcr0.s_out [28]),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [30])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:128.32-129.56" */
  LUT4 #(
    .INIT(16'h56cc)
  ) \lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z_LUT4_Z_9  (
    .A(\lcr0.s_out [26]),
    .B(\lcr0.s_out [25]),
    .C(\lcr0.s_out [24]),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_C_Z [26])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'hccc0)
  ) \lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C_LUT4_Z  (
    .A(1'h0),
    .B(\lcr0.s_out [22]),
    .C(\lcr0.s_out [21]),
    .D(\lcr0.s_out [20]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lcr0.s_out_TRELLIS_FF_Q_6  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[11]),
    .LSR(1'h0),
    .Q(\lcr0.s_out [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lcr0.s_out_TRELLIS_FF_Q_7  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[12]),
    .LSR(1'h0),
    .Q(\lcr0.s_out [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lcr0.s_out_TRELLIS_FF_Q_8  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[13]),
    .LSR(1'h0),
    .Q(\lcr0.s_out [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "lcr_32.v:9.5-16.8|/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:56.101-56.163" */
  TRELLIS_FF #(
    .CEMUX("CE"),
    .CLKMUX("CLK"),
    .GSR("DISABLED"),
    .LSRMUX("LSR"),
    .REGSET("RESET")
  ) \lcr0.s_out_TRELLIS_FF_Q_9  (
    .CE(\lcr0.s_out_TRELLIS_FF_Q_CE ),
    .CLK(clk),
    .DI(A_LUT4_B_Z[14]),
    .LSR(1'h0),
    .Q(\lcr0.s_out [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h00f3)
  ) \lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z  (
    .A(1'h0),
    .B(\control0.w_sh_l_LUT4_Z_D ),
    .C(\control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2]),
    .D(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_CE )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:124.33-125.56" */
  LUT4 #(
    .INIT(16'h0030)
  ) \lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D_LUT4_Z  (
    .A(1'h0),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(\lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:136.39-137.56" */
  LUT4 #(
    .INIT(16'hfeea)
  ) rst_LUT4_A (
    .A(rst),
    .B(\control0.state [2]),
    .C(\control0.state [1]),
    .D(\control0.state [0]),
    .Z(rst_LUT4_A_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:134.39-135.56" */
  LUT4 #(
    .INIT(16'hff00)
  ) rst_LUT4_D (
    .A(1'h0),
    .B(1'h0),
    .C(1'h0),
    .D(rst),
    .Z(rst_LUT4_D_Z)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/juan/fpga_tools/oss-cad-suite/lib/../share/yosys/lattice/cells_map_trellis.v:138.19-138.63" */
  PFUMX rst_LUT4_D_Z_PFUMX_BLUT (
    .ALUT(rst_LUT4_A_Z),
    .BLUT(rst_LUT4_D_Z),
    .C0(\control0.w_sh_l_LUT4_Z_D ),
    .Z(rst_LUT4_D_Z_PFUMX_BLUT_Z)
  );
  assign done_LUT4_C_Z[1] = done;
  assign \count0.val_TRELLIS_FF_Q_4_DI_LUT4_Z_D [2:0] = { \control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [2], \control0.w_sh_l_LUT4_Z_D , \count0.val [4] };
  assign { \lcr0.s_out_TRELLIS_FF_Q_25_CE_LUT4_Z_C [3], \lcr0.s_out_TRELLIS_FF_Q_25_CE_LUT4_Z_C [1:0] } = { \lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3], \lcr0.s_out [30], \lcr0.s_out [31] };
  assign { \lcr0.s_out_TRELLIS_FF_Q_15_CE_LUT4_Z_C [3], \lcr0.s_out_TRELLIS_FF_Q_15_CE_LUT4_Z_C [1:0] } = { \lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3], \lcr0.s_out [26], \lcr0.s_out [27] };
  assign \lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [2:0] = { \lcr0.s_out [16], \lcr0.s_out [17], \lcr0.s_out [18] };
  assign \control0.w_sh_l_LUT4_Z_D_LUT4_D_Z [1:0] = { \lcr0.s_out [2], A[3] };
  assign { \lcr0.s_out_TRELLIS_FF_Q_27_CE_LUT4_Z_C [3], \lcr0.s_out_TRELLIS_FF_Q_27_CE_LUT4_Z_C [1:0] } = { \lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3], \control0.w_sh_l_LUT4_Z_D , \lcr0.s_out [19] };
  assign { \lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C [3], \lcr0.s_out_TRELLIS_FF_Q_5_CE_LUT4_Z_C [1:0] } = { \lcr0.s_out_TRELLIS_FF_Q_CE_LUT4_Z_D [3], \control0.w_sh_l_LUT4_Z_D , \lcr0.s_out [23] };
  assign done_LUT4_C_B[2] = done;
  assign done_LUT4_C_D[2:0] = { done, done_LUT4_C_B[1:0] };
  assign done_LUT4_C_B_L6MUX21_Z_SD[5:0] = { \control0.state [0], \control0.state [1], \control0.state [2], \count0.val [2], \count0.val [3], \count0.val [4] };
  assign \lcr0.clk  = clk;
  assign \acc0.in_bcd  = \lcr0.s_out [31:16];
  assign \count0.dec  = \control0.w_sh_l ;
  assign \lcr0.in_A  = { 16'h0000, A };
  assign \control0.done  = done;
  assign \count0.clk  = clk;
  assign \control0.init  = init;
  assign \control0.rst  = rst;
  assign \control0.clk  = clk;
  assign \lcr0.shift  = \control0.w_sh_l ;
  assign \comp_z0.val  = \count0.val ;
  assign w_val = \count0.val ;
  assign w_BCD_part = \lcr0.s_out [31:16];
  assign w_combined = \lcr0.s_out ;
  assign w_sh_l = \control0.w_sh_l ;
  assign BCD_out = \lcr0.s_out [31:16];
endmodule
